### ISSUE TITLE
Enhancement: Notifications for new messages of the same conversation

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#1055] opened 2020-07-17 22:18 UTC
**Is your enhancement request related to a problem?**
Browser notifications are triggered (if already enabled) whenever a new conversation is **_created_** or _**assigned**_. However, when new messages arrive at that conversation at a later time, no notifications will be sent, which may cause delays in replying back due to missing out on these new messages at the time they were sent.

**Describe the solution you'd like**
An enhancement to the behavior of the notifications by adding an extra trigger (new message) is going to be of great help.

**Describe alternatives you've considered**
Refreshing or checking out Chatwoot's dashboard every now and then manually.

**Comment by pranavrajs** [comment] 2020-07-18 06:32
This is the duplicate of https://github.com/chatwoot/chatwoot/issues/895. Closing this one to track the changes there.

**Closed by pranavrajs** 2020-07-18 06:32 UTC
