### ISSUE TITLE
Only 10 keyword search results exposed

### ISSUE THREAD

**Issue by jihee-k** [chatwoot/chatwoot#9678] opened 2024-06-25 06:38 UTC
### Describe the bug

1. your API document says Filters conversations with messages containing the search term, but after searching for keywords, only up to 10 results are exposed.

2. Your api document says that paganate through conversations are possible, but it is not exposed on the chatwoot screen.

![image](https://github.com/chatwoot/chatwoot/assets/172241637/d96d64c9-8c12-43c2-88cd-24a326ea0358)

<img width="560" alt="image" src="https://github.com/chatwoot/chatwoot/assets/172241637/8a91e34e-e581-4d49-b70e-f9e1e15a3716">

- and Tell me the criteria for sorting the search results (Or is there no sorting standard?)

### To Reproduce

Environment:
1. self-hosted version
2. conversation screen and 
3. Search for messages in a conversation
4. Keyword search

**Issues**
- Only up to 10 results are exposed.
- Paginate through conversions are not exposed, so more search results are not visible.

### Expected behavior

1. Results containing keywords retrieved from all messages must be exposed.

2. The page through conversations click button must be exposed on the screen.

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

Browser

**Comment by pranavrajs** [comment] 2024-06-25 13:05
@jihee-k This is a know issue. Duplicate of #7329

**Closed by pranavrajs** 2024-06-25 13:05 UTC
Labels: Bug

**Comment by jihee-k** [comment] 2024-06-26 01:40
@pranavrajs thank you.
I checked your inquiry from a year ago. Has there been any improvement?
What's the timeline for improvement?

**Comment by pranavrajs** [comment] 2024-06-26 03:00
@jihee-k At the moment, this is not prioritized, I will add this to our discussions for next releases.
