### ISSUE TITLE
Cannot run migrations due error

### ISSUE THREAD

**Issue by orlando** [chatwoot/chatwoot#1702] opened 2021-01-27 22:53 UTC
**Describe the bug**

On a new installation, when running `rails db:migrate` it fails with the following error.

**To Reproduce**

1. On a new installation, run `rails db:migrate`

**Expected behavior**

Migrations should finish on a new database without errors.

**Screenshots**

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

```ruby
/app # bundle exec rails db:migrate
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
== 20200510112339 CreateInstallationConfig: migrating =========================
-- create_table(:installation_configs)
   -> 0.0171s
-- add_index(:installation_configs, [:name, :created_at], {:unique=>true})
   -> 0.0100s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined local variable or method `locked' for #<InstallationConfig:0x00007f872a11fdd8>
Did you mean?  lock!
/gems/ruby/2.7.0/gems/activemodel-6.0.3.4/lib/active_model/attribute_methods.rb:432:in `method_missing'
/app/app/models/installation_config.rb:39:in `set_lock'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:604:in `catch'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:604:in `block in default_terminator'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:201:in `block in halting'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `each'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:513:in `invoke_before'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:134:in `run_callbacks'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
/gems/ruby/2.7.0/gems/activemodel-6.0.3.4/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/gems/ruby/2.7.0/gems/activemodel-6.0.3.4/lib/active_model/validations.rb:337:in `valid?'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:68:in `valid?'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:84:in `perform_validations'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:47:in `save'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:314:in `block in save'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:212:in `transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:314:in `save'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/suppressor.rb:44:in `save'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:38:in `create'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:100:in `block in create'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:407:in `block in scoping'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:784:in `_scoping'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:407:in `scoping'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:100:in `create'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/relation.rb:169:in `find_or_create_by'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/querying.rb:21:in `find_or_create_by'
/app/lib/config_loader.rb:62:in `save_as_new_config'
/app/lib/config_loader.rb:52:in `save_general_config'
/app/lib/config_loader.rb:43:in `block in reconcile_general_config'
/app/lib/config_loader.rb:40:in `each'
/app/lib/config_loader.rb:40:in `reconcile_general_config'
/app/lib/config_loader.rb:23:in `process'
/app/db/migrate/20200510112339_create_installation_config.rb:11:in `change'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:828:in `exec_migration'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:811:in `block in migrate'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:810:in `migrate'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1002:in `migrate'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:212:in `transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1361:in `ddl_transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1280:in `each'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1229:in `block in migrate'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1229:in `migrate'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1061:in `up'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/migration.rb:1036:in `migrate'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/railties/databases.rake:84:in `each'
/gems/ruby/2.7.0/gems/activerecord-6.0.3.4/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/gems/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/gems/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/gems/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/command.rb:48:in `invoke'
/gems/ruby/2.7.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
/gems/ruby/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
bin/rails:4:in `<main>'
```

**Environment**

Amazon ECS running the official chatwoot image.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I left a comment on this PR https://github.com/chatwoot/chatwoot/pull/1641#issuecomment-767782286, which I think is the one that introduced the error.

**Comment by sojan-official** [comment] 2021-01-28 05:06
@orlando if its a fresh installation.  please use `rake task db:chatwoot_prepare` instead of the `rake db:migrate` .  
running migrations all the way from the start might have error since the underlying data models would have changed in the latest versions of code.  

if the issue is happening while upgrading from an older version to a newer one, do let us know.

**Comment by orlando** [comment] 2021-01-28 20:41
Hey @sojan-official 

Great! Looks like this command did the trick. I think we should add this information to the Docker setup page. Here's a PR for that in case you want to merge it. 

https://github.com/chatwoot/docs/pull/1

Thanks!

**Comment by pranavrajs** [comment] 2021-01-29 11:39
Closing as https://github.com/chatwoot/docs/pull/1 is merged.

**Closed by pranavrajs** 2021-01-29 11:39 UTC
Labels: Bug
