### ISSUE TITLE
Bug: Create label color chooser hide the create button

### ISSUE THREAD

**Issue by atapas** [chatwoot/chatwoot#2636] opened 2021-07-15 11:32 UTC
**Describe the bug**

When I try to create a label, it allows me to select a color for the label. After clicking on the color chooser,  the color selector hide the button to create the label.

**To Reproduce**

1. Go to the 'Labels' menu from the left nav
2. Click on the Add Label button.
3. A modal appears to provide the details
![image](https://user-images.githubusercontent.com/3633137/125780929-c1e9e702-17b2-41a3-b082-f68176a58669.png)
4. Then select a color by clicking on the color selector
5. It hides the create button. It doesn't disappear even when clicking outside of the color selector.
![image](https://user-images.githubusercontent.com/3633137/125781095-f643514a-a5b8-47ae-8e6c-3831175855bf.png)

**Expected behavior**

The create button should be visible to create the label.

![image](https://user-images.githubusercontent.com/3633137/125781256-3bd787e6-83e9-45dc-b226-6d08e29ab5e1.png)

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

Cloud

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Window 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 91

**Smartphone (please complete the following information):**

**Additional context**

**Comment by muhsin-k** [comment] 2021-07-15 12:03
Closing this as it is a duplicate of #1228

**Closed by muhsin-k** 2021-07-15 12:03 UTC
