### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by seblas81** [chatwoot/chatwoot#9767] opened 2024-07-12 03:42 UTC
### Describe the bug

Using Ubuntu 20 or 22
I get an error in husky compilation.
Compilation fails and it's aborted.

### To Reproduce

1 ubuntu 20
2 installer setup_20.04.sh

### Expected behavior

That works

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20

### Browser and version

Google Chrome

### Docker (if applicable)

No

### Additional context

No

**Comment by vishnu-narayanan** [comment] 2024-07-15 11:28
@seblas81 Please share the logs from installation.

**Comment by solracsf** [comment] 2024-07-21 15:00
Same problem here.

```
➥ 1/9 Installing dependencies. This takes a while.
File '/usr/share/keyrings/redis-archive-keyring.gpg' exists. Overwrite? (y/N) y
File '/etc/apt/keyrings/nodesource.gpg' exists. Overwrite? (y/N) y
➥ 2/9 Installing databases.
➥ 3/9 Installing webserver.
➥ 4/9 Setting up Ruby
➥ 5/9 Setting up the database.
➥ 6/9 Installing Chatwoot. This takes a long while.

Some error has occured. Check '/var/log/chatwoot-setup.log' for details.
```

```
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@chatwoot/prosemirror-schema > prosemirror-utils@0.9.6" has incorrect peer dependency "prosemirror-tables@^0.9.1".
warning " > vue-easytable@2.5.5" has unmet peer dependency "lodash@^4.17.20".
warning " > vue-loader@15.10.2" has unmet peer dependency "css-loader@*".
warning " > vuex-router-sync@4.1.3" has incorrect peer dependency "vue-router@^2.0.0".
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components > react-syntax-highlighter@15.5.0" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".
warning "@storybook/addon-docs > @storybook/addons@6.5.16" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/addons@6.5.16" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/api@6.5.16" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/api@6.5.16" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/components@6.5.16" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/components@6.5.16" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/core-common@6.5.16" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/core-common@6.5.16" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/preview-web@6.5.16" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/preview-web@6.5.16" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/source-loader@6.5.16" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/source-loader@6.5.16" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/store@6.5.16" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/store@6.5.16" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/theming@6.5.16" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/theming@6.5.16" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/addons > @storybook/router@6.5.16" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/addons > @storybook/router@6.5.16" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/core-common > fork-ts-checker-webpack-plugin@6.5.3" has unmet peer dependency "typescript@>= 2.7".
warning "@storybook/addon-essentials > @storybook/core-common@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/core-common@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > @storybook/vue@6.5.9" has unmet peer dependency "css-loader@*".
warning "@storybook/vue > ts-loader@8.4.0" has unmet peer dependency "typescript@*".
warning " > @vitejs/plugin-vue2@2.3.1" has unmet peer dependency "vite@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "eslint-plugin-storybook > @typescript-eslint/utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 306.31s.
/usr/local/rvm/gems/ruby-3.3.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: /usr/local/rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/mutex_m.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of activesupport-7.0.8.4 to add mutex_m into its gemspec.
DEPRECATION WARNING: Dotenv::Railtie is deprecated! Use Dotenv::Rails instead. (called from <top (required)> at /home/chatwoot/chatwoot/config/application.rb:14)
I, [2024-07-21T14:42:17.299108 #30803]  INFO -- : [dotenv] Loaded .env
I, [2024-07-21T14:42:17.299303 #30803]  INFO -- : [dotenv] Loaded .env
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
Done in 1.55s.
I, [2024-07-21T14:42:20.822166 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/manifest-90aab26ade71e747f745b1227b433fd7d580a54f279ee2be6e1a67bb326bf03a.js
I, [2024-07-21T14:42:20.822819 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/manifest-90aab26ade71e747f745b1227b433fd7d580a54f279ee2be6e1a67bb326bf03a.js.gz
I, [2024-07-21T14:42:20.823754 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-55cff82ac5edfdd84892a493c6a11c700f91eddfd221ef5e48fe2a6d910cc4aa.css
I, [2024-07-21T14:42:20.824500 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-55cff82ac5edfdd84892a493c6a11c700f91eddfd221ef5e48fe2a6d910cc4aa.css.gz
I, [2024-07-21T14:42:20.826174 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-0ca1ebe5baf40d486024c2af43f59c99db8ee966ae8440eaa75b247d725f91f1.js
I, [2024-07-21T14:42:20.827405 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-0ca1ebe5baf40d486024c2af43f59c99db8ee966ae8440eaa75b247d725f91f1.js.gz
I, [2024-07-21T14:42:20.828342 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate-field-active_storage/application-491e0febefaa4b7923c60e77838dadb71e679fcc07232cd97198fb364d300152.css
I, [2024-07-21T14:42:20.828928 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate-field-active_storage/application-491e0febefaa4b7923c60e77838dadb71e679fcc07232cd97198fb364d300152.css.gz
I, [2024-07-21T14:42:20.831238 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-2e4c5a7faeb8c684ad4d6b3f713605212c572f00d77c11bd74dcc29291fb50b9.js
I, [2024-07-21T14:42:20.831732 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-2e4c5a7faeb8c684ad4d6b3f713605212c572f00d77c11bd74dcc29291fb50b9.js.gz
I, [2024-07-21T14:42:20.833268 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/secretField-72cf0cbaa1d0c6b6a1a79d79e61649722f0612e6334a0f18929b04c145e3c024.js
I, [2024-07-21T14:42:20.833758 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/secretField-72cf0cbaa1d0c6b6a1a79d79e61649722f0612e6334a0f18929b04c145e3c024.js.gz
I, [2024-07-21T14:42:20.833953 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-2e4c5a7faeb8c684ad4d6b3f713605212c572f00d77c11bd74dcc29291fb50b9.js
I, [2024-07-21T14:42:20.834064 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-2e4c5a7faeb8c684ad4d6b3f713605212c572f00d77c11bd74dcc29291fb50b9.js.gz
I, [2024-07-21T14:42:20.834214 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actiontext-28c61f5197c204db043317a8f8826a87ab31495b741f854d307ca36122deefce.js
I, [2024-07-21T14:42:20.834321 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actiontext-28c61f5197c204db043317a8f8826a87ab31495b741f854d307ca36122deefce.js.gz
I, [2024-07-21T14:42:20.834490 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/trix-df2bf484e34719e3b4933ba6bc3139eb1e7ad4fbbedb13bbd04be4d80b42664a.js
I, [2024-07-21T14:42:20.834624 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/trix-df2bf484e34719e3b4933ba6bc3139eb1e7ad4fbbedb13bbd04be4d80b42664a.js.gz
I, [2024-07-21T14:42:20.834777 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/trix-6fd35bb8fae1d6a795115763ca265369b9750f73a1c6283a0b0ef4b6c2d550c8.css
I, [2024-07-21T14:42:20.834870 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/trix-6fd35bb8fae1d6a795115763ca265369b9750f73a1c6283a0b0ef4b6c2d550c8.css.gz
I, [2024-07-21T14:42:20.835016 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-0ca1ebe5baf40d486024c2af43f59c99db8ee966ae8440eaa75b247d725f91f1.js.gz
I, [2024-07-21T14:42:20.835244 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/belongs_to_search-25faa07e8d60e491e6f1218e5307b9e70ea1bb0a51e4a724a37e797cea81e9da.js
I, [2024-07-21T14:42:20.835338 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/belongs_to_search-25faa07e8d60e491e6f1218e5307b9e70ea1bb0a51e4a724a37e797cea81e9da.js.gz
I, [2024-07-21T14:42:20.835471 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage-3ab61e47dd4ee2d79db525ade1dca2ede0ea2b7371fe587e408ee37b7ade265d.js
I, [2024-07-21T14:42:20.837170 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage-3ab61e47dd4ee2d79db525ade1dca2ede0ea2b7371fe587e408ee37b7ade265d.js.gz
I, [2024-07-21T14:42:20.837553 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage.esm-01f58a45d77495cdfbdfcc872902a430426c4391634ec9c3da5f69fbf8418492.js
I, [2024-07-21T14:42:20.840258 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage.esm-01f58a45d77495cdfbdfcc872902a430426c4391634ec9c3da5f69fbf8418492.js.gz
I, [2024-07-21T14:42:20.842037 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable-5433453f9b6619a9de91aaab2d7fc7ff183e5260c0107cbc9a1aa0c838d9a74e.js
I, [2024-07-21T14:42:20.842305 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable-5433453f9b6619a9de91aaab2d7fc7ff183e5260c0107cbc9a1aa0c838d9a74e.js.gz
I, [2024-07-21T14:42:20.842524 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable.esm-e01089c3ec4fe7817fa9abcad06cab6bdc387f95f0ca6aab4bf7ba7537f70690.js
I, [2024-07-21T14:42:20.842687 #30803]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable.esm-e01089c3ec4fe7817fa9abcad06cab6bdc387f95f0ca6aab4bf7ba7537f70690.js.gz
Compiling...
Compilation failed:
```

**Comment by solracsf** [comment] 2024-07-21 15:18
In my case it was a duplicate of https://github.com/chatwoot/chatwoot/issues/9676

**Closed** 2024-10-02 07:36 UTC
Labels: need-more-info, self-hosted, waiting-for-reply, 🐧 self-hosted/linux
