### ISSUE TITLE
Banning/Blacklisting numbers

### ISSUE THREAD

**Issue by hldpzz** [chatwoot/chatwoot#8364] opened 2023-11-16 20:49 UTC
### Is your feature or enhancement related to a problem? Please describe.

Hey chatwoot team!

Im currently self hosting a chatwoot instance for 50 people and they use heavily the whatsapp connected inboxes.
I believe it is a big issue the question of abusive numbers, that send thousands of messages to the connected whatsapp business API.
On the platform we can already mute and solve the conversation but that does not stop the messages from coming and using the server's resources - when they are, for example, thousands of heavy images.
A coordinated agent can easily mobilize dozens of whatsapp numbers with an unnoficial API and spam an inbox with images.

In this sense, i believe there should be a "ban number" feature, to block the webhook call in its origin and prevent further abuse, and, if possible, an automatic spam detection

### Describe the solution you'd like

A ban number/add to blacklist feature, to block WABA webhook calls from abusive numbers, and, if possible, a spam prevention feature to automatically add abusive requests to the banned list.

### Describe alternatives you've considered

Adding abusive contacts to a team with nobody
Assign abusive contact to a blank agent
Muting abusive contacts

In all the workarounds the messages are still processed.

**Comment by hldpzz** [comment] 2023-11-23 18:48
Hey guys, any tought about this yet?

**Comment by pranavrajs** [comment] 2023-12-01 03:44
@hldpzz Thanks for the note. This is a duplicate of https://github.com/chatwoot/chatwoot/issues/3996. We will prioritize this in the upcoming updates.

**Closed by pranavrajs** 2023-12-01 03:44 UTC
