### ISSUE TITLE
No received email more

### ISSUE THREAD

**Issue by movilreup** [chatwoot/chatwoot#7721] opened 2023-08-14 05:35 UTC
### Describe the bug

Hello Support.

I upgrade from 2.18 to 3.0 to test and atfer upgrade the scritp no received more the fowards emails. in version 2.18 received all emails perfectly but in 3 show the logs delivery but no delivery in the script inbox. attacht here my postfix logs
.

```
Aug 14 01:31:50 vmi1375885 postfix/smtpd[122754]: connect from sender4-of-f72.zoho.com[136.143.188.72]
Aug 14 01:31:51 vmi1375885 postfix/smtpd[122754]: 62F0D922830: client=sender4-of-f72.zoho.com[136.143.188.72]
Aug 14 01:31:51 vmi1375885 postfix/cleanup[122759]: 62F0D922830: message-id=<189f28762c5.3f360d92-694087415.1892291553986743842@zoho.com>
Aug 14 01:31:51 vmi1375885 postfix/qmgr[104327]: 62F0D922830: from=<support+uml_=c0c9a168eaad5c1c60524a160820fce6=csmovilreup.com@movilreup.com>, size=3732, nrcpt=1 (queue active)
Aug 14 01:31:51 vmi1375885 postfix/smtpd[122754]: disconnect from sender4-of-f72.zoho.com[136.143.188.72] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Aug 14 01:31:51 vmi1375885 postfix/pipe[122760]: 62F0D922830: to=<chatwoot@csmovilreup.com>, orig_to=<c0c9a168eaad5c1c60524a160820fce6@csmovilreup.com>, relay=forward_to_rails, delay=0.48, delays=0.41/0/0/0.08, dsn=2.0.0, status=sent (delivered via forward_to_rails service)
Aug 14 01:31:51 vmi1375885 postfix/qmgr[104327]: 62F0D922830: removed
```

### To Reproduce

postfix logs
```
Aug 14 01:31:50 vmi1375885 postfix/smtpd[122754]: connect from sender4-of-f72.zoho.com[136.143.188.72]
Aug 14 01:31:51 vmi1375885 postfix/smtpd[122754]: 62F0D922830: client=sender4-of-f72.zoho.com[136.143.188.72]
Aug 14 01:31:51 vmi1375885 postfix/cleanup[122759]: 62F0D922830: message-id=<189f28762c5.3f360d92-694087415.1892291553986743842@zoho.com>
Aug 14 01:31:51 vmi1375885 postfix/qmgr[104327]: 62F0D922830: from=<support+uml_=c0c9a168eaad5c1c60524a160820fce6=csmovilreup.com@movilreup.com>, size=3732, nrcpt=1 (queue active)
Aug 14 01:31:51 vmi1375885 postfix/smtpd[122754]: disconnect from sender4-of-f72.zoho.com[136.143.188.72] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Aug 14 01:31:51 vmi1375885 postfix/pipe[122760]: 62F0D922830: to=<chatwoot@csmovilreup.com>, orig_to=<c0c9a168eaad5c1c60524a160820fce6@csmovilreup.com>, relay=forward_to_rails, delay=0.48, delays=0.41/0/0/0.08, dsn=2.0.0, status=sent (delivered via forward_to_rails service)
Aug 14 01:31:51 vmi1375885 postfix/qmgr[104327]: 62F0D922830: removed

```

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment] 2023-08-15 18:48
@movilreup It is a bit hard to understand the setup. Are you using a normal SMTP/IMAP authentication here?

**Comment by movilreup** [comment] 2023-08-16 04:06
@pranavrajs I used the fowarding email services via postfix ,and after upgrade from 2.18 to 3.0 show in log delivery but not show in the panel the message received via email.

**Comment by pranavrajs** [comment] 2023-08-16 18:19
@movilreup Can you please try with a new email and see if it reproducible? Without a reproducible step, it is hard to debug what it is going on.

**Comment by sojan-official** [comment] 2024-02-01 13:44
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.

**Closed by sojan-official** 2024-02-01 13:44 UTC
Labels: need-more-info, 📮 channel/email
