### ISSUE TITLE
500 Error: Unable to Update IMAP Settings

### ISSUE THREAD

**Issue by gtmadev** [chatwoot/chatwoot#4562] opened 2022-04-26 16:27 UTC
**Describe the bug**

When attempting to configure an IMAP account, I get a generic error: Unable to Update IMAP Settings.

**To Reproduce**

1. Go to inbox settings for an email channel
2. Click on configuration
3. Click checkbox to enable IMAP
4. Add IMAP settings, click "Update IMAP Settings"
5. See error: "Unable to Update IMAP Settings"

**Expected behavior**

Should see message "IMAP settings updated successfully". Or, if not successful, I would expect to at least see some kind of useful error message telling me what exactly went wrong or send me the IMAP server response, or something I can use to know what I need to change/fix. In this case however, the server-side error (see below) is `unknown attribute 'imap_login' for Channel::Email`.

**Screenshots**

![Screenshot_141](https://user-images.githubusercontent.com/30833539/165344907-10b909a4-1969-4ee3-a8be-4764f29b72e4.png)

**Browser logs**

post payload:
`{  "channel": 
    {"imap_enabled":true,
"imap_address":"mail.xxxx.net","imap_port":993,"imap_login":"support@xxxxx.app","imap_password":"xxxxxxxxxx","imap_enable_ssl":true,"imap_inbox_synced_at":"2022-04-26T16:11:16.282Z"}}`

response payload:
`{"status":500,"error":"Internal Server Error"}`

**Server logs**

`I, [2022-04-26T16:01:12.763801 #1]  INFO -- : [c6910129-a7b1-4751-939a-2ce8311a9ecd] Started PATCH "/api/v1/accounts/2/inboxes/8" for 10.0.10.15 at 2022-04-26 16:01:12 +0000
I, [2022-04-26T16:01:12.765554 #1]  INFO -- : [c6910129-a7b1-4751-939a-2ce8311a9ecd] Processing by Api::V1::Accounts::InboxesController#update as JSON
I, [2022-04-26T16:01:12.765610 #1]  INFO -- : [c6910129-a7b1-4751-939a-2ce8311a9ecd]   Parameters: {"channel"=>{"imap_enabled"=>true, "imap_address"=>"mail.xxxxx.net", "imap_port"=>993, "imap_login"=>"support@xxxxxx.app", "imap_password"=>"[FILTERED]", "imap_enable_ssl"=>true, "imap_inbox_synced_at"=>"2022-04-26T16:01:12.755Z"}, "account_id"=>"2", "id"=>"8", "inbox"=>{}}
I, [2022-04-26T16:01:13.340693 #1]  INFO -- : [c6910129-a7b1-4751-939a-2ce8311a9ecd] Completed 500 Internal Server Error in 575ms (ActiveRecord: 2.9ms | Allocations: 6538)
F, [2022-04-26T16:01:13.341276 #1] FATAL -- : [c6910129-a7b1-4751-939a-2ce8311a9ecd]   
[c6910129-a7b1-4751-939a-2ce8311a9ecd] ActiveModel::UnknownAttributeError (unknown attribute 'imap_login' for Channel::Email.):`

**Environment**

Self-hosted
Docker image: image: chatwoot/chatwoot:latest-ce

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave (chrome)
 - Version: V1.37.116 (Apr 14, 2022)

**Additional context**

In a previous build (I think a dev build), I was able to configure outgoing SMTP without IMAP. I don't need IMAP as I am using webhooks to forward email to the server (for inbound as well a conversation continuity). Given the server error of `unknown attribute 'imap_login' for Channel::Email`, this seems like some issue with the model?

**Comment by pranavrajs** [comment] 2022-04-26 16:39
@gtmadev Did you run rake `db:migrate` after updating the image. It seems like the attribute is missing which is most likely due to missing database migration.

**Comment by gtmadev** [comment] 2022-04-26 16:44
I jumped into the Rails container and tried running that. Note: I am NOT a Rails dev, so I am just trying this without really knowing much about Rails. The output follows. am I running this from the wrong path?

`/app # rake db:migrate
rake aborted!
Gem::LoadError: You have already activated rake 13.0.3, but your Gemfile requires rake 13.0.6. Prepending `bundle exec` to your command may solve this.
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/runtime.rb:309:in `check_for_activated_spec!'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/runtime.rb:25:in `block in setup'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/spec_set.rb:136:in `each'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/spec_set.rb:136:in `each'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/runtime.rb:24:in `map'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/runtime.rb:24:in `setup'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler.rb:151:in `setup'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/setup.rb:10:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/ui/shell.rb:136:in `with_level'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/ui/shell.rb:88:in `silence'
/usr/local/bundle/gems/bundler-2.3.12/lib/bundler/setup.rb:10:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/app/config/boot.rb:3:in `<top (required)>'
/app/config/application.rb:3:in `require_relative'
/app/config/application.rb:3:in `<top (required)>'
/app/Rakefile:4:in `require_relative'
/app/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
/app # `

**Comment by gtmadev** [comment] 2022-04-26 16:47
Okay.. I followed this guidance.. `Prepending `bundle exec` to your command may solve this.`, and the command worked. So I will try to see if I can now update IMAP.

**Comment by gtmadev** [comment] 2022-04-26 16:48
And... we are good. IMAP Settings accepted and all working again. Thanks for the tip!

**Comment by pranavrajs** [comment] 2022-04-26 16:50
Closing this as the issue is solved. :)

**Closed by pranavrajs** 2022-04-26 16:50 UTC
