### ISSUE TITLE
Can't set up SMTP connection, can't get info about the error

### ISSUE THREAD

**Issue by floatingpurr** [chatwoot/chatwoot#6181] opened 2023-01-05 09:46 UTC
Hi there, I'm working with the docker installation of chatwoot. I left the .env file untouched apart from the passwords for redis and postegres (is this ok?). 

When I spin up the containers, everything runs smoothly. Then, I set up a new INBOX with IMAP and SMTP.  I can see incoming emails but replies are never delivered. I guess there's a problem with the SMTP config, however, I can't see any debugging info in the application logs. You can't neither try the smtp settings with a test message.

Here are my SMTP settings

<img width="1123" alt="a" src="https://user-images.githubusercontent.com/14820600/210754089-bcb04ecf-79e4-4180-8ed8-a32c6bbc1454.png">

Is there a way to troubleshoot this error?

**Comment by GuiVKDigital** [comment] 2023-01-06 20:25
I'm with the same issue with Outlook. I was using Google Workspace and now I can't connect with Outlook

**Comment by vishnu-narayanan** [comment] 2023-01-12 03:08
@floatingpurr @GuiVKDigital Could you check and share the error logs from your instances? Look into sideqkiq logs.

**Comment by vishnu-narayanan** [comment] 2023-01-12 03:12
@GuiVKDigital Microsoft has deprecated support for basic auth and going forward will only support OAuth for authentication. That could be a reason why Outlook is not working.

We are working on adding support for OAuth to Chatwoot. Please track the progress here.
https://github.com/chatwoot/chatwoot/issues/5724

**Comment by floatingpurr** [comment] 2023-01-12 11:34
Hi @vishnu-narayanan, thanx for your answer. Strangely enough, setting the same params in the .env file AND setting also the mailbox in the UI fixed the problem. I believed that setting up a mailbox in the UI was enough. Is chatwoot supposed to behave that way?

**Comment by vishnu-narayanan** [comment] 2023-02-28 08:57
I am closing this as the issue is resolved.

**Closed by vishnu-narayanan** 2023-02-28 08:57 UTC
