### ISSUE TITLE
Geolite2 support for IP geocoding

### ISSUE THREAD

**Issue by Lucasvo1** [chatwoot/chatwoot#5493] opened 2022-09-24 11:57 UTC
At the moment, there is support for Maxmind's GeoIP2 commercial license, but it would be great if there also would be support for their free license, Geolite2. Other free alternatives like ip-api.com would also be great.

**Comment by pranavrajs** [comment] 2022-09-27 00:50
@Lucasvo1 The support for the free license is already there. Can you please share if you face any issues? Closing it for now.

**Closed by pranavrajs** 2022-09-27 00:50 UTC

**Comment by Lucasvo1** [comment] 2022-09-28 15:40
Hi, it seems there is a problem with the automation rule based on country. If we save an automation with a country as a condition, the condition is not saved when updating the automation rule.

**Comment by vishnu-narayanan** [comment] 2022-10-03 08:39
@Lucasvo1 The automation rules are saved successfully and should work as you would expect them to. I have tried to reproduce this issue and looks like the UI is having an issue displaying it correctly. I have opened #5540 to track this.
