### ISSUE TITLE
502 internal server error on deploying version 2.6.0 via Docker. undefined local variable or method `auto_assignment_config' 

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#4929] opened 2022-06-26 08:48 UTC
**Describe the bug**
Updated our instance of self-hosted chatwoot to 2.6.0 today. The local dev env works fine which is run using Procfile.dev and not Docker. But, on deploying to our AWS server the deployment fails with the 502  bad gateway errors as shown under the server logs error.

**Expected behavior**

The migrations on deployment should work.

**Browser logs**

N/A

**Server logs**

```
Bundle complete! 99 Gemfile dependencies, 201 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Bundled gems are installed into `/gems`
+ BUNDLE='bundle check'
+ bundle check
The Gemfile's dependencies are satisfied
+ exec /bin/sh -c 'bundle exec rails db:chatwoot_prepare ; bundle exec rails db:migrate ; bundle exec rails s -b 0.0.0.0 -p 3000'
I, [2022-06-26T08:39:30.213077 #12]  INFO -- : Migrating to AddAllowMessagesAfterResolvedToInbox (20211216110209)
== 20211216110209 AddAllowMessagesAfterResolvedToInbox: migrating =============
-- add_column(:inboxes, :allow_messages_after_resolved, :boolean, {:default=>true})
   -> 0.0069s
rails aborted!
I, [2022-06-26T08:39:30.585711 #12]  INFO -- sentry: [Transport] Sending envelope with items [event] 74c0855800cb4c48bb6b08c389b10233 to Sentry
StandardError: An error has occurred, this and all later migrations canceled:
undefined local variable or method `auto_assignment_config' for #<Inbox id: 56, channel_id: 25, account_id: 2, name: "Live Chat", created_at: "2021-10-02 12:28:10.111802000 +0000", updated_at: "2021-10-02 12:50:58.250694000 +0000", channel_type: "Channel::WebWidget", enable_auto_assignment: true, greeting_enabled: true, greeting_message: "Please give us a moment to get back 😊", email_address: nil, working_hours_enabled: true, out_of_office_message: "We are unavailable at the moment. Leave a message ...", timezone: "Asia/Kolkata", enable_email_collect: false, csat_survey_enabled: true, allow_messages_after_resolved: false>
/app/enterprise/app/models/enterprise/inbox.rb:15:in `ensure_valid_max_assignment_limit'
/app/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:12:in `block (2 levels) in update_csat_enabled_inboxes'
/app/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:10:in `each'
/app/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:10:in `block in update_csat_enabled_inboxes'
/app/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:9:in `update_csat_enabled_inboxes'
/app/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:5:in `change'
/app/lib/tasks/db_enhancements.rake:27:in `block (3 levels) in <main>'
/app/lib/tasks/db_enhancements.rake:18:in `each'
/app/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'
Caused by:
NameError: undefined local variable or method `auto_assignment_config' for #<Inbox id: 56, channel_id: 25, account_id: 2, name: "Live Chat", created_at: "2021-10-02 12:28:10.111802000 +0000", updated_at: "2021-10-02 12:50:58.250694000 +0000", channel_type: "Channel::WebWidget", enable_auto_assignment: true, greeting_enabled: true, greeting_message: "Please give us a moment to get back 😊", email_address: nil, working_hours_enabled: true, out_of_office_message: "We are unavailable at the moment. Leave a message ...", timezone: "Asia/Kolkata", enable_email_collect: false, csat_survey_enabled: true, allow_messages_after_resolved: false>
/app/enterprise/app/models/enterprise/inbox.rb:15:in `ensure_valid_max_assignment_limit'
/app/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:12:in `block (2 levels) in update_csat_enabled_inboxes'
/app/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:10:in `each'
/app/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:10:in `block in update_csat_enabled_inboxes'
/app/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:9:in `update_csat_enabled_inboxes'
/app/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:5:in `change'
/app/lib/tasks/db_enhancements.rake:27:in `block (3 levels) in <main>'
/app/lib/tasks/db_enhancements.rake:18:in `each'
/app/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
E, [2022-06-26T08:39:30.684576 #12] ERROR -- sentry: Event sending failed: the server responded with status 429
I, [2022-06-26T08:39:30.693119 #12]  INFO -- sentry: Unreported Event: NameError: undefined local variable or method `auto_assignment_config' for #<Inbox id: 56, channel_id: 25, account_id: 2, name: "Live Chat", created_at: "2021-10-02 12:28:10.111802000 +0000", updated_at: "2021-10-02 12:50:58.250694000 +0000", channel_type: "Channel::WebWidget", enable_auto_assignment: true, greeting_enabled: true, greeting_message: "Please give us a moment to get back 😊", email_address: nil, working_hours_enabled: true, out_of_office_message: "We are unavailable at the moment. Leave a message ...", timezone: "Asia/Kolkata", enable_email_collect: false, csat_survey_enabled: true, allow_messages_after_resolved: false>
E, [2022-06-26T08:39:30.699766 #12] ERROR -- sentry: exception happened in background worker: the server responded with status 429
rails aborted!
ActiveRecord::ConcurrentMigrationError: 
Cannot run migrations because another migration process is currently running.
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
I, [2022-06-26T08:39:42.590938 #16]  INFO -- sentry: [Transport] Sending envelope with items [event] 452c729890834217a7e587ab10dc875e to Sentry
=> Booting Puma
=> Rails 6.1.5.1 application starting in production 
=> Run `bin/rails server --help` for more startup options
W, [2022-06-26T08:39:53.757741 #1]  WARN -- : Creating scope :open. Overwriting existing method Conversation.open.
[1] Puma starting in cluster mode...
[1] * Puma version: 5.6.4 (ruby 3.0.4-p208) ("Birdie's Version")
[1] *  Min threads: 5
[1] *  Max threads: 5
[1] *  Environment: production
[1] *   Master PID: 1
[1] *      Workers: 1
[1] *     Restarts: (✔) hot (✖) phased
[1] * Preloading application
[1] * Listening on http://0.0.0.0:3000
[1] Use Ctrl-C to stop
[1] ! WARNING: Detected running cluster mode with 1 worker.

```
**Environment**

Self hosted chatwoot on AWS K8s via Docker file.
```
# pre-build stage
FROM ruby:3.0.4-alpine AS pre-builder

# ARG default to production settings
# For development docker-compose file overrides ARGS
ARG BUNDLE_WITHOUT="development:test"
ENV BUNDLE_WITHOUT ${BUNDLE_WITHOUT}
ENV BUNDLER_VERSION=2.1.2

ARG RAILS_SERVE_STATIC_FILES=true
ENV RAILS_SERVE_STATIC_FILES ${RAILS_SERVE_STATIC_FILES}

ARG RAILS_ENV=production
ENV RAILS_ENV ${RAILS_ENV}

ENV BUNDLE_PATH="/gems"

RUN apk update \
  && apk add \
    openssl \
    tar \
    build-base \
    tzdata \
    postgresql-dev \
    postgresql-client \
    nodejs \
    yarn \
    git \
  && mkdir -p /var/app \
  && gem install bundler

RUN mkdir -p /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./

# Do not install development or test gems in production
RUN if [ "$RAILS_ENV" = "production" ]; then \
  bundle config set without 'development test'; bundle install -j 4 -r 3; \
  else bundle install -j 4 -r 3; \
  fi

COPY package.json yarn.lock ./
RUN yarn install

COPY . /app

# generate production assets if production environment
RUN if [ "$RAILS_ENV" = "production" ]; then \
  SECRET_KEY_BASE=precompile_placeholder RAILS_LOG_TO_STDOUT=enabled bundle exec rake assets:precompile; \
  fi

# final build stage
FROM ruby:3.0.4-alpine

ARG BUNDLE_WITHOUT="development:test"
ENV BUNDLE_WITHOUT ${BUNDLE_WITHOUT}
ENV BUNDLER_VERSION=2.1.2

ARG EXECJS_RUNTIME="Disabled"
ENV EXECJS_RUNTIME ${EXECJS_RUNTIME}

ARG RAILS_SERVE_STATIC_FILES=true
ENV RAILS_SERVE_STATIC_FILES ${RAILS_SERVE_STATIC_FILES}

ARG RAILS_ENV=production
ENV RAILS_ENV ${RAILS_ENV}
ENV BUNDLE_PATH="/gems"

RUN apk add --update --no-cache \
    openssl \
    tzdata \
    postgresql-client \
    imagemagick \
  && gem install bundler

RUN if [ "$RAILS_ENV" = "production" ]; then \
  rm -rf spec node_modules app/assets vendor/assets tmp/cache; \
  else apk add nodejs yarn; \
  fi

COPY --from=pre-builder /gems/ /gems/
COPY --from=pre-builder /app /app

# Remove unnecessary files
# RUN rm -rf /gems/ruby/3.0.4/cache/*.gem \
#   && find /gems/ruby/3.0.4/gems/ -name "*.c" -delete \
#   && find /gems/ruby/3.0.4/gems/ -name "*.o" -delete

# creating a log directory so that image wont fail when  RAILS_LOG_TO_STDOUT is false
# https://github.com/chatwoot/chatwoot/issues/701
RUN mkdir -p /app/log

WORKDIR /app

COPY docker/entrypoints/rails.sh docker/entrypoints/rails.sh
RUN chmod +x docker/entrypoints/rails.sh
ENTRYPOINT ["docker/entrypoints/rails.sh"]
CMD bundle exec rails db:chatwoot_prepare ; bundle exec rails db:migrate ; bundle exec rails s -b 0.0.0.0 -p 3000

```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Amazon Linux
 - Browser [e.g. chrome, safari] - All
 - Version [e.g. 22] - Latest

**Comment by srameshr** [comment] 2022-06-28 02:36
@sojan-official From 1.22.0. My self-hosted version was on 1.22.0 and the latest master pull I took was from 2.6.0 which I merged with no errors and runs fine locally.

**Comment by pranavrajs** [comment] 2022-06-28 05:06
@srameshr You cannot update it directly from 1.22.0 to 2.6.0, please update to 2.0 -> 2.1 -> 2.2 and so on. You would need to do it sequentially to make sure that the migrations are properly run. Closing this here as the issue is not a bug, but the steps taken in the update.

**Closed by pranavrajs** 2022-06-28 05:06 UTC

**Comment by srameshr** [comment] 2022-06-28 08:32
@pranavrajs Have you deleted the older branches? Cant seem to pull from those branches.

**Comment by srameshr** [comment] 2022-06-28 08:34
@pranavrajs But, looks like you have deleted old branches. How can I pull from that specific branch or release now?

**Comment by srameshr** [comment] 2022-06-28 09:44
Got it. Il do it via cherrypicking commits on each release

**Comment by devinellis** [comment] 2022-07-27 05:06
FWIW I had the same issue but found this solution on Discord first: https://discord.com/channels/647412545203994635/650257251856285707/990972847306465290

```bundle exec rails db:chatwoot_prepare ; bundle exec rails db:migrate```

Interesting that the migration didn't run automatically when the latest image was pulled and started?
