### ISSUE TITLE
[CW-1400] Getting Microsoft Email working with Chatwoot in 2023

### ISSUE THREAD

**Issue by evolve2k** [chatwoot/chatwoot#6729] opened 2023-03-22 02:08 UTC
**As of 2023 basic auth is totally removed** (following Microsofts deprecation notices in 2022).

Getting Microsoft Email has become complicated in 2023  and Microsoft arent helping things.
This issue is to address a range of issues that are making it hard to setup Microsoft email for use with Chatwoot.

1. Microsoft Publisher Verification not required for Single Tenancy Access ("emails at one domain")

Until last week the guide implied (at least from the screenshots) to setup with multi-tenancy access when you register your Azure Application. If you only want to support email inboxes at a single domain, time-consuming organisational verification is not required. The guide being is updated to make 'single tenancy access' recommended, and to explain whats involved if  you want multi-tenancy. This was approved recently, and as time of writing is now live! 🙌
https://github.com/chatwoot/docs/pull/389

3. Single tenancy access setup currently causes an error in the logs 

Setup as single tenancy access generates an error in the server logs, like this:
`[Your Application] is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.`

This is occuring as currently chatwoot hardcodes a url endpoint that includes '/common' but for single tenancy access apps, this needs to be set to the project name.

We're glad to report, we've patched this ourselves and have this working, our devs unfamiliarity with your test suite has meant the PR has no tests currently, but we hope this makes it easy for someone to take it from here.

We have this working in https://github.com/chatwoot/chatwoot/pull/6728

3.  With endpoint fixed, Outlook emails setup correctly and can receive BUT issue sending.

While Microsoft said that SMTP can be used once Oath2.0 connectivity is setup (via registering your own Azure application), seems that this is not the case and SMTP remains broken for sending emails.

The issue here is that if not using a verified app, ALL SMTP functionality stops working and that equivilent functionality needs to be reimplemented using Micrsofts Graph API.

We have this working in https://github.com/chatwoot/chatwoot/pull/6728

We're looking for someone to add tests to the PR and to get it merged in.

<sub>[CW-1400](https://linear.app/chatwoot/issue/CW-1400/getting-microsoft-email-working-with-chatwoot-in-2023)</sub>

**Comment by pranavrajs** [comment] 2023-03-23 02:59
@evolve2k Thanks for the detailed note.

> ALL SMTP functionality stops working and that equivilent functionality needs to be reimplemented using Micrsofts Graph API.

Is it a consistent behaviour? We have customers using Chatwoot with Microsoft Email in production, haven't heard a complaint recently.

Anyway, happy to help with the implementation if required.

**Comment by evolve2k** [comment] 2023-03-23 05:28
WIthout this PR , it means that everyone to-date is using the /common endpoint, which in turn means they setup "multi-tenant access".

They each would have had to undertake organisational verification with Microsoft, which is a more involved process and requires providing legal documentation, accepting a bunch of additional terms and manual approvals on Microsofts end.

SIngle tenant access doesn't need verification but then relies on the graph api.

It's also possible that accounts setup before the deprecation hit in 2023 are still fine for the mean time.

**Comment by evolve2k** [comment] 2023-04-03 00:56
Checking in on this one.

**Comment by tejaswinichile** [comment] 2023-05-16 04:00
1. The specs which were passing not passing after rails 7 upgrade.
2. Mainly the issue is with action-mailer base delivery method.

**Comment by tejaswinichile** [comment] 2023-05-29 06:45
@sojan-official Can you check this, I am not able to deploy this branch. Initializer is giving issue that file not found.

**Comment by tejaswinichile** [comment] 2023-05-31 04:24
@sojan-official You can assign this back to me, I am stuck on the deployment issue for this one, I am not able to figure out why may be need a new eye to resolve it.

**Comment by grupale** [comment] 2023-06-08 12:31
Hi @sojan-official , @tejaswinichile any update about this issue? Thanks

**Comment by uro** [comment] 2023-09-20 20:41
Hey Folks, What's the status of this issue? Is it available for early tests anywhere?

**Comment by evolve2k** [comment] 2023-09-20 23:22
I just looked at #6878 and it was all merged 11 April 2023.

So this should all be in place and working now as far as I can tell.

Having a similar issue, I’d suggest to raise a new Issue.

**Closed** 2024-02-01 15:14 UTC
Labels: ✨ feature-request, investigation, linear, 2 points
