### ISSUE TITLE
cwctl install failure (ubuntu 20.0.4 and 22.0.4)

### ISSUE THREAD

**Issue by twhiting9275** [chatwoot/chatwoot#8479] opened 2023-12-03 05:57 UTC
### Describe the bug

Title says it all. CWCTL fails to install on Ubuntu, with two issues
1: key import for ruby fails (fix: get rid of the use keyserver comments in cwctl, and it works)
2: compilation failure

### To Reproduce

1. download cwctl
2. try to install
3. 

### Expected behavior

Expected behavior is that the system installs properly

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

### Operating system

Ubuntu 20.0.4 , Ubuntu 22.0.4

### Additional context

logs here
`
$ husky install
husky - Git hooks installed
Done in 0.74s.
I, [2023-12-03T05:49:13.614907 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/manifest-90aab26ade71e747f745b1227b433fd7d580a54f279ee2be6e1a67bb326bf03a.js
I, [2023-12-03T05:49:13.615244 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/manifest-90aab26ade71e747f745b1227b433fd7d580a54f279ee2be6e1a67bb326bf03a.js.gz
I, [2023-12-03T05:49:13.615850 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-c55458eda8f5016fa42c952490754581a9be3e72395a889843d6561bd5e1f8a9.css
I, [2023-12-03T05:49:13.616061 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-c55458eda8f5016fa42c952490754581a9be3e72395a889843d6561bd5e1f8a9.css.gz
I, [2023-12-03T05:49:13.616266 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-0ca1ebe5baf40d486024c2af43f59c99db8ee966ae8440eaa75b247d725f91f1.js
I, [2023-12-03T05:49:13.616504 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-0ca1ebe5baf40d486024c2af43f59c99db8ee966ae8440eaa75b247d725f91f1.js.gz
I, [2023-12-03T05:49:13.617027 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate-field-active_storage/application-491e0febefaa4b7923c60e77838dadb71e679fcc07232cd97198fb364d300152.css
I, [2023-12-03T05:49:13.617105 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate-field-active_storage/application-491e0febefaa4b7923c60e77838dadb71e679fcc07232cd97198fb364d300152.css.gz
I, [2023-12-03T05:49:13.617188 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-2e4c5a7faeb8c684ad4d6b3f713605212c572f00d77c11bd74dcc29291fb50b9.js
I, [2023-12-03T05:49:13.617247 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-2e4c5a7faeb8c684ad4d6b3f713605212c572f00d77c11bd74dcc29291fb50b9.js.gz
I, [2023-12-03T05:49:13.617328 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/secretField-72cf0cbaa1d0c6b6a1a79d79e61649722f0612e6334a0f18929b04c145e3c024.js
I, [2023-12-03T05:49:13.617389 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/secretField-72cf0cbaa1d0c6b6a1a79d79e61649722f0612e6334a0f18929b04c145e3c024.js.gz
I, [2023-12-03T05:49:13.617504 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-2e4c5a7faeb8c684ad4d6b3f713605212c572f00d77c11bd74dcc29291fb50b9.js
I, [2023-12-03T05:49:13.617565 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-2e4c5a7faeb8c684ad4d6b3f713605212c572f00d77c11bd74dcc29291fb50b9.js.gz
I, [2023-12-03T05:49:13.617642 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actiontext-28c61f5197c204db043317a8f8826a87ab31495b741f854d307ca36122deefce.js
I, [2023-12-03T05:49:13.617703 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actiontext-28c61f5197c204db043317a8f8826a87ab31495b741f854d307ca36122deefce.js.gz
I, [2023-12-03T05:49:13.617778 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/trix-1563ff9c10f74e143b3ded40a8458497eaf2f87a648a5cbbfebdb7dec3447a5e.js
I, [2023-12-03T05:49:13.617834 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/trix-1563ff9c10f74e143b3ded40a8458497eaf2f87a648a5cbbfebdb7dec3447a5e.js.gz
I, [2023-12-03T05:49:13.617913 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/trix-6fd35bb8fae1d6a795115763ca265369b9750f73a1c6283a0b0ef4b6c2d550c8.css
I, [2023-12-03T05:49:13.617974 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/trix-6fd35bb8fae1d6a795115763ca265369b9750f73a1c6283a0b0ef4b6c2d550c8.css.gz
I, [2023-12-03T05:49:13.618059 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-0ca1ebe5baf40d486024c2af43f59c99db8ee966ae8440eaa75b247d725f91f1.js
I, [2023-12-03T05:49:13.618114 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-0ca1ebe5baf40d486024c2af43f59c99db8ee966ae8440eaa75b247d725f91f1.js.gz
I, [2023-12-03T05:49:13.618197 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-c55458eda8f5016fa42c952490754581a9be3e72395a889843d6561bd5e1f8a9.css.gz
I, [2023-12-03T05:49:13.618278 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/belongs_to_search-25faa07e8d60e491e6f1218e5307b9e70ea1bb0a51e4a724a37e797cea81e9da.js
I, [2023-12-03T05:49:13.618333 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/belongs_to_search-25faa07e8d60e491e6f1218e5307b9e70ea1bb0a51e4a724a37e797cea81e9da.js.gz
I, [2023-12-03T05:49:13.618405 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage-3ab61e47dd4ee2d79db525ade1dca2ede0ea2b7371fe587e408ee37b7ade265d.js
I, [2023-12-03T05:49:13.618462 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage-3ab61e47dd4ee2d79db525ade1dca2ede0ea2b7371fe587e408ee37b7ade265d.js.gz
I, [2023-12-03T05:49:13.618533 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage.esm-01f58a45d77495cdfbdfcc872902a430426c4391634ec9c3da5f69fbf8418492.js
I, [2023-12-03T05:49:13.618588 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage.esm-01f58a45d77495cdfbdfcc872902a430426c4391634ec9c3da5f69fbf8418492.js.gz
I, [2023-12-03T05:49:13.618661 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable-5433453f9b6619a9de91aaab2d7fc7ff183e5260c0107cbc9a1aa0c838d9a74e.js
I, [2023-12-03T05:49:13.618717 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable-5433453f9b6619a9de91aaab2d7fc7ff183e5260c0107cbc9a1aa0c838d9a74e.js.gz
I, [2023-12-03T05:49:13.618789 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable.esm-e01089c3ec4fe7817fa9abcad06cab6bdc387f95f0ca6aab4bf7ba7537f70690.js
I, [2023-12-03T05:49:13.618843 #23607]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable.esm-e01089c3ec4fe7817fa9abcad06cab6bdc387f95f0ca6aab4bf7ba7537f70690.js.gz
Compiling...
Compilation failed:
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($num, $num * 0 + 1) or calc($num / ($num * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
17 â”‚   @return $num / ($num * 0 + 1);
   â”‚           ^^^^^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/util/_unit.scss 17:11             strip-unit()
    node_modules/foundation-sites/scss/util/_unit.scss 89:13             -zf-to-rem()
    node_modules/foundation-sites/scss/util/_unit.scss 47:13             rem-calc()
    node_modules/foundation-sites/scss/util/_unit.scss 61:13             -zf-bp-to-em()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 78:8        breakpoint()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 329:38      @import
    node_modules/foundation-sites/scss/util/_util.scss 12:9              @import
    app/javascript/dashboard/assets/scss/_foundation-settings.scss 44:9  @import
    app/javascript/dashboard/assets/scss/_woot.scss 18:9                 @import
    app/javascript/dashboard/assets/scss/app.scss 1:9                    root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(strip-unit($value), strip-unit($base)) or calc(strip-unit($value) / strip-unit($base))

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
89 â”‚     $value: strip-unit($value) / strip-unit($base) * 1rem;
   â”‚             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/util/_unit.scss 89:13             -zf-to-rem()
    node_modules/foundation-sites/scss/util/_unit.scss 47:13             rem-calc()
    node_modules/foundation-sites/scss/util/_unit.scss 61:13             -zf-bp-to-em()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 78:8        breakpoint()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 329:38      @import
    node_modules/foundation-sites/scss/util/_util.scss 12:9              @import
    app/javascript/dashboard/assets/scss/_foundation-settings.scss 44:9  @import
    app/javascript/dashboard/assets/scss/_woot.scss 18:9                 @import
    app/javascript/dashboard/assets/scss/app.scss 1:9                    root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($table-color-scale, 2) or calc($table-color-scale / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    â•·
548 â”‚ $table-head-background: smart-scale($table-background, $table-color-scale / 2);
    â”‚                                                        ^^^^^^^^^^^^^^^^^^^^^^
    â•µ
    app/javascript/dashboard/assets/scss/_foundation-settings.scss 548:56  @import
    app/javascript/dashboard/assets/scss/_woot.scss 18:9                   @import
    app/javascript/dashboard/assets/scss/app.scss 1:9                      root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($form-spacing, 2) or calc($form-spacing / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
55 â”‚ $input-padding: $form-spacing / 2 !default;
   â”‚                 ^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/forms/_text.scss 55:17  @import
    node_modules/foundation-sites/scss/forms/_forms.scss 13:9  @import
    node_modules/foundation-sites/scss/foundation.scss 28:9    @import
    app/javascript/dashboard/assets/scss/_woot.scss 23:9       @import
    app/javascript/dashboard/assets/scss/app.scss 1:9          root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($form-spacing, 2) or calc($form-spacing / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
39 â”‚   padding: ($form-spacing / 2 + rem-calc($input-border-width)) 0;
   â”‚             ^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/forms/_label.scss 39:13  form-label-middle()
    node_modules/foundation-sites/scss/forms/_label.scss 47:7   foundation-form-label()
    node_modules/foundation-sites/scss/forms/_forms.scss 28:3   foundation-forms()
    node_modules/foundation-sites/scss/foundation.scss 90:3     foundation-everything()
    app/javascript/dashboard/assets/scss/_woot.scss 25:1        @import
    app/javascript/dashboard/assets/scss/app.scss 1:9           root stylesheet

WARNING: 18 repetitive deprecation warnings omitted.

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($num, $num * 0 + 1) or calc($num / ($num * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
17 â”‚   @return $num / ($num * 0 + 1);
   â”‚           ^^^^^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/util/_unit.scss 17:11                        strip-unit()
    node_modules/foundation-sites/scss/util/_unit.scss 89:13                        -zf-to-rem()
    node_modules/foundation-sites/scss/util/_unit.scss 47:13                        rem-calc()
    node_modules/foundation-sites/scss/util/_unit.scss 61:13                        -zf-bp-to-em()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 78:8                   breakpoint()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 329:38                 @import
    node_modules/foundation-sites/scss/util/_util.scss 12:9                         @import
    app/javascript/dashboard/assets/scss/_foundation-settings.scss 44:9             @import
    app/javascript/dashboard/assets/scss/_woot.scss 18:9                            @import
    app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue 2:9  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(strip-unit($value), strip-unit($base)) or calc(strip-unit($value) / strip-unit($base))

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
89 â”‚     $value: strip-unit($value) / strip-unit($base) * 1rem;
   â”‚             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/util/_unit.scss 89:13                        -zf-to-rem()
    node_modules/foundation-sites/scss/util/_unit.scss 47:13                        rem-calc()
    node_modules/foundation-sites/scss/util/_unit.scss 61:13                        -zf-bp-to-em()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 78:8                   breakpoint()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 329:38                 @import
    node_modules/foundation-sites/scss/util/_util.scss 12:9                         @import
    app/javascript/dashboard/assets/scss/_foundation-settings.scss 44:9             @import
    app/javascript/dashboard/assets/scss/_woot.scss 18:9                            @import
    app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue 2:9  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($table-color-scale, 2) or calc($table-color-scale / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    â•·
548 â”‚ $table-head-background: smart-scale($table-background, $table-color-scale / 2);
    â”‚                                                        ^^^^^^^^^^^^^^^^^^^^^^
    â•µ
    app/javascript/dashboard/assets/scss/_foundation-settings.scss 548:56           @import
    app/javascript/dashboard/assets/scss/_woot.scss 18:9                            @import
    app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue 2:9  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($form-spacing, 2) or calc($form-spacing / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
55 â”‚ $input-padding: $form-spacing / 2 !default;
   â”‚                 ^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/forms/_text.scss 55:17                       @import
    node_modules/foundation-sites/scss/forms/_forms.scss 13:9                       @import
    node_modules/foundation-sites/scss/foundation.scss 28:9                         @import
    app/javascript/dashboard/assets/scss/_woot.scss 23:9                            @import
    app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue 2:9  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($form-spacing, 2) or calc($form-spacing / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
39 â”‚   padding: ($form-spacing / 2 + rem-calc($input-border-width)) 0;
   â”‚             ^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/forms/_label.scss 39:13                      form-label-middle()
    node_modules/foundation-sites/scss/forms/_label.scss 47:7                       foundation-form-label()
    node_modules/foundation-sites/scss/forms/_forms.scss 28:3                       foundation-forms()
    node_modules/foundation-sites/scss/foundation.scss 90:3                         foundation-everything()
    app/javascript/dashboard/assets/scss/_woot.scss 25:1                            @import
    app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue 2:9  root stylesheet

WARNING: 18 repetitive deprecation warnings omitted.

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($num, $num * 0 + 1) or calc($num / ($num * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
17 â”‚   @return $num / ($num * 0 + 1);
   â”‚           ^^^^^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/util/_unit.scss 17:11             strip-unit()
    node_modules/foundation-sites/scss/util/_unit.scss 89:13             -zf-to-rem()
    node_modules/foundation-sites/scss/util/_unit.scss 47:13             rem-calc()
    node_modules/foundation-sites/scss/util/_unit.scss 61:13             -zf-bp-to-em()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 78:8        breakpoint()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 329:38      @import
    node_modules/foundation-sites/scss/util/_util.scss 12:9              @import
    app/javascript/dashboard/assets/scss/_foundation-settings.scss 44:9  @import
    app/javascript/dashboard/assets/scss/_woot.scss 18:9                 @import
    app/javascript/dashboard/assets/scss/app.scss 1:9                    @import
    app/javascript/dashboard/App.vue 2:9                                 root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(strip-unit($value), strip-unit($base)) or calc(strip-unit($value) / strip-unit($base))

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
89 â”‚     $value: strip-unit($value) / strip-unit($base) * 1rem;
   â”‚             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/util/_unit.scss 89:13             -zf-to-rem()
    node_modules/foundation-sites/scss/util/_unit.scss 47:13             rem-calc()
    node_modules/foundation-sites/scss/util/_unit.scss 61:13             -zf-bp-to-em()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 78:8        breakpoint()
    node_modules/foundation-sites/scss/util/_breakpoint.scss 329:38      @import
    node_modules/foundation-sites/scss/util/_util.scss 12:9              @import
    app/javascript/dashboard/assets/scss/_foundation-settings.scss 44:9  @import
    app/javascript/dashboard/assets/scss/_woot.scss 18:9                 @import
    app/javascript/dashboard/assets/scss/app.scss 1:9                    @import
    app/javascript/dashboard/App.vue 2:9                                 root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($table-color-scale, 2) or calc($table-color-scale / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    â•·
548 â”‚ $table-head-background: smart-scale($table-background, $table-color-scale / 2);
    â”‚                                                        ^^^^^^^^^^^^^^^^^^^^^^
    â•µ
    app/javascript/dashboard/assets/scss/_foundation-settings.scss 548:56  @import
    app/javascript/dashboard/assets/scss/_woot.scss 18:9                   @import
    app/javascript/dashboard/assets/scss/app.scss 1:9                      @import
    app/javascript/dashboard/App.vue 2:9                                   root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($form-spacing, 2) or calc($form-spacing / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
55 â”‚ $input-padding: $form-spacing / 2 !default;
   â”‚                 ^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/forms/_text.scss 55:17  @import
    node_modules/foundation-sites/scss/forms/_forms.scss 13:9  @import
    node_modules/foundation-sites/scss/foundation.scss 28:9    @import
    app/javascript/dashboard/assets/scss/_woot.scss 23:9       @import
    app/javascript/dashboard/assets/scss/app.scss 1:9          @import
    app/javascript/dashboard/App.vue 2:9                       root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($form-spacing, 2) or calc($form-spacing / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   â•·
39 â”‚   padding: ($form-spacing / 2 + rem-calc($input-border-width)) 0;
   â”‚             ^^^^^^^^^^^^^^^^^
   â•µ
    node_modules/foundation-sites/scss/forms/_label.scss 39:13  form-label-middle()
    node_modules/foundation-sites/scss/forms/_label.scss 47:7   foundation-form-label()
    node_modules/foundation-sites/scss/forms/_forms.scss 28:3   foundation-forms()
    node_modules/foundation-sites/scss/foundation.scss 90:3     foundation-everything()
    app/javascript/dashboard/assets/scss/_woot.scss 25:1        @import
    app/javascript/dashboard/assets/scss/app.scss 1:9           @import
    app/javascript/dashboard/App.vue 2:9                        root stylesheet

WARNING: 18 repetitive deprecation warnings omitted.

`

**Comment by vishnu-narayanan** [comment] 2023-12-15 09:34
Compilation failure usually occurs due to insufficient memory. Could you share you machine spec? CPU and RAM?

**Comment by Paul181516** [comment] 2024-01-23 21:49
Same here i tried to use a swap file but didnt work.

**Comment by vishnu-narayanan** [comment] 2024-01-24 06:53
@Paul181516 Could you share your machine specs? The recommendation is to use 8GB or more of RAM. If you are pressed for memory, I recommend trying the docker based installation.

**Comment by matheusschreiber** [comment] 2024-02-07 00:10
I had the same problem... Solved by doing a docker installation:

[https://www.chatwoot.com/docs/self-hosted/deployment/docker/](https://www.chatwoot.com/docs/self-hosted/deployment/docker/)

**Comment by vishnu-narayanan** [comment] 2024-02-07 04:45
I'm closing this because the issue is due to the underprovisioned machine spec.

**Closed by vishnu-narayanan** 2024-02-07 04:45 UTC
Labels: self-hosted, 🐧 self-hosted/linux
