### ISSUE TITLE
ERROR WHEN INSTALLING CHATWOOT

### ISSUE THREAD

**Issue by Lohuama** [chatwoot/chatwoot#8948] opened 2024-02-15 14:42 UTC
### Describe the bug

INSTALLATION IS NOT COMPLETE - CONTABO UBUNTU SERVER 20.04

### To Reproduce

➥ 1/9 Installing dependencies. This takes a while.
File '/usr/share/keyrings/redis-archive-keyring.gpg' exists. Overwrite? (y/N) y
File '/etc/apt/keyrings/nodesource.gpg' exists. Overwrite? (y/N) y
➥ 2/9 Installing databases.
➥ 3/9 Installing webserver.
➥ 4/9 Setting up Ruby
➥ 5/9 Setting up the database.
➥ 6/9 Installing Chatwoot. This takes a long while.
➥ 7/9 Running database migrations.

Some error has occured. Check '/var/log/chatwoot-setup.log' for details.

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

LINUX

### Docker (if applicable)

Docker version 25.0.3, build 4debf41

**Comment by Lohuama** [comment] 2024-02-15 14:46
> [ERRO PR-919 AO INSTALAR O CHATWOOT](https://linear.app/chatwoot/issue/PR-919/error-when-installing-chatwoot)

You don't have access to this workspace.
Please contact the workspace admin to gain access.

**Comment by jordan26** [comment] 2024-02-15 19:54
Provide the error(s) within the `/var/log/chatwoot-setup.log` file.

**Comment by Lohuama** [comment] 2024-02-16 12:02
> Forneça os erros no `/var/log/chatwoot-setup.log`arquivo.

This is one of the errors it is giving:

/usr/local/rvm/gems/ruby-3.2.2/gems/gmail_xoauth-0.4.2/lib/gmail_xoauth/imap_xoauth2_authenticator.rb:24: warning: Net::IMAP.add_authenticator is deprecated. Use Net::IMAP::SASL.add_authenticator instead.
rails aborted!
ActiveRecord::DatabaseConnectionError: There is an issue connecting to your database with your username/password, username: chatwoot. (ActiveRecord::DatabaseConnectionError)

Please check your database configuration to ensure the username/password are valid.
/home/chatroot/chatroot/lib/tasks/db_enhancements.rake:20:in `block (3 levels) in <main>'
/home/chatroot/chatroot/lib/tasks/db_enhancements.rake:18:in `each'
/home/chatroot/chatroot/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'

Caused by:
PG::ConnectionBad: FATAL: password authentication failed for user "chatroot" (PG::ConnectionBad)
/home/chatroot/chatroot/lib/tasks/db_enhancements.rake:20:in `block (3 levels) in <main>'
/home/chatroot/chatroot/lib/tasks/db_enhancements.rake:18:in `each'
/home/chatroot/chatroot/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'
Tasks: TOP => db:chatroot_prepare
(See full trace by running task with --trace)
root@vmi1403382:~#

**Comment by Lohuama** [comment] 2024-02-16 12:03
> Forneça os erros no `/var/log/chatwoot-setup.log`arquivo.

este é um dos erros que está dando:

/usr/local/rvm/gems/ruby-3.2.2/gems/gmail_xoauth-0.4.2/lib/gmail_xoauth/imap_xoauth2_authenticator.rb:24: warning: Net::IMAP.add_authenticator is deprecated.  Use Net::IMAP::SASL.add_authenticator instead.
rails aborted!
ActiveRecord::DatabaseConnectionError: There is an issue connecting to your database with your username/password, username: chatwoot. (ActiveRecord::DatabaseConnectionError)

Please check your database configuration to ensure the username/password are valid.
/home/chatwoot/chatwoot/lib/tasks/db_enhancements.rake:20:in `block (3 levels) in <main>'
/home/chatwoot/chatwoot/lib/tasks/db_enhancements.rake:18:in `each'
/home/chatwoot/chatwoot/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'

Caused by:
PG::ConnectionBad: FATAL:  password authentication failed for user "chatwoot" (PG::ConnectionBad)
/home/chatwoot/chatwoot/lib/tasks/db_enhancements.rake:20:in `block (3 levels) in <main>'
/home/chatwoot/chatwoot/lib/tasks/db_enhancements.rake:18:in `each'
/home/chatwoot/chatwoot/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'
Tasks: TOP => db:chatwoot_prepare
(See full trace by running task with --trace)
root@vmi1403382:~#

**Comment by sojan-official** [comment] 2024-02-16 12:15
@Lohuama please use `cwctl` to install chatwoot : https://www.chatwoot.com/docs/self-hosted/deployment/chatwoot-ctl/ 
the error clearly states that the username / password combination is wrong for your postgres database.  

Closing this since this is not a bug, but config value issue.

**Closed by sojan-official** 2024-02-16 12:15 UTC
Labels: Bug

**Comment by Lohuama** [comment] 2024-02-16 12:50
> @Lohuamause `cwctl`para instalar o chatwoot: https://www.chatwoot.com/docs/self-hosted/deployment/chatwoot-ctl/ o erro afirma claramente que a combinação de nome de usuário/senha está errada para seu banco de dados postgres.
> 
> Fechando isso, pois não é um bug, mas um problema de valor de configuração.

The documentation states that this tool is a self-installer for Linux, I'm using Ubuntu 20.04, will it work?

**Comment by sojan-official** [comment] 2024-02-16 16:06
@Lohuama  yes, we support 20.04
