### ISSUE TITLE
Images of Inboxes are not displayed (2.13.0)

### ISSUE THREAD

**Issue by luizeof** [chatwoot/chatwoot#6341] opened 2023-01-24 15:12 UTC
**Describe the bug**

Images of Inboxes are not displayed

![c92955d3-3cad-41ad-8ddb-abe2aba6acf4](https://user-images.githubusercontent.com/257004/214331011-5836c661-ad71-452a-8421-736766d13e50.png)

If you follow the image path (`https://mydomain/assets/images/dashboard/channels/website.png`), this appears:

![914e8a3b-8a70-48fc-8c85-074ea791443c](https://user-images.githubusercontent.com/257004/214331053-6515c62d-7d9b-4f79-b29c-7b2212b1c9d8.png)

**To Reproduce**

1. Go to `/app/accounts/1/settings/inboxes/new`

**Expected behavior**

Appear the images of the input boxes

**Screenshots**

![c92955d3-3cad-41ad-8ddb-abe2aba6acf4](https://user-images.githubusercontent.com/257004/214331472-77bb756a-75ed-4a59-82dc-38630c61f0a5.png)

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [x] Self-hosted
- - [ ] Linux VM
- - [x] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: [e.g. Linux, Windows, MacOS]
 - Browser [e.g. chrome, firefox, safari]

**Smartphone (please complete the following information)** (If applicable)
 - Device: [e.g. iPhone6, Pixel7]
 - Browser [e.g. stock browser, firefox, safari]

**Docker** (If applicable)

Please share the output of the following.
- `docker version`
- `docker info`
- `docker-compose version`

**Cloud Provider** (If applicable)
- [ ] AWS
- [ ] GCP
- [ ] Azure
- [x] DigitalOcean
- [ ] Others

**Additional context**

**Comment by neliocaa** [comment] 2023-01-25 02:16
I tested several clean deploys, and all in version 2.13.0 have this bug.
I did a deploy of the previous version (2.12.1), it worked perfectly.

**Comment by pranavrajs** [comment] 2023-01-25 03:48
@vishnu-narayanan Did we miss adding the files to the docker image?

**Comment by vishnu-narayanan** [comment] 2023-01-25 15:45
@neliocaa Thank you for reporting this. I was able to reproduce this.

**Comment by vishnu-narayanan** [comment] 2023-01-25 15:46
> @vishnu-narayanan Did we miss adding the files to the docker image? I mean the public folder.
@pranavrajs No, there has been no change to the `Dockerfile` compared to the December release.

**Comment by afonsolage** [comment] 2023-01-25 18:15
Maybe it is related to this commit?
https://github.com/chatwoot/chatwoot/commit/9bbadc2388dd1514ed84c3322bd1b40309465101

**Comment by afonsolage** [comment] 2023-01-26 10:31
I was able to fix it by removing the following line from `.dockerignore`:
https://github.com/chatwoot/chatwoot/blob/6bd4e8853bab00acea017d4e2bdad71bbb8f5d29/.dockerignore#L14

Since webpack won't pack those images anymore, we should let docker deploy it on image. This was my understanding tho.

**Comment by vishnu-narayanan** [comment] 2023-02-03 13:27
Fixed via https://github.com/chatwoot/chatwoot/commit/76731ae31a8fdbf88af602f9667177193f3d87a3

**Comment by vishnu-narayanan** [comment] 2023-02-03 13:27
Use `v2.13.1` tag

**Closed by vishnu-narayanan** 2023-02-03 13:27 UTC
Labels: bug, investigation

**Comment by neliocaa** [comment] 2023-02-03 13:35
thanks, just waiting now to update docker hub with new tag

**Comment by vishnu-narayanan** [comment] 2023-02-03 13:38
@neliocaa It should be available in the next 10-20 minutes. 😄 
https://hub.docker.com/repository/registry-1.docker.io/chatwoot/chatwoot/builds/5d0dba91-b390-4392-a94b-c49a0ede044d
