### ISSUE TITLE
Identify contact

### ISSUE THREAD

**Issue by hartois** [chatwoot/chatwoot#1664] opened 2021-01-17 20:44 UTC
How can I identify in API contact that created when chat started from web widget?
And vice verse - how can I set in web widget contact, that already created from API?

In my case I should use same contact for different channels: web widget and several channels over API.
I would like set own uniq ID (may be uuid) in one channel and use it in other channels.

As I understand it, this will allow me to link several conversations of one client through different channels.

**Comment by hartois** [comment] 2021-01-17 20:48
Documentation say that I can set user_id
![image](https://user-images.githubusercontent.com/11641656/104855504-41a2a080-591e-11eb-8472-de533b98d535.png)

But I does not see it in return of API methods "list", "get" and I cannot use it in "search contact".

**Comment by hartois** [comment] 2021-01-17 21:02
Separately, I would like to note that if the setting of a unique user ID in the widget is used, then we should NOT use cookies to identify him. Otherwise, two sessions that we open for in different browser tabs, which we want to identify as different contacts (by ID from the external system) will be used by the backend as one contact.

**Comment by hartois** [comment] 2021-01-18 09:15
I found another serious problem.
If you open two different sites in the same browser, with different widget tokens, the conversation is mixed: a message sent for example by an agent appears in both conversations. 
![image](https://user-images.githubusercontent.com/11641656/104894742-210e3100-5986-11eb-86fc-d41b4ed013c0.png)
![image](https://user-images.githubusercontent.com/11641656/104894759-24a1b800-5986-11eb-9bdb-0ae3b9334cb8.png)

Reloading the page restores the conversation:
![image](https://user-images.githubusercontent.com/11641656/104894806-34210100-5986-11eb-9eb6-3a72a9ac46e6.png)

This is due to the fact that the _chatwoot_session variable is stored in the cookie of the chat platform domain, not the site where the widget is installed.

It seems to me that session cookies should only be stored in the site's domain. When the widget is started, we need get the id of the conversation through api and store it in the widget variable, without storing it in cookies.
In this case, if the contact identifier is set, ignore the cookie variable and receive the session through api.

**Comment by pranavrajs** [comment] 2021-01-18 09:30
@hartois I didn't understand the issue you mentioned in the last comment. Could you please share a screencast?

**Comment by hartois** [comment] 2021-01-18 10:19
https://user-images.githubusercontent.com/11641656/104902356-b661f300-598f-11eb-828b-fe4aab7f3f2f.mp4

**Comment by hartois** [comment] 2021-01-18 10:36
Hm...
I'm clear cookies on both sites and cannot repeate bug

**Comment by hartois** [comment] 2021-01-18 10:46
Ok, I'm CAN repeate issue.
I check additionally, but it looks like this happens if you run a SetOser with the same identifier.

**Comment by hartois** [comment] 2021-01-18 10:51
@pranavrajs 
If we believe that the setUser is establishing a chat session, then when the widget starts, the same conversation should be loaded on different sites. If we believe that this is a user (contact) identifier, then the conversations should be different.

**Comment by sojan-official** [comment] 2021-01-18 11:20
@hartois  in release v1.12.0 we have introduced hmac user identity verification for web widgets . 

if you pass the contact identifier hash along with other parameters in `setUser` ,  the same conversation will be loaded on different browsers.  

ref: https://github.com/chatwoot/chatwoot/blob/develop/docs/channels/identity-validation.md 

let us know if this fixes the issue.

**Comment by hartois** [comment] 2021-01-18 11:30
@sojan-official
> if you pass the contact identifier hash along with other parameters in `setUser` , the same conversation will be loaded on different browsers.

This is very intresting feature, but in other case I need another: same contact, but different conversations.
In my case this is conversations with two different departments.

Ideally I can define the external unique id of the contact and the external unique id of the conversation.

**Comment by sojan-official** [comment] 2021-01-18 12:04
@hartois  chatwoot doesn't support conversations sharing across channels with email conversation continuity as the only exception.  ie, a conversation created for contact via API won't be shown in the web widget for that contact.  

But the agents in your chatwoot installation can see all the conversations associated with that contact in the dashboard 

---

> How can I identify in API contact that created when chat started from web widget?
> And vice verse - how can I set in web widget contact, that already created from API?
> 
> In my case I should use same contact for different channels: web widget and several channels over API.
> I would like set own uniq ID (may be uuid) in one channel and use it in other channels.
> 
> As I understand it, this will allow me to link several conversations of one client through different channels.

I am not sure I fully understand the use case. But let me know if the following is helpful. 

- You can have an internal identifier for your contacts or you could use email as the contact identifier 
- For creating conversations through the API, you can use our REST APIs.  you can look up for existing contacts via  
  
   https://www.chatwoot.com/developers/api#operation/contactSearch
   
 - Now to create a conversation for the same contact on your website ( use setUser along with HMAC ) 
 
 Notes: 
 
 - In the web widget the contact won't be able to see the conversations created in other API channels
 - if you have HMAC enabled the conversation will persist across sessions 
 - agents in your dashboard will be able to see all the conversation associated to the contact across channels 
 
 Let me know if you find any gaps

**Comment by hartois** [comment] 2021-01-18 12:19
I'm updating to v1.12.0

Example:
two sites: site1.com and site2.com each with its own inbox and own websiteToken
One customer who has userCode "id-0001" in my own system.

I start a conversation through a widgets on the sites.
I use setUser with HMAC.

I generate ```hash_hmac ('sha256', $this->**userCode**, $this->**websiteToken**)``` and put it in JS var **hmacCode**.

setUser (**hmacCode**, {name: **userCode**});

For clarity, I am setting the id as the username.

I expect this to be two separate conversations of the same contact. That is, as you described - the administrator will be able to see all of them in the "Previous conversations".

But in fact, I see two separate conversations of two different contacts.

**Comment by hartois** [comment] 2021-01-18 12:25
@sojan-official 
Please tell me if I am not using HMAC correctly or doing something wrong.

**Comment by hartois** [comment] 2021-01-18 12:39
Opening same page, with same hmac_hash passed to setUser in two different browsers

https://user-images.githubusercontent.com/11641656/104916619-612fdc80-59a3-11eb-93a8-5a822286b42c.mp4

**Comment by hartois** [comment] 2021-01-18 13:01
@sojan-official 

Another case:
different sites, **same user identifier**, different hmac_hash

First site:
```
hash_hmac('sha256', 'id-0001', 'nQapN*****zRj1oB3')

        window.$chatwoot.setUser(cwIdentHmac,{
            name: 'User 0001',
            email: 'user0001-from@site1.com'
        });
```
Second site:
```
hash_hmac('sha256', 'id-0001', 'zGFK*********Pdycd')

        window.$chatwoot.setUser(cwIdentHmac,{
            name: 'User 0001',
            email: 'user0001-from@site2.com'
        });
```
As administrator I see two different contacts (different emails):
![image](https://user-images.githubusercontent.com/11641656/104918789-53c82180-59a6-11eb-804c-bccf78962dbe.png)
![image](https://user-images.githubusercontent.com/11641656/104918803-588cd580-59a6-11eb-9246-110a90e2f518.png)

**Comment by sojan-official** [comment] 2021-01-18 16:51
@hartois  the hmac identifier is supposed to sent differently : https://github.com/chatwoot/chatwoot/blob/develop/docs/channels/website-sdk.md#identity-validation

```
window.$chatwoot.setUser(`identifier-hash`, {
  name: '', // Name of the user
  avatar_url: '', // Avatar URL
  email: '', // Email of the user
  identifier_hash: '' // Identifier Hash generated based on the webwidget hmac_token
})
```

**Comment by hartois** [comment] 2021-01-18 17:48
@pranavrajs where I must set **user_id** on which was generated hmac_hash?

**Comment by hartois** [comment] 2021-01-18 17:53
I'm also try next:

First site:
```
hash_hmac('sha256', 'id-0001', 'nQapN*****zRj1oB3')

        window.$chatwoot.setUser('id-0001',{
            name: 'User 0001',
            email: 'user0001-from@site1.com'
            identify_hash: cwIdentHmac
        });
```

Second site:
```
hash_hmac('sha256', 'id-0001', 'zGFK*********Pdycd')

        window.$chatwoot.setUser('id-0001',{
            name: 'User 0001',
            email: 'user0001-from@site2.com',
            identify_hash: cwIdentHmac
        });
```

Thi is correct?

**Comment by hartois** [comment] 2021-01-18 18:13
@sojan-official 
Every time I set same user_id (first arg of setUser) on different sites I got same result - mixed conversation as in screencast

**Comment by hartois** [comment] 2021-01-18 18:30
Screencast with configs from previous comment:
https://user-images.githubusercontent.com/11641656/104951795-445fcd00-59d4-11eb-806e-d55dc4752656.mp4

**Comment by pranavrajs** [comment] 2021-01-18 18:45
@hartois Thanks for the detailed explanation. Let us try to debug, we will get back to you soon.

**Comment by hartois** [comment] 2021-01-19 07:14
I noticed another problem related to this. If the cookie has already been set and we are use setUser with a new user_id, then it looks like not a new contact is being created, but the old one is updated.

Once again I am convinced that when using an external unique user ID, cookies are a bad idea.

**Comment by hartois** [comment] 2021-02-04 20:16
Can you reproduce bug with setUser from once browser?

**Comment by pranavrajs** [comment] 2021-02-08 09:59
@hartois Yes, we could. It will be fixed soon.

**Comment by azyzio** [comment] 2021-11-04 09:26
Hi @pranavrajs ,

I was in the middle of describing the findings I had about this issue and found this thread. I am happy to help you here, as I believe there is a high risk of data breaches caused by this behaviour.

My description of the problem:

If two identifiable contacts (created with the `$chatwoot.setUser` method with uniq identifier numbers) work from the same browser, they will me merged by chatwoot and will later see each other's conversations - even when using different computers. 

This issue is related to the fact that `$chatwoot.setUser` is using the `update` method in `Api::V1::Widget::ContactsController`. This endpoint defines `@contact` based on the token created from `cookies[:cw_conversation]`. It later uses `ContactIdentifyAction`, which actually not only identifies the contact, but also merges it with contact found using the specific `identifier`. This means that when two different contacts use the same browser, they will be merged - the first will be stored in cw_conversation cookie, and the second will be provided in `$chatwoot.setUser`.

I think the severity of this issue is pretty high.

**To Reproduce**

1. Create an empty website and enable chatwoot web-widget.
2. Run the following in the browser console: `window.$chatwoot.setUser('id_1', { email: 'id_1@test.com' })`
3. Write something in the chat
4. Run the following in the browser console: `window.$chatwoot.setUser('id_2', { email: 'id_2@test.com' })`
5. Write something in the chat

In the chatwoot dashboard, both conversations will be related to the same contact and it will have the second email. 

**Expected behavior**

It's not really obvious what should be the expected behaviour, but it feels like the `$chatwoot.setUser` should remove the conversation history if there is a mismatch between the current contact and the contact owning the previous conversation.

The contacts should get merged.

I'm wondering where is the best place to change and I believe that identifier value of the contact should never change. It two contacts have different identifiers, no merge should be happening. A possible place to start could be to add a condition by modifying contact_identify_action.rb#33 to be:
return if params[:identifier].blank? || params[:identifier] != @existing_identified_contact.identifier

Please let me know how I can be of help here :)

**Environment**

I have checked it applies both when  Enforce User Identity Validation is enabled and disabled.

**Comment by pranavrajs** [comment] 2021-11-08 07:17
@azyzio The contacts should be merged. Even if somebody calls the `setUser` method, they would not be able to retrieve the previous messages/conversations from another browser. The messages are retrieved based on contact_inbox which is essentially the sessions for a user. 

Here the problem is only with the real-time message behavior. The issue here is that the user has 2 browser sessions one with conversation and another one without conversation. The real-time messages creep into the browser session without conversation. I guess the fix here is to ignore all real-time messages if there is no active conversation on the widget.

**Comment by azyzio** [comment] 2021-11-08 08:51
Hi @pranavrajs ,

Thank a lot for the response.

We dug a little deeper in the meantime and we have adjusted our internal system to just remove the cw_conversation (and user) cookies on logout from our system. It is safer, but there might still be an issue when sessions have different expiries (the logout can happen while cw_conversation stays) and users are loosing their conversation history on logout (not a big deal really).

I'm not sure why the contacts should be merged when they have different identifiers. I must be missing something :) Let's imagine the situation:
- We have a user that is logged into some Saas system. Chatwoot is initialized and we provide identifier "Joe", "joe@gmail.com" as email and Joe's photo as his avatar using setUser. The sessions cookie (cw_conversation) is associated with Joe.
- Joe logs out to let his friend Jane use the same system from her own account. As she logs in, she can still see Joe's conversation as it's downloaded based on the sessions cookie (not a huge problem).
- setUser sets the identifier "Jane", "jane@gmail.com" as the email and her avatar. On the backend, Chatwoot merges Joe and Jane into one contact.
- Saas support agent logs in to find some old conversation with Joe. But Joe is not a contact in Chatwoot anymore. Only Jane exists and all previous Joe's conversation are assigned to her. The agent doesn't know that and therefore can't find the coversation.

I know it's really tricky to serve the "unlogged" and "identified" accounts in the same way. I was thinking that we could maybe add an additional Chatwoot initializer into the SDK that would initialize with Contact info already. Something like runIdentifiedSDK that takes user params as the input. This would ignore the previous session and set a new one if the contacts between session and the initializer didn't match. Would it make sense?

Best,
Adam

**Comment by pranavrajs** [comment] 2021-11-08 10:10
@azyzio I guess you missed implementing the `window.$chatwoot.reset()`. 

https://www.chatwoot.com/docs/product/channels/live-chat/sdk/setup#refresh-the-session-use-this-while-you-logout-the-user-from-your-app

You have to reset the session when the user logs out or the session is invalidated. Your use case would be covered with the reset method.

However, the following one is a bug, setUser should have identified that is already a session with identified contact, if so reset the session and create a new conversation.

> setUser sets the identifier "Jane", "jane@gmail.com" as the email and her avatar. On the backend, Chatwoot merges Joe and Jane into one contact.

**Comment by hartois** [comment] 2021-11-17 14:32
We have a system in which a user opens a website using a unique link. By the identifier in this link, we determine the user on the backend, we find him in the database. The user does not perform any login / logout operations.
And we cannot reset the session when the user logs out.
The process of identifying a user by ID and HMAC should occur when the chat starts, regardless of whether there is something in the cookie or not. If we set a new user ID, the session should be automatically reset and the history should be loaded using the new ID.

**Closed** 2021-11-22 18:06 UTC
Labels: bug

**Comment by azyzio** [comment] 2021-11-29 16:02
Thanks a lot for prioritizing this!

**Comment by soyket** [comment] 2022-02-24 14:39
Hi,

Though this is old there might be someone who is trying to solve this but is still stuck. 
First of all, make sure the identification function is within the below function

`window.addEventListener('chatwoot:ready', function () {
  window.$chatwoot.setUser('youruseridfromsite', {
  email: '<email-address-of-the-user@your-domain.com>',
  name: '<name-of-the-user>',
  identifier_hash: 'identifier_hash', 
});

});
`
The identifier_has generation for example is - 

`$identifier_hash = hash_hmac('sha256', 'youruseridfromsite', 'the_key_from_chatwoot_for_inbox');`

Make sure the youruseridfromsite in both js in PHP has_hmac function is the same otherwise it will not work. 
Now you can simply add prefix for site x and site y in the youruseridfromsite to make it uniq so each time users should have different profiles created for different sites.
