### ISSUE TITLE
Select which WhatsApp templates Chatwoot can use

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#5903] opened 2022-11-18 20:12 UTC
**Is your enhancement request related to a problem? Please describe.**

Today chatwoot syncs all whatsapp templates approved by facebook.

But many templates are examples of facebook, others are registered for integration of other tools and the like.

**Describe the solution you'd like**

I would like that in the inbox configuration, u as account administrator, I could select which templates will be used in chatwoot and which my agents will not have access to.

![image](https://user-images.githubusercontent.com/99494469/202793389-11c59da0-6a6e-4459-ac82-893d72eb046d.png)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered.

**Additional context**

Sorry... but my crocki is in portugues, but i belive you can understand.

![image](https://user-images.githubusercontent.com/99494469/202793389-11c59da0-6a6e-4459-ac82-893d72eb046d.png)

**Comment by pranavrajs** [comment] 2022-11-21 19:56
@glauberssoutodossantos Thanks, This is a good suggestion. It might need a couple of changes to get this done. We will estimate the changes and take it accordingly.

**Comment by vagner-dias** [comment] 2023-02-04 14:33
+1

**Comment by indexbrasil** [comment] 2023-03-01 17:17
Obrigado pela contribuição. Sofro com esse problema!

**Comment by rgon** [comment] 2023-05-05 16:11
Seems like a duplicate of #5246

**Comment by sojan-official** [comment] 2023-10-10 23:20
closing in favour of https://github.com/chatwoot/chatwoot/issues/5246

**Closed by sojan-official** 2023-10-10 23:20 UTC
