### ISSUE TITLE
Let the CSML-Bot respond immediately on Widget Open

### ISSUE THREAD

**Issue by valentinwinkelmann** [chatwoot/chatwoot#6397] opened 2023-02-05 11:21 UTC
When I open a conversation in a live chat I have to write something first to make the CSML bot react. This is extremely problematic and frustrating for the users, because the users tend to formulate long questions, because they want to ask their question directly. that means they write their complex question, make an effort to formulate it, send it and THEN the bot comes with a banality that of course does not address their question. is it somehow possible to let the bot start its dialog as soon as the chatwoot widget is opened or the "Start Conversation" button is pressed? otherwise the bot would only cause frustration instead of being helpful, but if it starts its execution immediately it would be useful, because it would prevent users from wasting effort formulating their question before they have actually been forwarded to a human agent.

**Comment by iammattmartin** [comment] 2023-02-06 23:35
Think this has already been covered before and is due to the way the chatwoot system works. More a duplicate of an existing issue than a new one..

**Comment by valentinwinkelmann** [comment] 2023-02-07 05:17
> Think this has already been covered before and is due to the way the chatwoot system works. More a duplicate of an existing issue than a new one..

Right, I wasn't sure if I addressed it back then on GitHub, but here is my original question #2993 from 2021. Unfortunately it still doesn't seem to be solved and so any chatbot within Chatwoot is unfortunately still rather frustrating than fulfilling a purpose, although right now with the integration of CSML the whole thing could be so powerful and extremely powerful. I think for most this is a committee criterion, because the bot must meet with high acceptance by the user, but he can hardly do that if every user must first find frustrated "_oh no I wrote everything for nothing_".

If there is no obvious solution to enable this, please add a "Trigger Start on Open" checkbox under the "Bot Configuration" tab.

**Comment by vishnu-narayanan** [comment] 2023-02-28 08:49
Duplicate of #2993.  Closing this for now.

**Closed by vishnu-narayanan** 2023-02-28 08:49 UTC
Labels: feature-request
