### ISSUE TITLE
Bug : automation rules not ahowing after we add it and save it

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#4520] opened 2022-04-20 19:37 UTC
Bug : automation rules not ahowing after we add it and save it

We ad the automation rule and save it and it's working but after we go to automation page : its showing no automation rules was found

**Comment by pranavrajs** [comment] 2022-04-21 06:41
Closing as the issue is resolved.

**Closed by pranavrajs** 2022-04-21 06:41 UTC
