### ISSUE TITLE
Assign the conversation to agent who opens the conversation

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3766] opened 2022-01-14 07:38 UTC
> If a ticket was with a bot, but then an agent responds, and "opens" the conversation, it gets assigned to any agent. In this case, it should go to the Agent who is marking the conversation as "Open"

- [ ] **Case 1:** Any conversation which is in Snoozed/Resolved/Pending status

If an agent opens a conversation that was resolved/snoozed/is pending, assign the conversation automatically to the agent who opened it.

- [x] **Case 2:** Any conversation created using a new message option in contacts

When a new message is created by an agent from the contacts screen, the conversation should be assigned to the same agent who created it.

**Comment by pranavrajs** [comment] 2022-01-24 19:43
@sojan-official Can you please evaluate the effort required for this?

@tejaswinichile Can we achieve the first case by a minimal change in automation?

**Comment by muhsin-k** [comment] 2022-02-07 07:58
The second case is the duplicate of #2912

**Closed** 2022-02-08 11:09 UTC
Labels: enhancement
