### ISSUE TITLE
Chatbot shake

### ISSUE THREAD

**Issue by tabrza** [chatwoot/chatwoot#762] opened 2020-04-24 09:31 UTC
**Describe the bug**
When mousing over the chatbot it shakes. The issue appears I believe due to the overflow: hidden being appended to the body..  
Appears to hide the scroll bar resulting in this issue

**To Reproduce**
Scroll on edge of chatbot when window open

**Comment by KasunAssetDidital** [comment] 2020-04-24 09:45
hey @tabrza how do i run u = User.find_by(email: 'my@email.com') on docker CLI could you tel me

**Comment by tabrza** [comment] 2020-04-24 10:12
@KasunAssetDidital - i've been working on this with heroku. for that, in your command line pls do the following

heroku run rails c -a "app name"
u = User.find_by(email: 'a@b.com')

**Comment by KasunAssetDidital** [comment] 2020-04-24 10:17
I run this command,but nothing changed
` docker-compose run rails -it **MyappName** bin/rails c -a 'u = User.find_by(email: 'my@email.com')'`

Thank you

**Comment by tabrza** [comment] 2020-04-24 10:59
> **Describe the bug**
> When mousing over the chatbot it shakes. The issue appears I believe due to the overflow: hidden being appended to the body..
> Appears to hide the scroll bar resulting in this issue
> 
> **To Reproduce**
> Scroll on edge of chatbot when window open

solved the issue by appending overflow-y scroll to the html tag
```
<html lang="en" style="overflow-y: scroll !important;">
```

if there is a cleaner solution to this kindly pls do let me know

**Comment by pranavrajs** [comment] 2020-04-24 16:32
@tabrza Thanks for reporting this, I'm not sure whether there is a conflicting overflow with the parent website'd body. I'll do some test around it to see I can reproduce this.

**Comment by pranavrajs** [comment] 2020-05-05 08:14
Closing this as the issue is not reproducible.  @tabrza Please feel free to re-open this if you have demo where we can see the error.

**Closed by pranavrajs** 2020-05-05 08:14 UTC
Labels: Investigation
