### ISSUE TITLE
Broken css for message options

### ISSUE THREAD

**Issue by Jatin-MYST** [chatwoot/chatwoot#6510] opened 2023-02-23 03:31 UTC
I will keep it short. Clicking on the 3 dots show this.
![image](https://user-images.githubusercontent.com/72418976/220815348-9f0d9c69-f8aa-4cf1-b724-8e5f1d597ede.png)

Edit: v2.14.0

**Comment by pranavrajs** [comment] 2023-02-23 03:50
This is a duplicate of https://github.com/chatwoot/chatwoot/issues/6471. For a quick fix, please close the participant box in the right hand sidebar.

**Closed by pranavrajs** 2023-02-23 03:50 UTC
