### ISSUE TITLE
Improved contact display in agent Conversation view

### ISSUE THREAD

**Issue by mariusa** [chatwoot/chatwoot#5828] opened 2022-11-09 11:34 UTC
Hi and thanks for Chatwoot!

Would you please consider improving ontact display in agent Conversation view, as follows:

1. At top
![2022-11-09_13-21](https://user-images.githubusercontent.com/1283842/200817402-b08f3609-1884-445b-b6b6-7c323c6fec28.png)

Show "Our company" (inbox name) only if multiple inboxes. If just one, hide it.

2. on the Inbox name line: Show primary attributes, ONLY if set (id, email, phone)

3. Hide `id` if same as email

4. Clicking on name should open More details

5. More details (Right panel)

5.1. Hide avatar if not set (now uses 1 large line)

5.2.  Show primary attributes ONLY if set (now says "Not Available"). Most web apps don't set phone/address.

5.3. Hide `id` if same as email

I see Contact attributes panel remains open after being open once, this is great.

Thanks for such a useful project!

**Comment by muhsin-k** [comment] 2022-11-10 03:49
> Hi and thanks for Chatwoot!
> 
> Would you please consider improving ontact display in agent Conversation view, as follows:
> 
> 1. At top
>    ![2022-11-09_13-21](https://user-images.githubusercontent.com/1283842/200817402-b08f3609-1884-445b-b6b6-7c323c6fec28.png)
> 
> Show "Our company" (inbox name) only if multiple inboxes. If just one, hide it.
> 
This is a great suggestion.
> 2. on the Inbox name line: Show primary attributes, ONLY if set (id, email, phone)

This may break the line if email/phone/id has more characters.

> 3. Hide `id` if same as the email

Don't understand this part.

> 4. Clicking on name should open More details

We already have a "More button" to show more details.

> 5. More details (Right panel)
> 
> 5.1. Hide avatar if not set (now uses 1 large line)

+1

> 
> 5.2. Show primary attributes ONLY if set (now says "Not Available"). Most web apps don't set phone/address.
> 
> 5.3. Hide `id` if same as email

Don't understand this part as well.

> 
> I see Contact attributes panel remains open after being open once, this is great.

This is an intended behaviour.

> 
> Thanks for such a useful project!

**Comment by muhsin-k** [comment] 2022-11-10 03:51
@mariusa Thanks for the UX suggestions. Please add more details about the items that we didn't understand.

**Comment by mariusa** [comment] 2022-11-10 07:02
Thanks for considering!

We set user `id` to be the same as `email`. If they are the same, we'd prefer to hide the id from display, show only the email.

> We already have a "More button" to show more details.

Right. Was suggesting that clicking on the name (which is larger than the "More details" link) would do the same. But the name shouldn't be in blue/underlined though, keep the current display style.

**Comment by muhsin-k** [comment] 2022-11-11 06:53
@mariusa That Makes sense.

**Comment by muhsin-k** [comment] 2022-11-11 07:19
- https://github.com/chatwoot/chatwoot/issues/5843
-https://github.com/chatwoot/chatwoot/issues/5844

**Comment by sojan-official** [comment] 2024-02-01 13:19
Closing this since @absurdiya  is redesigning the view and these items will be addressed in the new design.

**Closed by sojan-official** 2024-02-01 13:19 UTC
Labels: need-more-info, 20%-project
