### ISSUE TITLE
iPad app - Landscape support

### ISSUE THREAD

**Issue by SwimGeek** [chatwoot/chatwoot#10175] opened 2024-09-27 14:56 UTC
### Describe the bug

Hi

When using the Chatwoot app for iPad - it does not seem to support Landscape orientation.

### To Reproduce

Install on iPad - run app - turn iPad in landscape mode.

### Expected behavior

Use app in Landscape mode

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Mobile

### Operating system

Debian

### Browser and version

iPad app

**Comment by pranavrajs** [comment] 2024-09-29 19:07
@SwimGeek This is not a bug, this is not supported at the moment. You can only use it in portrait mode. We will address this in the upcoming design update. Closing it here for now as there is no immediate actionable on the issue.

**Closed by pranavrajs** 2024-09-29 19:07 UTC
Labels: Bug
