### ISSUE TITLE
Can't login after updating to v2.17.0

### ISSUE THREAD

**Issue by Jatin-MYST** [chatwoot/chatwoot#7150] opened 2023-05-22 02:09 UTC
### Describe the bug

**I updated chatwoot using the command:**
`sudo cwctl -u` (its at v2.17.1 now but still the same error)

After successfully installing it broke due to the redis issue. **(Please put breaking changes in the release changelogs)**
Anyway, I fixed that and installed the `libvips` library and rebooted the entire VM. 

**But its still broken when I try to login it gives 422 Error:**

![image](https://github.com/chatwoot/chatwoot/assets/72418976/b6463a24-d1ae-4899-ba95-81b4bd0cd45b)
![image](https://github.com/chatwoot/chatwoot/assets/72418976/f0b28043-da02-4793-a73f-d862977d56b5)

Also over the weekend, chatwoot/storage directory filled up my entire VM disk space. Had to extend disk.
Its filled with what looks to be emails. Not sure if this is related to above.
![image](https://github.com/chatwoot/chatwoot/assets/72418976/ed4bf61f-dd73-4324-bd99-2b1581af33ad)

**Here are logs using `sudo cwctl --logs web`:**

May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: I, [2023-05-22T00:55:57.343489 #6957]  INFO -- : source=rack-timeout id=cb3f1e35-4208-43cb-8e4d-c89678de14ae timeout=15000ms state=ready      
                                                                                                                                                                                       
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: D, [2023-05-22T00:55:57.343645 #6957] DEBUG -- : source=rack-timeout id=cb3f1e35-4208-43cb-8e4d-c89678de14ae timeout=15000ms service=0ms state=active         
                                                                                                                                                                       
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: I, [2023-05-22T00:55:57.344147 #6957]  INFO -- : [cb3f1e35-4208-43cb-8e4d-c89678de14ae] Started POST "/auth/sign_in" for ###.###.###.## at 2023-05-22 00:55:57 +0000     
                                                                                                                                                            
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: I, [2023-05-22T00:55:57.347444 #6957]  INFO -- : [cb3f1e35-4208-43cb-8e4d-c89678de14ae] Processing by DeviseOverrides::SessionsController#create as HTML        
                                                                                                                                                                     
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: I, [2023-05-22T00:55:57.347787 #6957]  INFO -- : [cb3f1e35-4208-43cb-8e4d-c89678de14ae]   Parameters: {"email"=>"###Valid-Email###", "password"=>"[FILTERED]", "sso_auth_token"=>"[FILTERED]"}                
                                                                                                         
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: D, [2023-05-22T00:55:57.351570 #6957] DEBUG -- : [cb3f1e35-4208-43cb-8e4d-c89678de14ae]   User Load (1.1ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "###Valid-Email###"], ["LIMIT", 1]]           
                                                                              
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: D, [2023-05-22T00:55:57.358079 #6957] DEBUG -- : [cb3f1e35-4208-43cb-8e4d-c89678de14ae]   User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3  [["email", "###Valid-Email###"], ["provider", "email"], ["LIMIT", 1]]         
                             
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: D, [2023-05-22T00:55:57.591123 #6957] DEBUG -- : [cb3f1e35-4208-43cb-8e4d-c89678de14ae]   TRANSACTION (0.8ms)  BEGIN            
       
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: D, [2023-05-22T00:55:57.592705 #6957] DEBUG -- : [cb3f1e35-4208-43cb-8e4d-c89678de14ae]   SuperAdmin Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."type" = $1 AND "users"."id" = $2 LIMIT $3 FOR UPDATE  [["type", "SuperAdmin"], ["id", 3], ["LIMIT", 1]]         
                                                     
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: D, [2023-05-22T00:55:57.706309 #6957] DEBUG -- : [cb3f1e35-4208-43cb-8e4d-c89678de14ae]   ActiveStorage::Attachment Load (0.7ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 3], ["record_type", "User"], ["name", "avatar"], ["LIMIT", 1]]       
                                                                      
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: D, [2023-05-22T00:55:57.708257 #6957] DEBUG -- : [cb3f1e35-4208-43cb-8e4d-c89678de14ae]   TRANSACTION (0.5ms)  ROLLBACK           
     
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: I, [2023-05-22T00:55:57.710459 #6957]  INFO -- : [cb3f1e35-4208-43cb-8e4d-c89678de14ae] Completed 422 Unprocessable Entity in 363ms (Views: 0.2ms | ActiveRecord: 4.9ms | Allocations: 2723)                                                                                    
                                                     
May 22 00:55:57 ip-###-##-##-### chatwoot-web.1[6957]: I, [2023-05-22T00:55:57.710932 #6957]  INFO -- : source=rack-timeout id=cb3f1e35-4208-43cb-8e4d-c89678de14ae timeout=15000ms service=367ms state=completed 

### To Reproduce

updated from 2.16 to 2.17
updated to 2.17.1 as well. still no luck.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

**Comment by sojan-official** [comment] 2023-05-24 15:26
We recently limited the text fields to a maximum of 20000 characters. it seems like you have a message signature bigger than that, which isn't a normal case. Could you add details about the use case here? 

# you can fix the issue by  resetting the signature using rails console 
- https://www.chatwoot.com/docs/self-hosted/monitoring/super-admin-sidekiq#access-rails-console
- run following command
```
u = User.find_by(email: 'john@acme.inc')
u.message_signature = nil
u.save
```

**Comment by Jatin-MYST** [comment] 2023-05-25 00:34
ah.. I see.
I used pgadmin to have a look what was happening.
Culprit was the images I had in my message signature were in base64.
This easily pushed the signature to over the 20k limit.
I updated the signature in the record and now I can login.
Thank you so much for you reply.

**Comment by sojan-official** [comment] 2023-05-25 03:59
Closing this as the issue is resolved :)

**Closed by sojan-official** 2023-05-25 03:59 UTC
Labels: self-hosted
