### ISSUE TITLE
Optimise Widget

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#2658] opened 2021-07-18 22:19 UTC
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Using Google PageSpeed Insights/Lighthouse, there are some improvements which could be made to the widget. As this is loaded on every page, it is probably wise to ensure this is as lightweight as possible.

```
Reduce unused JavaScript

URL | Transfer Size | Potential Savings
-- | -- | --
…js/widget-ffa558b….js(domain.com) | 170.4 KiB | 80.7 KiB
…./node_modules/vue/dist/vue.common.prod.js | 25.3 KiB | 12.3 KiB
…./node_modules/marked/lib/marked.js | 12.2 KiB | 9.1 KiB
…./node_modules/vue-upload-component/dist/vue-upload-component.js | 6.6 KiB | 5.7 KiB
(unmapped) | 39.3 KiB | 4.3 KiB
…./node_modules/vue-i18n/dist/vue-i18n.esm.js | 7.3 KiB | 3.9 KiB
```

```
Avoid serving legacy JavaScript to modern browsers



…js/widget-ffa558b….js(domain.com) |   | 13.9 KiB
-- | -- | --
webpack:///./node_modules/core-js/modules/es.symbol.js:253:2 | Object.getOwnPropertyNames |  
webpack:///./node_modules/core-js/modules/es.array.filter.js:11:2 | Array.prototype.filter |  
webpack:///./node_modules/core-js/modules/es.object.keys.js:10:2 | Object.keys |  
webpack:///./node_modules/core-js/modules/es.object.get-own-property-descriptors.js:10:2 | Object.getOwnPropertyDescriptors |  
webpack:///./node_modules/core-js/modules/es.array.from.js:12:2 | Array.from |  
webpack:///./node_modules/core-js/modules/es.array.map.js:11:2 | Array.prototype.map |  
webpack:///./node_modules/core-js/modules/es.object.get-prototype-of.js:11:2 | Object.getPrototypeOf |  
webpack:///./node_modules/core-js/modules/es.reflect.construct.js:25:2 | Reflect.construct |  
webpack:///./node_modules/core-js/modules/es.array.includes.js:8:2 | Array.prototype.includes |  
<unmapped>:1:0 | @babel/plugin-transform-classes |  
webpack:///./node_modules/core-js/modules/es.array.find-index.js:14:2 | Array.prototype.findIndex |  
webpack:///./node_modules/core-js/modules/es.array.find.js:14:2 | Array.prototype.find |  
webpack:///./node_modules/core-js/modules/es.object.values.js:6:2 | Object.values |  
webpack:///./app/javascript/widget/api/agent.js:4:34 | @babel/plugin-transform-regenerator |  
webpack:///./node_modules/core-js/modules/es.function.name.js:1:0 | Function.prototype.name |  
…js/sdk.js(domain.com) |   | 12.5 KiB
webpack:///./node_modules/core-js/modules/es.symbol.js:253:2 | Object.getOwnPropertyNames |  
webpack:///./node_modules/core-js/modules/es.array.filter.js:11:2 | Array.prototype.filter |  
webpack:///./node_modules/core-js/modules/es.object.keys.js:10:2 | Object.keys |  
webpack:///./node_modules/core-js/modules/es.array.includes.js:8:2 | Array.prototype.includes |  
webpack:///./node_modules/core-js/modules/es.object.get-own-property-descriptors.js:10:2 | Object.getOwnPropertyDescriptors |  
```

```
Reduce unused CSS

URL | Transfer Size | Potential Savings
-- | -- | --
…css/widget-d7ab88a5.css(domain.com) | 16.8 KiB | 11.9 KiB
```

**Comment by pranavrajs** [comment] 2021-07-22 06:19
@iammattmartin Closing this as this is a duplicate of #2111

**Closed by pranavrajs** 2021-07-22 06:19 UTC
