### ISSUE TITLE
Can't edit whatsapp channel settings

### ISSUE THREAD

**Issue by cruz4d3r** [chatwoot/chatwoot#7334] opened 2023-06-16 17:58 UTC
### Describe the bug

When I try to edit whatsapp settings it doesn't store it. It happened when upgrading from v2.16.0 to v2.18.0

### To Reproduce

1. Ubuntu 20.04 - Chatwoot v2.18.0
2. Go to Channels and try edit Whastapp Channel Settings

### Environment

Linux VM

### Cloud Provider

GCP

### Platform

Browser

### Operating system

Ubuntu 20.04

### Browser and version

Chrome Versión 114.0.5735.111 (Build oficial) (64 bits)

**Comment by sojan-official** [comment] 2023-06-19 08:27
@cruz4d3r  could you check your browser logs and see if there are any errors on save ?

**Comment by rolymaz** [comment] 2023-06-25 09:28
I had this issue and it was caused by the size of my out of office message. There is a limit of 255 characters (I think)

**Comment by pranavrajs** [comment] 2023-10-01 15:50
The character limits are updated in the latest release. Closing this here for now. Please feel free to reopen if it is not the case.

**Closed by pranavrajs** 2023-10-01 15:50 UTC
Labels: waiting-for-reply
