### ISSUE TITLE
Messages with PDF files attached by agent cannot be seen by user.

### ISSUE THREAD

**Issue by migarol** [chatwoot/chatwoot#6424] opened 2023-02-09 00:37 UTC
Chatwoot Self-hosted v2.13.1 via Docker installation
Using Local Storage
When an agent send a pdf files, the text is blank:

![image](https://user-images.githubusercontent.com/411062/217684137-c85e1154-e104-4a13-b12b-c602b9b554a4.png)

File can be downloaded if you find the download link on the blank, but no one can see the the download link

If i select the text with the mouse, i can see the text is there, but its all white so.. seems a buggy message and users cannot understand there's a file to download or even a message there.

![image](https://user-images.githubusercontent.com/411062/217684674-546c815d-8acb-4acd-a3c3-d127ed54edf5.png)

**Comment by migarol** [comment] 2023-02-09 00:41
Not only on pdf files, seems all files attached have the same issue: 
![image](https://user-images.githubusercontent.com/411062/217684984-02857880-5ea3-40b6-a05b-704d7671f89b.png)

**Comment by muhsin-k** [comment] 2023-02-10 13:48
Confirmed the issue in the staging environment.

<img width="459" alt="CleanShot 2023-02-10 at 19 17 46@2x" src="https://user-images.githubusercontent.com/12408980/218107635-49594ce3-5301-4ff5-9fdd-1a6f5a509b87.png">

@migarol Thanks for reporting the issue.

**Comment by devrizwanali** [comment] 2023-02-10 18:59
The issue is in the Widget/FileBubble component.

**Comment by muhsin-k** [comment] 2023-02-28 19:09
@migarol Tested in localhost, and it is working fine. We are closing this issue, for now. Please feel free to reopen this if it is still an issue.
![CleanShot 2023-03-01 at 00 38 29](https://user-images.githubusercontent.com/12408980/221954611-7f251210-ab00-4789-92bd-69d3e3735af3.png)

**Closed by muhsin-k** 2023-02-28 19:09 UTC
Labels: frontend, severity: 4, UI/UX improvements
