### ISSUE TITLE
Whatsapp 360dialog Vue js broken

### ISSUE THREAD

**Issue by reckerswartz** [chatwoot/chatwoot#4895] opened 2022-06-20 12:49 UTC
**Describe the bug**
Whatsapp 360dialog not allowing messages to send

**To Reproduce**
Fresh installation on Heroku

**Screenshots**
![image](https://user-images.githubusercontent.com/16918568/174604830-74ec4065-d0d3-4841-8a95-b1eb47d093de.png)

**Browser logs**

TypeError: i.filter is not a function
    getWhatsAppTemplates inboxes.js:67
    whatsAppTemplateMessages TemplatesPicker.vue:70
    VueJS 3
    filteredTemplateMessages TemplatesPicker.vue:73
    VueJS 3
    RD TemplatesPicker.vue:1
    VueJS 39
[vue.common.prod.js:659:10](webpack:///node_modules/vue/dist/vue.common.prod.js)

**Server logs**

Share the server logs to debug the issue further

 - OS: Ubuntu 22.04
 - Browser Mozilla 101.0.1 (64-bit)

**Comment by drdaga** [comment] 2022-06-24 05:42
it can be due to api key problem 
its not getting templates to sync

**Comment by pranavrajs** [comment] 2022-07-05 10:01
Closing this as this issue cannot be reproduced. @reckerswartz Please feel free to reopen with logs that would help us debug this.

**Closed by pranavrajs** 2022-07-05 10:01 UTC
Labels: whatsapp
