### ISSUE TITLE
Command+Z (Undo) deletes entire message from compose window

### ISSUE THREAD

**Issue by dmasiero** [chatwoot/chatwoot#8812] opened 2024-01-29 18:52 UTC
### Describe the bug

When composing an email/message and Command+Z is used to undo typing, the entire message is deleted. There is no way to undo. (i.e. Command+Shift+Z)

### To Reproduce

1.) Start composing an email.
2.) After typing a few paragraphs, use Command+Z keyboard shortcut to undo.
3.) Entire message deletes!
4.) Frustration ensues.

### Expected behavior

Undo keyboard shortcut should undo most recent typing/changes. Not delete the entire message without anyway to recover/restore.

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

macOS 14.2.1

### Browser and version

Brave 1.61.120 / Chromium 120.0.6099.234

**Comment by pranavrajs** [comment] 2024-01-29 19:45
@dmasiero Thanks for the note. Do you see the behavior all the time or just when you write continuously before a break?

The behavior as far as I understand is that the editor would revert to the point where you stopped writing before. Let me know if this is not the case.

**Comment by dmasiero** [comment] 2024-01-29 20:41
Not 100% on exact steps to re-produce. Most of the time, the behavior is normal in that Command+Z will undo most recent typing and then Shift+Command+Z will redo.

When the bug occurs, ALL text is deleted and Shift+Command+Z will NOT restore any of the text. 

I will continue to monitor and advise of exact steps to re-produce when able to notate such. This does happen rather frequently though, so I'm sure it'll show itself again soon. 👍🏻

**Comment by pranavrajs** [comment] 2024-01-29 21:06
Understood! I think this must be some edge case that we have missed. Since we don't have any option to reproduce this, I'll close this here. Feel free to comment here to reopen once you have a screen recording or a step to reproduce the bug.

**Closed by pranavrajs** 2024-01-29 21:06 UTC
Labels: 🧄 feature/agent-ui, Bug
