### ISSUE TITLE
Integrate with botpress chatbot

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3308] opened 2021-10-29 23:37 UTC
BotPress ChatBot is open source chatbot support building advanced bot with flow builder
https://github.com/botpress/botpress

**Comment by iammattmartin** [comment] 2021-10-30 16:53
Duplicate of #2502

**Comment by sojan-official** [comment] 2021-10-31 12:26
closing in favor of #2502

**Closed by sojan-official** 2021-10-31 12:26 UTC

**Comment by sanjayws** [comment] 2021-12-02 17:12
I made a very simple yet workable Botpress integration with CW using the great guide from here https://github.com/chatwoot/rasa-agent-bot-demo. Do reach out, happy to share my very rudimentary php code.

**Comment by drdaga** [comment] 2022-03-09 16:16
> I made a very simple yet workable Botpress integration with CW using the great guide from here https://github.com/chatwoot/rasa-agent-bot-demo. Do reach out, happy to share my very rudimentary php code.

can u help i want to integrate chatwoot with botpress
