### ISSUE TITLE
"Delete message" doesn't work

### ISSUE THREAD

**Issue by thiagodebugs** [chatwoot/chatwoot#8560] opened 2023-12-14 23:40 UTC
### Describe the bug

The "[Delete Message](https://www.chatwoot.com/docs/user-guide/conversation-workflow/#delete-message)" feature does not work as expected.

### To Reproduce

1. Create an inbox (Telegram, WhatsApp, other...).
2. Start a chat.
3. Send a message and delete it.

### Expected behavior

The message is expected to be deleted in the configured inbox, but it is only deleted in Chatwoot.

### Environment

Other [please specify in the description]

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Windows 10

### Browser and version

Google Chrome | Version 120.0.6099.72 (Official Version) 64-bit

### Additional context

I'm using Chatwoot version 3.2.0, deployed from AWS Marketplace. I tested the “Delete message” feature on Telegram and WhatsApp.

Another thing that is important to inform is that when a message intended for my service channel is deleted by my client, this message remains present in the Chatwoot conversation.
The feature does not work as expected from both directions.

**Comment by viniciusdebruin** [comment] 2023-12-15 18:29
I'm having the same problem.
When a conversation is deleted on WhatsApp, it is not informed on Chatwoot that it has been deleted.
When we delete a message on chatwoot, it is only removed from chatwoot, not removed from whatsapp

**Comment by pranavrajs** [comment] 2023-12-15 18:44
This is expected. We can't delete messages on other platforms due to API limitations. For eg, You can unsend an email or you won't be able to delete the message via API in WhatsApp at the moment.

**Comment by pranavrajs** [comment] 2023-12-15 18:44
Closing this here as it is not a bug.

**Closed by pranavrajs** 2023-12-15 18:44 UTC
