### ISSUE TITLE
Messages not loading after migrating database

### ISSUE THREAD

**Issue by pedrofnts** [chatwoot/chatwoot#8619] opened 2023-12-28 02:17 UTC
### Describe the bug

I have a Chatwoot installation (installed via install.sh, with Nginx), and I created a new one using Traefik and Portainer (Docker). I backed up my database in the old installation, and tried to restore it in the current installation. I kept the environment variables unchanged (which now differ, because in the previous installation POSTGRES_HOST=localhost, POSTGRES_USERNAME=chatwoot, while now both are "postgres", plus the password differs). I ran the restore with the command pg_restore -U postgres -d chatwoot -c /backup.tar, and got a series of errors, such as:

```
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 345; 1259 17424 SEQUENCE conv_dpid_seq_2 chatwoot
pg_restore: error: could not execute query: ERROR: sequence "conv_dpid_seq_2" does not exist
Command was: DROP SEQUENCE public.conv_dpid_seq_2;
pg_restore: from TOC entry 346; 1259 17425 SEQUENCE camp_dpid_seq_2 chatwoot
pg_restore: error: could not execute query: ERROR: sequence "camp_dpid_seq_2" does not exist
Command was: DROP SEQUENCE public.camp_dpid_seq_2;
pg_restore: from TOC entry 428; 1255 17399 FUNCTION accounts_after_insert_row_tr() chatwoot
pg_restore: error: could not execute query: ERROR: role "chatwoot" does not exist
Command was: ALTER FUNCTION public.accounts_after_insert_row_tr() OWNER TO chatwoot;
```

I created the chatwoot role manually in the database, and was then able to complete the restore and access the chatwoot installation. Everything is there (contacts, labels, agents, and the message counter), but the messages don't load, and I can't send or receive them either, even though I've set the boxes (I use API channel).

What can I do?

### To Reproduce

Migrating from Chatwoot v3.3.0 (direct deploy) to Chatwoot 3.4.0 (docker), on Ubuntu 20 VPS.

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

None

### Operating system

Ubuntu 20.04

**Comment by pranavrajs** [comment] 2024-01-05 19:58
```
ERROR: role "chatwoot" does not exist
```

This seems like an issue with the pg_dump export. I believe you need to exclude the user roles when taking the pg_dump. Closing this here as the issue is not related to Chatwoot.

**Closed by pranavrajs** 2024-01-05 19:58 UTC

**Comment by pranavrajs** [comment] 2024-02-05 20:45
@pedrofnts You can migrate one installation to another by taking the Postgres dump.
