### ISSUE TITLE
Respond to email in plain text

### ISSUE THREAD

**Issue by gobeyondpty** [chatwoot/chatwoot#8438] opened 2023-11-30 13:50 UTC
### Is your feature or enhancement related to a problem? Please describe.

I created an email channel for Google Voice as it is possible to respond to texts by email. However, replies are sent as HTML and <p></p> surrounds all the replies.

![image](https://github.com/chatwoot/chatwoot/assets/152504625/c2ec3b3f-53be-4ab5-b1ce-4f7b750e1b97)

### Describe the solution you'd like

Add the ability to reply in plain text

**Comment by pranavrajs** [comment] 2023-12-01 03:03
@gobeyondpty Are you using an API channel? Can you please describe the issue in detail? There is not much information on where this issue happens and how we can reproduce it. Please add relevant screenshots & screencasts to help reproduce the behavior.

**Comment by sojan-official** [comment] 2024-02-01 11:15
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.

**Closed by sojan-official** 2024-02-01 11:15 UTC
Labels: need-more-info

**Comment by gobeyondpty** [comment] 2024-02-02 03:07
This is using the email channel. Google Voice allows you to respond to SMS messages by email reply. However, when responding using chatwoot it adds <p> tags around the reply. When replying from Gmail by email it does not add <p> tags. 

This basically is a way of getting free SMS in chatwoot.
