### ISSUE TITLE
"We are offline" message is misleading.

### ISSUE THREAD

**Issue by vahid-neuralinc** [chatwoot/chatwoot#1600] opened 2021-01-04 22:19 UTC
In website chat widget > welcome screen > status is shown online as long as agent has:

- The agent has admin panel open in browser 

- The agent has mobile app opened

As soon as the agent closes the browser window/tab or the mobile app, the status changes to offline i.e. "We are offline"

This is misleading for the website visitors since the agent might be available but it's just he has closed the app (web or mobile) and he can launch the app to respond to any support request as quick as he receives a push or email notification + Offline status on the website looks ugly as well since the reason is not really that support is not available, but rather the app (web or mobile) are closed.

**This should be fixed.**

There are multiple options we can look for:

- An option available to override "We are offline" message in admin panel. When this is overidden, agent avatars are always shown

- An option to specify the office hours and change the offline status base on the office hours

- Along with office hours, there should also be an option to select "always available"

**Comment by pranavrajs** [comment] 2021-01-05 15:35
@vahid-neuralinc This should be fixed by #1491

**Comment by pranavrajs** [comment] 2021-01-05 15:36
We will be displaying the online/offline status based on the business hours set by the inbox admin instead of the availability of the user.

**Comment by mariusa** [comment] 2021-03-21 12:39
If there are no business hours setup, would you please consider displaying the status automatically as the 1st message said?
In website chat widget > welcome screen > status is shown online as long as agent has:

* The agent has admin panel open in browser
* The agent has mobile app opened

I don't have a regular work schedule, but would like to show as online when I have the admin panel open in browser (at least 1 agent has the app/panel open).

**Comment by mariusa** [comment] 2021-03-21 12:41
Actually, after more testing, it seems to work like this, which is great. It took more time (minutes) for online to change to offline after I closed the tab, which is ok.
Would you confirm? Based on the issue history, I thought this was dropped completely and only business hours mattered.

**Comment by sojan-official** [comment] 2021-03-21 16:31
@mariusa when you don't have business hours set up. We display the online status based on whether you have agents logged into the system.  

at the moment, chatwoot takes around a minute to register an agent to be offline after they logged out.

I can confirm that behaviour. 

> Actually, after more testing, it seems to work like this, which is great. It took more time (minutes) for online to change to offline after I closed the tab, which is ok.
> Would you confirm? Based on the issue history, I thought this was dropped completely and only business hours mattered.

**Comment by mariusa** [comment] 2021-03-21 17:37
> when you don't have business hours set up. We display the online status based on whether you have agents logged into the system.

perfect! Thanks

**Comment by cortopy** [comment] 2022-03-14 10:17
I'm currently using [Zammad](https://zammad.org/) and considering chatwoot. Showing online availability is very important to us, and it feels to me like the way Zammad handles online statuses for agents is flawless.

If a conversation is assigned to an agent, and the agent doesn't reply within X number of minutes, the agent status is changed to offline automatically. This solves many issues with having a browser window active, mobile app open/close, etc. and it's a far more reliable method

This would work great with the chatwoot app, since it gives time to agents to reply after a notification is received on the phone, and if there's no answer the chat availability changes

**Comment by sojan-official** [comment] 2022-03-14 12:37
@cortopy  Thanks for the note I have logged #4170  for better visibility.  
closing this issue in favour of #4170

**Closed by sojan-official** 2022-03-14 12:37 UTC
