### ISSUE TITLE
/api/v1/accounts/1/conversations?status=open&assignee_type=unassigned&page=1 500 (Internal Server Error)

### ISSUE THREAD

**Issue by rodrigo-p-a** [chatwoot/chatwoot#6119] opened 2022-12-21 23:32 UTC
**Describe the bug**

Go to : http://192.168.0.4:3000/app/accounts/1/dashboard

get this error in console.log when click in all messages:

/api/v1/accounts/1/conversations?status=open&assignee_type=unassigned&page=1 500 (Internal Server Error)

When click in other filter get normal messages without error:
/api/v1/accounts/1/conversations?status=open&assignee_type=me&page=1

I think error occour when filter is assignee_type=unassigned

![image](https://user-images.githubusercontent.com/12823068/209022674-fb96870a-dbe5-4d55-bd24-56f66ce47731.png)
![image](https://user-images.githubusercontent.com/12823068/209022813-c35cd8e9-6163-4ccc-b054-3120e585b116.png)
![image](https://user-images.githubusercontent.com/12823068/209022842-04703845-5be9-4437-a99d-7ff77afd94e5.png)

**Environment**

self-hosted installation . 
Linux real machine Debian 10 buster 64 bits
Postgresql + Redis in other server. Database is ok

chatwoot app in other server 
same network

**Desktop (please complete the following information)** (If applicable)
 - OS: [e.g. Linux, Windows, MacOS]
 - Browser [e.g. chrome, firefox, safari] -> tested in chrome, firefox, edge same error 
Version: cwctl v2.2.0 alpha build

**Comment by rodrigo-p-a** [comment] 2022-12-22 17:02
If you need, i can provide access via ssh to server

**Comment by vishnu-narayanan** [comment] 2022-12-23 15:01
@rodrigo-p-a From the sidekiq logs you shared, Chatwoot fails to obtain the database's connectivity.

```
Could not obtain a connection pool
```

Could you check your database metrics? Were you having a lot of active connections at that point?

**Comment by rodrigo-p-a** [comment] 2022-12-23 16:44
Stranged, i use in small company, with only 3 agents connected.
Postgresql configured to accept up to 200 connections.
Server of database idle 50-70% most time

**Comment by vishnu-narayanan** [comment] 2022-12-27 07:24
@rodrigo-p-a Are you able to reproduce this, or do you get this frequently? Could you monitor the DB metrics when you are getting this error?

**Comment by rodrigo-p-a** [comment] 2022-12-27 17:36
Hi sorry by delay. Yes i check db and no get errors. If help to found problem, i can provide access via ssh to server then you check, or i can provide to you access to system, then you can investigate the problem. If you can access to investigate, please send me a email.

**Comment by rodrigo-p-a** [comment] 2023-01-06 12:13
Other developer help me, delete some messages and problema disapear

**Comment by sojan-official** [comment] 2023-01-06 12:16
@rodrigo-p-a it will be helpful to set up an APM platform in the future to identify the root cause of such errors. 
ref: https://www.chatwoot.com/docs/self-hosted/monitoring/apm-and-error-monitoring

**Comment by rodrigo-p-a** [comment] 2023-01-06 12:21
Tks, Ill setup APM

**Comment by vishnu-narayanan** [comment] 2023-01-09 06:51
@rodrigo-p-a Closing this issue for now. Please reopen if you face this again.

**Closed by vishnu-narayanan** 2023-01-09 06:51 UTC
Labels: investigation
