### ISSUE TITLE
Feat: See end user answer as they type.

### ISSUE THREAD

**Issue by Brokray** [chatwoot/chatwoot#1891] opened 2021-03-10 13:03 UTC
**Is your feature request related to a problem? Please describe.**
In another livechat it was possible to see what the end user was typing in real time. This would let our agents prepare their answer at the same time. 
They would gain a lot of time in answering.

**Describe the solution you'd like**
See a temporary answer in real-time next to the "isTyping" widget. 
Also have a documentation on how to implement it using an API channel.

**Comment by iammattmartin** [comment] 2021-03-11 03:40
Near duplicate of #1137.

Needs to be optional as may breach privacy regs in some countries.

**Closed** 2022-03-25 14:55 UTC
