### ISSUE TITLE
Dialogflow not work on API Channel

### ISSUE THREAD

**Issue by aldhielman** [chatwoot/chatwoot#4004] opened 2022-02-16 17:14 UTC
I have tested dialogflow to integrate with FB, IG, Widget Chat and telegram and all is running well (including Agent Handoff mechanism)
but when i try integrate my API Channel Inbox that use samae credential JSON file as for other Inbox (FB, IG etc) it looks doesn't work.

currently i use postman to create new message from client, message successfully shown on Chatwoot but no reply from Dialogflow bot

this my sidekiq log
![image](https://user-images.githubusercontent.com/16577318/154319180-f87193ff-9aa1-4a36-89ca-65e14007795c.png)

and this from my service log
![image](https://user-images.githubusercontent.com/16577318/154319303-40cd58dc-706b-4c6e-9eed-a1e3cd1d77d4.png)

any suggestion ?

**Comment by sojan-official** [comment] 2022-02-21 13:18
@aldhielman  We will take a look and get back with updates.

**Comment by giquieu** [comment] 2022-06-23 14:07
@sojan-official 
Hi, any news about this? Can I help investigate?

**Comment by sojan-official** [comment] 2022-06-23 20:36
@giquieu We haven't gotten a chance to look at this yet. It would be super helpful if you could take a look.

**Comment by giquieu** [comment] 2022-07-25 04:46
@sojan-official 
I did several tests and could not reproduce the situation reported.
I get correct result, from Dialogflow and API Hook.

IMHO, that is no longer occurring.

I configured the integration with Dialogflow, as suggested by the documentation.
https://www.chatwoot.com/docs/product/channels/live-chat/integrations/dialogflow
And following the steps for communication through the API:
https://www.chatwoot.com/docs/product/channels/api/send-messages

Some from the log:
`01:36:33 backend.1  | Started POST "/api/v1/accounts/1/conversations/15/messages" for 127.0.0.1 at 2022-07-25 01:36:33 -0300
01:36:33 backend.1  | Processing by Api::V1::Accounts::Conversations::MessagesController#create as JSON
01:36:33 backend.1  |   Parameters: {"content"=>"test incoming msg", "message_type"=>"incoming", "private"=>"[FILTERED]", "account_id"=>"1", "conversation_id"=>"15", "message"=>{"content"=>"test incoming msg", "message_type"=>"incoming", "private"=>"[FILTERED]"}}
01:36:34 backend.1  | Enqueued ActionCableBroadcastJob (Job ID: 9f0fed5d-5f91-4726-a9a1-6d9d62368087) to Sidekiq(default) with arguments: ["eWsTf6kXKh8VgcGMjAU2mVgB", "Xrug2qrkTrQvvdD4y3fKU6gu"], "message.created", {"id"=>402, "content"=>"test incoming msg", "account_id"=>1, "inbox_id"=>2, "conversation_id"=>15, "message_type"=>"incoming", "created_at"=>Mon, 25 Jul 2022 04:36:34.083728000 UTC +00:00, "updated_at"=>Mon, 25 Jul 2022 04:36:34.083728000 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>nil, "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>"Contact", "sender_id"=>71, "external_source_ids"=>{}, "additional_attributes"=>{}, :created_at=>1658723794, :message_type=>0, :conversation_id=>15, :conversation=>{:assignee_id=>nil}, :sender=>{:additional_attributes=>{}, :custom_attributes=>{}, :email=>nil, :id=>71, :identifier=>nil, :name=>nil, :phone_number=>nil, :thumbnail=>"", :type=>"contact"}, :account_id=>1, :performer=>{:id=>1, :name=>"John", :available_name=>"John", :avatar_url=>"https://www.gravatar.com/avatar/0d722ac7bc3b3c92c030d0da9690d981?d=404", :type=>"user", :availability_status=>"online", :thumbnail=>"https://www.gravatar.com/avatar/0d722ac7bc3b3c92c030d0da9690d981?d=404"}}
01:36:34 worker.1   | start
01:36:34 worker.1   | Performing ActionCableBroadcastJob (Job ID: 9f0fed5d-5f91-4726-a9a1-6d9d62368087) from Sidekiq(default) enqueued at 2022-07-25T04:36:34Z with arguments: ["eWsTf6kXKh8VgcGMjAU2mVgB", "Xrug2qrkTrQvvdD4y3fKU6gu"], "message.created", {"id"=>402, "content"=>"test incoming msg", :account_id=>1, "inbox_id"=>2, :conversation_id=>15, :message_type=>0, :created_at=>1658723794, "updated_at"=>Mon, 25 Jul 2022 04:36:34.083728000 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>nil, "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>"Contact", "sender_id"=>71, "external_source_ids"=>{}, "additional_attributes"=>{}, :conversation=>{:assignee_id=>nil}, :sender=>{:additional_attributes=>{}, :custom_attributes=>{}, :email=>nil, :id=>71, :identifier=>nil, :name=>nil, :phone_number=>nil, :thumbnail=>"", :type=>"contact"}, :performer=>{:id=>1, :name=>"John", :available_name=>"John", :avatar_url=>"https://www.gravatar.com/avatar/0d722ac7bc3b3c92c030d0da9690d981?d=404", :type=>"user", :availability_status=>"online", :thumbnail=>"https://www.gravatar.com/avatar/0d722ac7bc3b3c92c030d0da9690d981?d=404"}}
01:36:34 backend.1  | Enqueued EventDispatcherJob (Job ID: 87777266-c890-428b-afa1-edfb734751a1) to Sidekiq(events) with arguments: "message.created", Mon, 25 Jul 2022 04:36:34.179010000 UTC +00:00, {:message=>#<GlobalID:0x00007fd51567ee30 @uri=#<URI::GID gid://chatwoot/Message/402>>, :performed_by=>nil}
01:36:34 worker.1   | start
01:36:34 backend.1  | Enqueued SendReplyJob (Job ID: 7a6ebef3-fb58-4a13-bd7c-37d872ac7e71) to Sidekiq(high) with arguments: 402
01:36:34 worker.1   | start
01:36:34 worker.1   | Performed ActionCableBroadcastJob (Job ID: 9f0fed5d-5f91-4726-a9a1-6d9d62368087) from Sidekiq(default) in 20.7ms
01:36:34 worker.1   | done
01:36:34 worker.1   | Performing SendReplyJob (Job ID: 7a6ebef3-fb58-4a13-bd7c-37d872ac7e71) from Sidekiq(high) enqueued at 2022-07-25T04:36:34Z with arguments: 402
01:36:34 worker.1   | Performing EventDispatcherJob (Job ID: 87777266-c890-428b-afa1-edfb734751a1) from Sidekiq(events) enqueued at 2022-07-25T04:36:34Z with arguments: "message.created", Mon, 25 Jul 2022 04:36:34.179010000 UTC +00:00, {:message=>#<GlobalID:0x00007fa6d8b79e78 @uri=#<URI::GID gid://chatwoot/Message/402>>, :performed_by=>nil}
01:36:34 worker.1   | Performed SendReplyJob (Job ID: 7a6ebef3-fb58-4a13-bd7c-37d872ac7e71) from Sidekiq(high) in 49.09ms
01:36:34 worker.1   | done
01:36:34 worker.1   | start
01:36:34 worker.1   | Enqueued HookJob (Job ID: 164140c9-0d94-4f33-8ddd-73722784eaf8) to Sidekiq(integrations) with arguments: #<GlobalID:0x00007fa6d843d1f0 @uri=#<URI::GID gid://chatwoot/Integrations::Hook/2>>, "message.created", {:message=>#<GlobalID:0x00007fa6d843c598 @uri=#<URI::GID gid://chatwoot/Message/402>>}
01:36:34 worker.1   | Performing HookJob (Job ID: 164140c9-0d94-4f33-8ddd-73722784eaf8) from Sidekiq(integrations) enqueued at 2022-07-25T04:36:34Z with arguments: #<GlobalID:0x00007fa6d8455098 @uri=#<URI::GID gid://chatwoot/Integrations::Hook/2>>, "message.created", {:message=>#<GlobalID:0x00007fa6d8454788 @uri=#<URI::GID gid://chatwoot/Message/402>>}
01:36:34 backend.1  | Enqueued ActionCableBroadcastJob (Job ID: 79e5fb6c-01a0-4301-be8b-17f641e5521d) to Sidekiq(default) with arguments: ["eWsTf6kXKh8VgcGMjAU2mVgB"], "contact.updated", {:additional_attributes=>{}, :custom_attributes=>{}, :email=>nil, :id=>71, :identifier=>nil, :name=>nil, :phone_number=>nil, :thumbnail=>"", :type=>"contact", :account_id=>1, :performer=>{:id=>1, :name=>"John", :available_name=>"John", :avatar_url=>"https://www.gravatar.com/avatar/0d722ac7bc3b3c92c030d0da9690d981?d=404", :type=>"user", :availability_status=>"online", :thumbnail=>"https://www.gravatar.com/avatar/0d722ac7bc3b3c92c030d0da9690d981?d=404"}}
01:36:34 worker.1   | start
01:36:34 backend.1  | Enqueued EventDispatcherJob (Job ID: 2903eb03-276d-4b2d-8e27-40288749b70f) to Sidekiq(events) with arguments: "contact.updated", Mon, 25 Jul 2022 04:36:34.336733000 UTC +00:00, {:contact=>#<GlobalID:0x00007fd4f79f79b8 @uri=#<URI::GID gid://chatwoot/Contact/71>>}
01:36:34 worker.1   | start
01:36:34 worker.1   | Performing ActionCableBroadcastJob (Job ID: 79e5fb6c-01a0-4301-be8b-17f641e5521d) from Sidekiq(default) enqueued at 2022-07-25T04:36:34Z with arguments: ["eWsTf6kXKh8VgcGMjAU2mVgB"], "contact.updated", {:additional_attributes=>{}, :custom_attributes=>{}, :email=>nil, :id=>71, :identifier=>nil, :name=>nil, :phone_number=>nil, :thumbnail=>"", :type=>"contact", :account_id=>1, :performer=>{:id=>1, :name=>"John", :available_name=>"John", :avatar_url=>"https://www.gravatar.com/avatar/0d722ac7bc3b3c92c030d0da9690d981?d=404", :type=>"user", :availability_status=>"online", :thumbnail=>"https://www.gravatar.com/avatar/0d722ac7bc3b3c92c030d0da9690d981?d=404"}}
01:36:34 backend.1  |   Rendered api/v1/accounts/conversations/messages/create.json.jbuilder (Duration: 2.3ms | Allocations: 512)
01:36:34 backend.1  | Completed 200 OK in 491ms (Views: 7.2ms | ActiveRecord: 229.5ms | Allocations: 34373)
01:36:34 backend.1  | 
01:36:34 backend.1  | 
01:36:34 worker.1   | Performed ActionCableBroadcastJob (Job ID: 79e5fb6c-01a0-4301-be8b-17f641e5521d) from Sidekiq(default) in 10.75ms
01:36:34 worker.1   | done
01:36:34 worker.1   | Performing EventDispatcherJob (Job ID: 2903eb03-276d-4b2d-8e27-40288749b70f) from Sidekiq(events) enqueued at 2022-07-25T04:36:34Z with arguments: "contact.updated", Mon, 25 Jul 2022 04:36:34.336733000 UTC +00:00, {:contact=>#<GlobalID:0x00007fa6bb8a8ae0 @uri=#<URI::GID gid://chatwoot/Contact/71>>}
01:36:34 worker.1   | Performed EventDispatcherJob (Job ID: 2903eb03-276d-4b2d-8e27-40288749b70f) from Sidekiq(events) in 0.21ms
01:36:34 worker.1   | done
01:36:34 worker.1   | Enqueued WebhookJob (Job ID: 59336fdc-23e5-4136-8f89-17eaade2cb92) to Sidekiq(webhooks) with arguments: "https://webhook.site/175af36b-dac2-4dbb-9f5b-4278906a223f", {:account=>{:id=>1, :name=>"Acme Inc"}, :additional_attributes=>{}, :content_attributes=>{}, :content_type=>"text", :content=>"test incoming msg", :conversation=>{:additional_attributes=>{}, :can_reply=>true, :channel=>"Channel::Api", :contact_inbox=>#<GlobalID:0x00007fa6d92d0b18 @uri=#<URI::GID gid://chatwoot/ContactInbox/55>>, :id=>15, :inbox_id=>2, :messages=>[{"id"=>402, "content"=>"test incoming msg", "account_id"=>1, "inbox_id"=>2, "conversation_id"=>15, "message_type"=>"incoming", "created_at"=>Mon, 25 Jul 2022 04:36:34.083728000 UTC +00:00, "updated_at"=>Mon, 25 Jul 2022 04:36:34.083728000 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>nil, "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>"Contact", "sender_id"=>71, "external_source_ids"=>{}, "additional_attributes"=>{}, :created_at=>1658723794, :message_type=>0, :conversation_id=>15, :conversation=>{:assignee_id=>nil}, :sender=>{:additional_attributes=>{}, :custom_attributes=>{}, :email=>nil, :id=>71, :identifier=>nil, :name=>nil, :phone_number=>nil, :thumbnail=>"", :type=>"contact"}}], :meta=>{:sender=>{:additional_attributes=>{}, :custom_attributes=>{}, :email=>nil, :id=>71, :identifier=>nil, :name=>nil, :phone_number=>nil, :thumbnail=>"", :type=>"contact"}, :assignee=>nil, :hmac_verified=>false}, :status=>"pending", :custom_attributes=>{}, :snoozed_until=>nil, :unread_count=>1, :agent_last_seen_at=>1658426315, :contact_last_seen_at=>0, :timestamp=>1658723794}, :created_at=>Mon, 25 Jul 2022 04:36:34.083728000 UTC +00:00, :id=>402, :inbox=>{:id=>2, :name=>"Channel - API"}, :message_type=>"incoming", :private=>false, :sender=>{:id=>71, :name=>nil, :avatar=>"", :type=>"contact", :account=>{:id=>1, :name=>"Acme Inc"}}, :source_id=>nil, :event=>"message_created"}
01:36:34 worker.1   | start
01:36:34 worker.1   | Performed EventDispatcherJob (Job ID: 87777266-c890-428b-afa1-edfb734751a1) from Sidekiq(events) in 244.1ms
01:36:34 worker.1   | done
01:36:34 worker.1   | Performing WebhookJob (Job ID: 59336fdc-23e5-4136-8f89-17eaade2cb92) from Sidekiq(webhooks) enqueued at 2022-07-25T04:36:34Z with arguments: "https://webhook.site/175af36b-dac2-4dbb-9f5b-4278906a223f", {:account=>{:id=>1, :name=>"Acme Inc"}, :additional_attributes=>{}, :content_attributes=>{}, :content_type=>"text", :content=>"test incoming msg", :conversation=>{:additional_attributes=>{}, :can_reply=>true, :channel=>"Channel::Api", :contact_inbox=>#<GlobalID:0x00007fa6d848fc70 @uri=#<URI::GID gid://chatwoot/ContactInbox/55>>, :id=>15, :inbox_id=>2, :messages=>[{"id"=>402, "content"=>"test incoming msg", "account_id"=>1, "inbox_id"=>2, :conversation_id=>15, :message_type=>0, :created_at=>1658723794, "updated_at"=>Mon, 25 Jul 2022 04:36:34.083728000 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>nil, "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>"Contact", "sender_id"=>71, "external_source_ids"=>{}, "additional_attributes"=>{}, :conversation=>{:assignee_id=>nil}, :sender=>{:additional_attributes=>{}, :custom_attributes=>{}, :email=>nil, :id=>71, :identifier=>nil, :name=>nil, :phone_number=>nil, :thumbnail=>"", :type=>"contact"}}], :meta=>{:sender=>{:additional_attributes=>{}, :custom_attributes=>{}, :email=>nil, :id=>71, :identifier=>nil, :name=>nil, :phone_number=>nil, :thumbnail=>"", :type=>"contact"}, :assignee=>nil, :hmac_verified=>false}, :status=>"pending", :custom_attributes=>{}, :snoozed_until=>nil, :unread_count=>1, :agent_last_seen_at=>1658426315, :contact_last_seen_at=>0, :timestamp=>1658723794}, :created_at=>Mon, 25 Jul 2022 04:36:34.083728000 UTC +00:00, :id=>402, :inbox=>{:id=>2, :name=>"Channel - API"}, :message_type=>"incoming", :private=>false, :sender=>{:id=>71, :name=>nil, :avatar=>"", :type=>"contact", :account=>{:id=>1, :name=>"Acme Inc"}}, :source_id=>nil, :event=>"message_created"}
01:36:35 worker.1   | Performed Request:  Code - 200
01:36:35 worker.1   | Performed WebhookJob (Job ID: 59336fdc-23e5-4136-8f89-17eaade2cb92) from Sidekiq(webhooks) in 920.54ms
01:36:35 worker.1   | done
01:36:36 worker.1   | start
01:36:36 worker.1   | Enqueued ActionCableBroadcastJob (Job ID: 57beeb7e-c798-478e-b672-3fd1c5e7b8c1) to Sidekiq(default) with arguments: ["eWsTf6kXKh8VgcGMjAU2mVgB", "Xrug2qrkTrQvvdD4y3fKU6gu"], "message.created", {"id"=>403, "content"=>"I missed what you said. What was that?", "account_id"=>1, "inbox_id"=>2, "conversation_id"=>15, "message_type"=>"outgoing", "created_at"=>Mon, 25 Jul 2022 04:36:36.572002000 UTC +00:00, "updated_at"=>Mon, 25 Jul 2022 04:36:36.572002000 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>nil, "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>nil, "sender_id"=>nil, "external_source_ids"=>{}, "additional_attributes"=>{}, :created_at=>1658723796, :message_type=>1, :conversation_id=>15, :conversation=>{:assignee_id=>nil}, :account_id=>1}
01:36:36 worker.1   | Performing ActionCableBroadcastJob (Job ID: 57beeb7e-c798-478e-b672-3fd1c5e7b8c1) from Sidekiq(default) enqueued at 2022-07-25T04:36:36Z with arguments: ["eWsTf6kXKh8VgcGMjAU2mVgB", "Xrug2qrkTrQvvdD4y3fKU6gu"], "message.created", {"id"=>403, "content"=>"I missed what you said. What was that?", :account_id=>1, "inbox_id"=>2, :conversation_id=>15, :message_type=>1, :created_at=>1658723796, "updated_at"=>Mon, 25 Jul 2022 04:36:36.572002000 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>nil, "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>nil, "sender_id"=>nil, "external_source_ids"=>{}, "additional_attributes"=>{}, :conversation=>{:assignee_id=>nil}}
01:36:36 worker.1   | start
01:36:36 worker.1   | Enqueued EventDispatcherJob (Job ID: 0e30e442-8831-4e9b-8c45-ae6ecbf10fa3) to Sidekiq(events) with arguments: "message.created", Mon, 25 Jul 2022 04:36:36.586006000 UTC +00:00, {:message=>#<GlobalID:0x00007fa6bba4bbb8 @uri=#<URI::GID gid://chatwoot/Message/403>>, :performed_by=>nil}
01:36:36 worker.1   | Performed ActionCableBroadcastJob (Job ID: 57beeb7e-c798-478e-b672-3fd1c5e7b8c1) from Sidekiq(default) in 6.29ms
01:36:36 worker.1   | done
01:36:36 worker.1   | start
01:36:36 worker.1   | Enqueued SendReplyJob (Job ID: 0c51e9fa-3121-4b11-9b9b-14e85262474c) to Sidekiq(high) with arguments: 403
01:36:36 worker.1   | Performing EventDispatcherJob (Job ID: 0e30e442-8831-4e9b-8c45-ae6ecbf10fa3) from Sidekiq(events) enqueued at 2022-07-25T04:36:36Z with arguments: "message.created", Mon, 25 Jul 2022 04:36:36.586006000 UTC +00:00, {:message=>#<GlobalID:0x00007fa6d9410b90 @uri=#<URI::GID gid://chatwoot/Message/403>>, :performed_by=>nil}
01:36:36 worker.1   | Performed HookJob (Job ID: 164140c9-0d94-4f33-8ddd-73722784eaf8) from Sidekiq(integrations) in 2263.41ms
01:36:36 worker.1   | done
01:36:36 worker.1   | Performing SendReplyJob (Job ID: 0c51e9fa-3121-4b11-9b9b-14e85262474c) from Sidekiq(high) enqueued at 2022-07-25T04:36:36Z with arguments: 403
01:36:36 worker.1   | Performed SendReplyJob (Job ID: 0c51e9fa-3121-4b11-9b9b-14e85262474c) from Sidekiq(high) in 12.32ms
01:36:36 worker.1   | done
01:36:36 worker.1   | Enqueued HookJob (Job ID: affe3ebc-7ede-4545-ace9-6c36c48eee0e) to Sidekiq(integrations) with arguments: #<GlobalID:0x00007fa6d94887f8 @uri=#<URI::GID gid://chatwoot/Integrations::Hook/2>>, "message.created", {:message=>#<GlobalID:0x00007fa6d9483618 @uri=#<URI::GID gid://chatwoot/Message/403>>}
01:36:36 worker.1   | start
01:36:36 worker.1   | Performing HookJob (Job ID: affe3ebc-7ede-4545-aace9-6c36c48eee0e) from Sidekiq(integrations) enqueued at 2022-07-25T04:36:36Z with arguments: #<GlobalID:0x00007fa6bbb08c18 @uri=#<URI::GID gid://chatwoot/Integrations::Hook/2>>, "message.created", {:message=>#<GlobalID:0x00007fa6bbb080d8 @uri=#<URI::GID gid://chatwoot/Message/403>>}
01:36:36 worker.1   | Performed HookJob (Job ID: affe3ebc-7ede-4545-ace9-6c36c48eee0e) from Sidekiq(integrations) in 0.2ms
01:36:36 worker.1   | done
01:36:36 worker.1   | start
01:36:36 worker.1   | Enqueued WebhookJob (Job ID: 6f59d183-5915-45dd-bb8f-c1e07455b24a) to Sidekiq(webhooks) with arguments: "https://webhook.site/175af36b-dac2-4dbb-9f5b-4278906a223f", {:account=>{:id=>1, :name=>"Acme Inc"}, :additional_attributes=>{}, :content_attributes=>{}, :content_type=>"text", :content=>"I missed what you said. What was that?", :conversation=>{:additional_attributes=>{}, :can_reply=>true, :channel=>"Channel::Api", :contact_inbox=>#<GlobalID:0x00007fa6d9541ed8 @uri=#<URI::GID gid://chatwoot/ContactInbox/55>>, :id=>15, :inbox_id=>2, :messages=>[{"id"=>403, "content"=>"I missed what you said. What was that?", "account_id"=>1, "inbox_id"=>2, "conversation_id"=>15, "message_type"=>"outgoing", "created_at"=>Mon, 25 Jul 2022 04:36:36.572002000 UTC +00:00, "updated_at"=>Mon, 25 Jul 2022 04:36:36.572002000 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>nil, "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>nil, "sender_id"=>nil, "external_source_ids"=>{}, "additional_attributes"=>{}, :created_at=>1658723796, :message_type=>1, :conversation_id=>15, :conversation=>{:assignee_id=>nil}}], :meta=>{:sender=>{:additional_attributes=>{}, :custom_attributes=>{}, :email=>nil, :id=>71, :identifier=>nil, :name=>nil, :phone_number=>nil, :thumbnail=>"", :type=>"contact"}, :assignee=>nil, :hmac_verified=>false}, :status=>"pending", :custom_attributes=>{}, :snoozed_until=>nil, :unread_count=>1, :agent_last_seen_at=>1658426315, :contact_last_seen_at=>0, :timestamp=>1658723796}, :created_at=>Mon, 25 Jul 2022 04:36:36.572002000 UTC +00:00, :id=>403, :inbox=>{:id=>2, :name=>"Channel - API"}, :message_type=>"outgoing", :private=>false, :sender=>nil, :source_id=>nil, :event=>"message_created"}
01:36:36 worker.1   | Performed EventDispatcherJob (Job ID: 0e30e442-8831-4e9b-8c45-ae6ecbf10fa3) from Sidekiq(events) in 73.32ms
01:36:36 worker.1   | done
01:36:36 worker.1   | Performing WebhookJob (Job ID: 6f59d183-5915-45dd-bb8f-c1e07455b24a) from Sidekiq(webhooks) enqueued at 2022-07-25T04:36:36Z with arguments: "https://webhook.site/175af36b-dac2-4dbb-9f5b-4278906a223f", {:account=>{:id=>1, :name=>"Acme Inc"}, :additional_attributes=>{}, :content_attributes=>{}, :content_type=>"text", :content=>"I missed what you said. What was that?", :conversation=>{:additional_attributes=>{}, :can_reply=>true, :channel=>"Channel::Api", :contact_inbox=>#<GlobalID:0x00007fa6d9558110 @uri=#<URI::GID gid://chatwoot/ContactInbox/55>>, :id=>15, :inbox_id=>2, :messages=>[{"id"=>403, "content"=>"I missed what you said. What was that?", "account_id"=>1, "inbox_id"=>2, :conversation_id=>15, :message_type=>1, :created_at=>1658723796, "updated_at"=>Mon, 25 Jul 2022 04:36:36.572002000 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>nil, "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>nil, "sender_id"=>nil, "external_source_ids"=>{}, "additional_attributes"=>{}, :conversation=>{:assignee_id=>nil}}], :meta=>{:sender=>{:additional_attributes=>{}, :custom_attributes=>{}, :email=>nil, :id=>71, :identifier=>nil, :name=>nil, :phone_number=>nil, :thumbnail=>"", :type=>"contact"}, :assignee=>nil, :hmac_verified=>false}, :status=>"pending", :custom_attributes=>{}, :snoozed_until=>nil, :unread_count=>1, :agent_last_seen_at=>1658426315, :contact_last_seen_at=>0, :timestamp=>1658723796}, :created_at=>Mon, 25 Jul 2022 04:36:36.572002000 UTC +00:00, :id=>403, :inbox=>{:id=>2, :name=>"Channel - API"}, :message_type=>"outgoing", :private=>false, :sender=>nil, :source_id=>nil, :event=>"message_created"}
01:36:36 backend.1  | Started GET "/monitoring/sidekiq/stats" for ::1 at 2022-07-25 01:36:36 -0300
01:36:36 backend.1  | Started GET "/cable" for ::1 at 2022-07-25 01:36:36 -0300
01:36:36 backend.1  | Started GET "/cable/" [WebSocket] for ::1 at 2022-07-25 01:36:36 -0300
01:36:36 backend.1  | Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
01:36:36 backend.1  | WebSocket error occurred: Broken pipe
01:36:36 backend.1  | Finished "/cable/" [WebSocket] for ::1 at 2022-07-25 01:36:36 -0300
01:36:37 worker.1   | Performed Request:  Code - 200
01:36:37 worker.1   | Performed WebhookJob (Job ID: 6f59d183-5915-45dd-bb8f-c1e07455b24a) from Sidekiq(webhooks) in 843.41ms
01:36:37 worker.1   | done`

**Comment by sojan-official** [comment] 2022-07-25 12:31
@giquieu  Thanks a lot for the findings. Let's close this out and reopen it in case it reoccurs. 

@aldhielman   note: Dialogflow intent detection max text length is 256 characters. In cases where its more, it wouldn't return a result. 

ref: https://cloud.google.com/dialogflow/quotas

**Closed by sojan-official** 2022-07-25 12:31 UTC
Labels: investigation
