### ISSUE TITLE
Provider config Invalid Credentials when updating WhatsApp API key

### ISSUE THREAD

**Issue by WEBudoGT** [chatwoot/chatwoot#9545] opened 2024-05-24 21:37 UTC
### Describe the bug

Using versions 3.8.0 and 3.9.0
When updating API key for WhatsApp channel, the following error is always shown:
"We couldn't update Inbox settings. Please try again later."

On the API, when making the request, it returns:

{
    "message": "Provider config Invalid Credentials",
    "attributes": [
        "provider_config"
    ]
}

### To Reproduce

Add a WhatsApp Inbox using the temporary API token and validate everything works fine.
After generating a new permanent token on Meta, copy the new token and try to use the "Update API Key" section of the channel.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

**Comment by ameztir** [comment] 2024-05-27 13:18
I have the same issue "Provider config Invalid Credentials".

**Comment by adnkh** [comment] 2024-06-04 18:04
We have the same issue here and here is the log:

`I, [2024-06-04T18:01:00.221736 #1]  INFO -- : [0605b525-6056-45b3-82bd-45553e307a33] Started POST "/api/v1/accounts/1/inboxes" for 162.158.38.73 at 2024-06-04 18:01:00 +0000
I, [2024-06-04T18:01:00.223961 #1]  INFO -- : [0605b525-6056-45b3-82bd-45553e307a33] Processing by Api::V1::Accounts::InboxesController#create as JSON
I, [2024-06-04T18:01:00.224026 #1]  INFO -- : [0605b525-6056-45b3-82bd-45553e307a33]   Parameters: {"name"=>"Whatsapp", "channel"=>{"type"=>"whatsapp", "phone_number"=>"**", "provider"=>"whatsapp_cloud", "provider_config"=>{"api_key"=>"[FILTERED]", "phone_number_id"=>"**", "business_account_id"=>"**"}}, "account_id"=>"1", "inbox"=>{"name"=>"Whatsapp"}}
I, [2024-06-04T18:01:00.410019 #1]  INFO -- : [0605b525-6056-45b3-82bd-45553e307a33] Handled error: #<ActiveRecord::RecordInvalid: Validation failed: Provider config Invalid Credentials>
I, [2024-06-04T18:01:00.410515 #1]  INFO -- : [0605b525-6056-45b3-82bd-45553e307a33] Completed 422 Unprocessable Entity in 186ms (Views: 0.2ms | ActiveRecord: 2.6ms | Allocations: 6798)
I, [2024-06-04T18:01:00.410951 #1]  INFO -- : source=rack-timeout id=0605b525-6056-45b3-82bd-45553e307a33 timeout=15000ms service=190ms state=completed
`

**Comment by adnkh** [comment] 2024-06-04 18:06
We have the same issue here and here is the log:

> I, [2024-06-04T18:01:00.221736 #1]  INFO -- : [0605b525-6056-45b3-82bd-45553e307a33] Started POST "/api/v1/accounts/1/inboxes" for 162.158.38.73 at 2024-06-04 18:01:00 +0000
I, [2024-06-04T18:01:00.223961 #1]  INFO -- : [0605b525-6056-45b3-82bd-45553e307a33] Processing by Api::V1::Accounts::InboxesController#create as JSON
I, [2024-06-04T18:01:00.224026 #1]  INFO -- : [0605b525-6056-45b3-82bd-45553e307a33]   Parameters: {"name"=>"Whatsapp", "channel"=>{"type"=>"whatsapp", "phone_number"=>"**", "provider"=>"whatsapp_cloud", "provider_config"=>{"api_key"=>"[FILTERED]", "phone_number_id"=>"**", "business_account_id"=>"**"}}, "account_id"=>"1", "inbox"=>{"name"=>"Whatsapp"}}
I, [2024-06-04T18:01:00.410019 #1]  INFO -- : [0605b525-6056-45b3-82bd-45553e307a33] Handled error: #<ActiveRecord::RecordInvalid: Validation failed: Provider config Invalid Credentials>
I, [2024-06-04T18:01:00.410515 #1]  INFO -- : [0605b525-6056-45b3-82bd-45553e307a33] Completed 422 Unprocessable Entity in 186ms (Views: 0.2ms | ActiveRecord: 2.6ms | Allocations: 6798)
I, [2024-06-04T18:01:00.410951 #1]  INFO -- : source=rack-timeout id=0605b525-6056-45b3-82bd-45553e307a33 timeout=15000ms service=190ms state=completed

**Comment by pranavrajs** [comment] 2024-07-08 04:48
Most of the issues we have see is with the access permission of the token. The service accounts should have admin permissions. Otherwise, the call will fail. Closing this here as this is not a bug.

**Closed by pranavrajs** 2024-07-08 04:48 UTC
Labels: Bug
