### ISSUE TITLE
Error 'time out reading data for server"

### ISSUE THREAD

**Issue by regueir0** [chatwoot/chatwoot#8390] opened 2023-11-20 15:52 UTC
### Describe the bug

This error ocorred after update CW 3.2 for CW 3.3.1  this update It was done in accordance with the documentation and as I always do in all previous updates .

### To Reproduce

# Login as Chatwoot user
sudo -i -u chatwoot

# Navigate to the Chatwoot directory
cd chatwoot

# Pull the latest version of the master branch
git checkout master && git pull

# Ensure the ruby version is upto date
rvm install "ruby-3.2.2"
rvm use 3.2.2 --default

# Update dependencies
bundle
yarn

# Recompile the assets
rake assets:precompile RAILS_ENV=production

# Migrate the database schema
RAILS_ENV=production bundle exec rake db:migrate

# Switch back to root user
exit

# Copy the updated targets
cp /home/chatwoot/chatwoot/deployment/chatwoot-web.1.service /etc/systemd/system/chatwoot-web.1.service
cp /home/chatwoot/chatwoot/deployment/chatwoot-worker.1.service /etc/systemd/system/chatwoot-worker.1.service
cp /home/chatwoot/chatwoot/deployment/chatwoot.target /etc/systemd/system/chatwoot.target

# Reload systemd files
systemctl daemon-reload

# Restart the chatwoot server
systemctl restart chatwoot.target

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20.04

**Comment by regueir0** [comment] 2023-11-20 15:52
![Uploading 586c46.jpeg…]()

**Comment by MPteste** [comment] 2023-11-23 11:36
I'm facing the same problem after updating to 3.3.1

**Comment by IcaruuS22** [comment] 2023-11-23 14:03
Também estou com este problema, alguém conseguiu resolver?

**Comment by pranavrajs** [comment] 2023-12-01 03:22
@regueir0 Can you please describe the issue in detail? There is not much information on where this issue happens and how we can reproduce it. Please add relevant screenshots & screencasts to help reproduce the behavior.

**Comment by mateusimao** [comment] 2023-12-01 19:39
Também estou com o mesmo problema após a 3.3.1, versões anteriores estava funcionando sem problemas.
Alguns envios, tanto como mensagem ou arquivos, apresenta o seguinte:
![erro_chatwoot3 3 1](https://github.com/chatwoot/chatwoot/assets/36195848/129ae5b5-2835-4e35-bc1e-013295460a98)

 Mas a mensagem e ou arquivo é entregue normalmente, só é exibido a mensagem de falha no Chatwoot.

**Comment by grupale** [comment] 2023-12-05 12:28
Hi @pranavrajs and @sojan-official I hope your fine, Im having the same issue after upgrading. Here are some screenshots refering the case.
![image](https://github.com/chatwoot/chatwoot/assets/10934794/edfae35b-2c03-4165-8bb5-ee395ac2317c)

I notice in Sidekiq that the Queue times increased a lot and the 10 Threads are constantly at 100%. In my case the virtual machine that host Chatwoot has many more resources but Rails its not using it.

![image](https://github.com/chatwoot/chatwoot/assets/10934794/28087974-24f4-45dc-a597-2832c9c5753f)
![image](https://github.com/chatwoot/chatwoot/assets/10934794/5a0bba1c-6e0a-41ae-9dcf-c931556b81e2)

**Comment by xandecrn** [comment] 2023-12-05 14:16
the same here. 8gb myVPS

**Comment by grupale** [comment] 2023-12-05 16:58
@pranavrajs Should I increase the RAILS_MAX_THREADS and/or enable the SIDEKIQ_CONCURRENCY parameter in the .env file?

**Comment by vishnu-narayanan** [comment] 2023-12-07 12:51
@grupale Look like the webhook endpoint is timing out. Could you check this logs for that service.

```
http://192.168.10.22:21467/api/adjudicaciones/chatwoof
```

**Comment by grupale** [comment] 2023-12-07 13:08
Hi @vishnu-narayanan thanks for your answer. In my case the webhook endpoint is not loggin any error in particular. I'm using the same type of webhook integration in another Chatwoot server that is running 3.2 version and is not having this behaviour. 

Looking at Sidekiq its seems that every job is taking more time to be completed and queue increase over time. In the env file I increased the SIDEKIQ CONCURRENCY to 30 but the total queue never reach to 0.

![image](https://github.com/chatwoot/chatwoot/assets/10934794/d9b1406b-c449-44a6-982f-8dc74475aa9c)
![image](https://github.com/chatwoot/chatwoot/assets/10934794/d75b692f-80c7-4d9b-88a1-11bebaa19681)
![image](https://github.com/chatwoot/chatwoot/assets/10934794/20127316-b9fe-42a7-a383-ef6e38b44b16)

**Comment by josep112** [comment] 2024-01-19 19:36
Does anyone have a solution for this I have version 3.4 and I have the same problem, the impression I have is that if the return takes too long I get this error

**Comment by josep112** [comment] 2024-01-22 12:55
Doing better tests, I found that if a text or file takes more than 6 seconds to return a response, I receive this response. My question is: is there a way to change the webhook response time?

**Comment by stgcompany** [comment] 2024-01-25 20:22
![image](https://github.com/chatwoot/chatwoot/assets/143809393/b8560296-9e8a-4209-95ca-e3136dc46d2c)

I suppressed the error with this conditional, as the files are actually been sent.

**Comment by pranavrajs** [comment] 2024-02-07 02:06
@josep112 / everyone on the thread. This is not a bug with Chatwoot. We are sending webhook events to the specified URL.

During this request, we expect the URL to respond within 5 seconds. This timeout is considered reasonable when compared to the millisecond timeouts of most general products. Note that thread in Chatwoot is waiting for the URL to respond, blocked from doing other processing. Setting a higher limit could potentially cause the message queue to become congested, which would negatively impact the system's performance. 

@stgcompany If you are sending the message back to WhatsApp or using some other integration, I would suggest doing it in the background rather than directly using it within the request. This way you can send the response back to Chatwoot and process it in the background without affecting any services.

Closing this here as we would not change the timeouts

**Closed by pranavrajs** 2024-02-07 02:06 UTC
Labels: need-more-info

**Comment by pranavrajs** [comment] 2024-02-07 02:30
Added the note here as well, just in case any is looking into this in future. https://www.chatwoot.com/docs/product/features/webhooks#return-a-success2xx-response-quickly
