### ISSUE TITLE
Error when using environment variables to change Chatwoot branding

### ISSUE THREAD

**Issue by mane06** [chatwoot/chatwoot#7222] opened 2023-05-31 03:10 UTC
### Describe the bug

In the Chatwoot 2.16 version I used this configuration in the super admin panel to change the chatwoot branding but in version 2.17.1 when I wanted to do this same configuration I got this error:

`May 31 03:02:53 localhost chatwoot-web.1[32429]: [84eb4019-e018-46b3-88a7-b3c9d7a435e5] ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_installation_configs_on_name"`

![Error example](https://github.com/chatwoot/chatwoot/assets/50756282/8c24409a-633c-4886-8b4a-805d0c3d47c8)

- INSTALLATION_NAME
- BRAND_NAME
- LOGO
- LOGO_THUMBNAIL

How should the branding be changed in this new version? or where is my mistake?

My Chjatwoot instance is working fine in every way except for this configuration that I have not been able to do, it is hosted on a VPS with Ubuntu 20

### To Reproduce

1. Enter the super admin panel
2. Select the Installation Configs menu
3. Select the Installation Configs menu and add New installation config
4. Add one of the environment variables and its corresponding value

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

**Comment by pranavrajs** [comment] 2023-06-01 22:55
@mane06 The installation config shown on the super admin dashboard are only configured, rest everything else is not configurable. Please reset to the previous so that the configuration would start working. Closing this here as the issue is not a bug. Please feel free to open a discussion if you couldn't get it back to working state.

**Closed by pranavrajs** 2023-06-01 22:55 UTC
