### ISSUE TITLE
Email error <accounts@chatwoot.com>: Sender address rejected: not owned by user example@email.com

### ISSUE THREAD

**Issue by btcmaine** [chatwoot/chatwoot#3304] opened 2021-10-28 18:13 UTC
Email fails to send (new signups, transcripts)

docker deployment on debian
set SMTP to any custom server that verifies sender

**Expected behavior**
MAILER_SENDER_EMAIL=example@email.com
should set the sender address

**Server logs**
2021-10-28T18:10:13.424Z pid=1 tid=28sd class=ActionMailer::MailDeliveryJob jid=b5f6ad87b3483b2ef12478a8 elapsed=0.681 INFO: fail
2021-10-28T18:10:13.426Z pid=1 tid=28sd WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"mailers","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::MailDeliveryJob","args":[{"job_class":"ActionMailer::MailDeliveryJob","job_id":"22e8fb73-1f66-4e3f-bf71-a60fb143491c","provider_job_id":null,"queue_name":"mailers","priority":null,"arguments":["ConversationReplyMailer","conversation_transcript","deliver_now",{"params":{"account":{"_aj_globalid":"gid://chatwoot/Account/2"},"_aj_symbol_keys":["account"]},"args":[{"_aj_globalid":"gid://chatwoot/Conversation/6"},"user@example.com"],"_aj_ruby2_keywords":["params","args"]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2021-10-28T18:10:12Z"}],"jid":"b5f6ad87b3483b2ef12478a8","created_at":1635444612.7421389,"enqueued_at":1635444612.7427614},"jobstr":"{\"retry\":true,\"queue\":\"mailers\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::MailDeliveryJob\",\"args\":[{\"job_class\":\"ActionMailer::MailDeliveryJob\",\"job_id\":\"22e8fb73-1f66-4e3f-bf71-a60fb143491c\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"ConversationReplyMailer\",\"conversation_transcript\",\"deliver_now\",{\"params\":{\"account\":{\"_aj_globalid\":\"gid://chatwoot/Account/2\"},\"_aj_symbol_keys\":[\"account\"]},\"args\":[{\"_aj_globalid\":\"gid://chatwoot/Conversation/6\"},\"user@example.com\"],\"_aj_ruby2_keywords\":[\"params\",\"args\"]}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2021-10-28T18:10:12Z\"}],\"jid\":\"b5f6ad87b3483b2ef12478a8\",\"created_at\":1635444612.7421389,\"enqueued_at\":1635444612.7427614}"}
2021-10-28T18:10:13.429Z pid=1 tid=28sd WARN: Net::SMTPFatalError: 553 5.7.1 <accounts@chatwoot.com>: Sender address rejected: not owned by user noreply@example.com

**Environment**

Docker on Debian 11

**Comment by btcmaine** [comment] 2021-10-29 18:24
update: 
MAILER_SENDER_EMAIL=noreply@example.com
changes the value for sign up confirmation and password reset emails but not transcript emails.

**Comment by jean-philippeansel** [comment] 2021-11-14 15:40
@pranavrajs 
I can confirm the issue.
All SMTP variables, including MAILER_SENDER_EMAIL, are perfectly set, but any emails sent from the Email Inbox as well as chat transcript are sent from accounts@chatwoot.com.
So all outgoing emails end up to SPAM.

**Comment by sagararyal** [comment] 2022-01-03 14:03
This issue is solved in v2.0

It now uses: `Agent Name | Inbox Name < MAILER_SENDER_EMAIL >`

**Comment by Soundmagic** [comment] 2022-01-09 10:09
I update to 2.0.2, but issue still persists. What do you mean by solved in v2.0 ?!?

**Comment by hostup** [comment] 2022-01-14 05:00
same issue here also updated but it shows from accounts@chatwoot.com

**Comment by pranavrajs** [comment] 2022-01-14 05:38
@sojan-official @vishnu-narayanan Looks like there is something wrong with the configuration. 

@hostup / @Soundmagic is it fresh installation, did you have any changes in your self-hosted installation?

**Comment by hostup** [comment] 2022-01-14 05:40
> @sojan-official @vishnu-narayanan Looks like there is something wrong with the configuration.
> 
> @hostup / @Soundmagic is it fresh installation, did you have any changes in your self-hosted installation?

It's not fresh, but it's only 16 days old. I have changed the env file to this:

MAILER_SENDER_EMAIL="Chatwoot <chatt@hostup.se>"

**Comment by Soundmagic** [comment] 2022-01-14 07:36
same for me, not fresh but only 7 days old. I change the env file to this 
MAILER_SENDER_EMAIL="shop <shop@gastroshark.de>"

I enabled also the continously function.
I setup an Email channel with smtp only (not imap), incoming mails catch by postfix and forwarded via action mailer.
I restart the chatwoot service after every change.

Agent repley in email channel "shop" are send out still with "accounts@chatwood.com".

Can it be that .env is cached any how?
I did a review on "conversation_replay_mailer.rb" as well, and I have the feeling the logic in "def replay_mail" (line 99) and "def from_email_with_name" (line 108) is not correct. The boolean "shoul_use_conversation_email_address" logic seems wrong for me. Maybe here is an issue.

**Comment by pranavrajs** [comment] 2022-01-14 18:08
@vishnu-narayanan This sounds like the issue with env. 

@Soundmagic @btcmaine @hostup Would you be able to upgrade the version to 2.1.0 and see if the issue is still there? We had a fix for similar issue via https://github.com/chatwoot/chatwoot/pull/3702

**Comment by vishnu-narayanan** [comment] 2022-01-14 18:31
@Soundmagic @btcmaine @hostup Could you also confirm your Chatwoot setup? Deployment method? Chatwoot version ?

**Comment by vishnu-narayanan** [comment] 2022-01-14 18:38
@pranavrajs `MAILER_SENDER_EMAIL` variable was not modified to use the GlobalConfigService. It is still fetching directly from env variable.

```ENV.fetch('MAILER_SENDER_EMAIL', 'Chatwoot <accounts@chatwoot.com>')```


ref: https://github.com/chatwoot/chatwoot/search?q=MAILER_SENDER_EMAIL&type=

**Comment by Soundmagic** [comment] 2022-01-14 20:20
> @vishnu-narayanan This sounds like the issue with env.
> 
> @Soundmagic @btcmaine @hostup Would you be able to upgrade the version to 2.1.0 and see if the issue is still there? We had a fix for similar issue via #3702

I update bevor my last post to 2.1.0 but issue persist

**Comment by Soundmagic** [comment] 2022-01-14 20:21
> @Soundmagic @btcmaine @hostup Could you also confirm your Chatwoot setup? Deployment method? Chatwoot version ?

Ubuntu 20 LTS via install script
Chatwoot 2.1.0

**Comment by hostup** [comment] 2022-01-15 10:35
> > @Soundmagic @btcmaine @hostup Could you also confirm your Chatwoot setup? Deployment method? Chatwoot version ?
> 
> Ubuntu 20 LTS via install script Chatwoot 2.1.0

Yes I am using this setup.

**Comment by Soundmagic** [comment] 2022-01-17 07:13
Over the weekend I tried to fix this anyhow.
I did:
- resetting .env and start again --> not effect-> accounts@chatwoot.com is taken everytime
- I disables continously mailer in channel features via rail console --> not effect-> accounts@chatwoot.com is taken everytime
- I change the "accounts@chatwoot.com" in mailer_xxx.rb files --> not effect-> accounts@chatwoot.com is taken everytime
- I set up via super_admin the global parameter "MAILER_SENDER_EMAIL" --> not effect-> accounts@chatwoot.com is taken everytime
- I did a server restart serveral times in between theses changes --> not effect-> accounts@chatwoot.com is taken everytime
- on Ubunutu: I logged in as chatwoot user, start the rails console and checke the ENV output. ENV variable "MAILER_SENDER_EMAIL" is showing the value I setup in .ENV, but in chatwoot itself ----> not effect-> accounts@chatwoot.com is taken everytime

So far, I have no ideas anymore

**Comment by sojan-official** [comment] 2022-01-26 00:47
@Soundmagic  Could you access the rails console and see the value for. 
```
Account.find(account_id).support_email 
```

**Comment by Soundmagic** [comment] 2022-01-26 08:26
Result:

3.0.2 :013 > Account.find(1).support_email
 => "Chatwoot <accounts@chatwoot.com>"

This is strange, because it is not the value I defined during creation of the channel.
 I will set this via rails to my mail adresse an dwill check again.

**Comment by Soundmagic** [comment] 2022-01-26 08:34
okay, I can confirm after changing this, mails sent out with correct mail adresse.
Topic can be closed as resolved.

**Comment by pranavrajs** [comment] 2022-01-26 18:24
@sojan-official It seems like `MAILER_SUPPORT_EMAIL` in installation config is not updated/has more preference than the env variable.

**Comment by g00g1** [comment] 2022-02-17 17:51
I hope my fix will save others a few hours of debugging :)

1) go to the [rails console](https://www.chatwoot.com/docs/self-hosted/monitoring/super-admin-sidekiq#access-rails-console)
2) check if you seeing the same output:
```
3.0.2 :001 > Account.find(1).support_email
=> "Chatwoot <accounts@chatwoot.com>"
```
3) execute next commands (do not forget to change chat@example.com to your own):
```
3.0.2 :002 > Account.update(id: 1, support_email: "chat <chat@example.com>")
 => 
[#<Account:0x0000555f61447828
  id: 1,
  name: "chat",
  created_at: Wed, 15 Feb 2022 16:56:36.195048000 UTC +00:00,
  updated_at: Thu, 17 Feb 2022 17:37:38.001855682 UTC +00:00,
  locale: "en",
  domain: nil,
  support_email: "chat <chat@example.com>",
  settings_flags: 0,
  feature_flags: 15,
  auto_resolve_duration: 7,
  limits: {}>] 
3.0.2 :003 > Account.find(1).support_email
 => "chat <chat@example.com>" 
```

**Comment by sojan-official** [comment] 2022-02-18 08:04
@g00g1  Thanks a lot for reporting this back.

**Closed** 2022-03-25 10:43 UTC
Labels: bug, severity: 3
