### ISSUE TITLE
Not seeing all the Facebook pages I manage

### ISSUE THREAD

**Issue by vinch** [chatwoot/chatwoot#7219] opened 2023-05-30 13:55 UTC
### Describe the bug

While trying to add the Facebook Messenger inbox and giving permission to access the 3 pages I manage, I only see 1 of them in the resulting dropdown (not the one I want).

### To Reproduce

1. Click on "Continue with Facebook" in the new inbox wizard
2. Opt in to all my pages
3. Click on "Save"
4. Only see 1 of my 3 pages in the dropdown list

![Screenshot 2023-05-30 at 15 45 17](https://github.com/chatwoot/chatwoot/assets/155370/b0037034-a63f-48cd-a363-4cfe6d360777)

![Screenshot 2023-05-30 at 15 50 49](https://github.com/chatwoot/chatwoot/assets/155370/ee579d01-f032-4430-bd38-167c71043c9d)

![Screenshot 2023-05-30 at 15 45 42](https://github.com/chatwoot/chatwoot/assets/155370/fa4bc551-336f-407b-97be-cdf45f989c2c)

Note that I tried to do it with the Graph API explorer as well and got the same result (only 1 page).

![Screenshot 2023-05-30 at 15 46 10](https://github.com/chatwoot/chatwoot/assets/155370/2dd054dc-a6bf-48c2-b63c-94590e387283)

### Expected behavior

I should see the 3 pages I selected, not only one.

### Environment

Heroku

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

macOS

### Browser and version

Chrome latest version

### Additional context

Could it be because the 2 missing pages are linked to a business, while the 1 I see is attached to my user?

**Comment by sojan-official** [comment] 2023-05-31 12:35
@vinch  Thanks for reporting back. closing this as the issue is resolved now.

**Closed by sojan-official** 2023-05-31 12:35 UTC

**Comment by vinch** [comment] 2023-05-31 12:37
@sojan-official OK but make sure to modify the source code to ask for the `business_management` permission as well. I shouldn't have to do it from the Graph API Explorer.

**Comment by vinch** [comment] 2023-05-31 12:38
I can create a PR if you want.

**Comment by sojan-official** [comment] 2023-05-31 12:46
> I can create a PR if you want.

oh that will be wonderful ❤️

**Comment by vinch** [comment] 2023-06-01 08:15
Done #7235 ✅
