### ISSUE TITLE
Localhost not working because origin set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by briannezhad** [chatwoot/chatwoot#7980] opened 2023-09-25 15:12 UTC
### Describe the bug

I am developing my app locally and trying to tailor Chatwoot before it goes live in PROD. I installed a self-hosted instance in my app origin, support.example.com. But my localhost:3000 development is not playing well with getting SDK because I get the following error: 

```
Refused to display 'https://support.example.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

```

### To Reproduce

Localhost connecting to origin support.example.com
Chrome Inspector: 
```
Refused to display 'https://support.example.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

```

Image: 
<img width="894" alt="Screenshot 2023-09-25 at 11 27 21 AM" src="https://github.com/chatwoot/chatwoot/assets/10551124/aff1e551-fdfe-464a-880d-d8909e49f139">

### Expected behavior

Load Chatwoot Icon Locally.

### Environment

Other [please specify in the description]

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu 

### Additional context

I am using easypanel, which gives me environment variable control.

**Comment by pranavrajs** [comment] 2023-09-27 13:01
@briannezhad Are you trying to embed the dashboard within another application?

**Comment by adayush** [comment] 2023-12-01 12:05
@pranavrajs I'm facing the same issue and I see that a fix for this was pushed sometime back. I'm running chatwoot through docker, so is there a way for me to use this function through .env or some config?

https://github.com/chatwoot/chatwoot/blob/fdc1123b18864b3602e02fe4e0000eaf3fcd43de/app/controllers/widgets_controller.rb#L72-L74

**Comment by KingZedPriest** [comment] 2023-12-08 13:31
> @briannezhad Are you trying to embed the dashboard within another application?

I am currently having the same issue. I am using Next.js. I created a Chat component that has the code as stated in one of your documentation, when I add the Chat component in my Layout so that the chat will be displayed everywhere in the app, it shows "Refused to display 'https://app.chatwoot.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'" in the console. I am trying to add the Chatwoot in my Next.js and see the button and the way it functions locally.

**Closed** 2023-12-08 15:19 UTC
Labels: need-more-info

**Comment by KingZedPriest** [comment] 2023-12-09 18:10
> @adayush and @KingZedPriest I was using easypanel to install chatwoot, in my case, all I had to do was add this in my `advanced->deploy`:
> 
> `bundle exec rails db:chatwoot_prepare && (bundle exec rails s -p 3000 -b 0.0.0.0 &) && bundle exec sidekiq -C config/sidekiq.yml`

I am using Next.js, so I am not sure the above code can work.

**Comment by adayush** [comment] 2023-12-09 18:12
I'm using Next.js too, the issue is not related to that though. Chatwoot is sending this header.

**Comment by KingZedPriest** [comment] 2023-12-10 03:34
> I'm using Next.js too, the issue is not related to that though. Chatwoot is sending this header.

Did you try another Support Chat System? I have been trying to install one.
