### ISSUE TITLE
How to I receive a gps position from telegram

### ISSUE THREAD

**Issue by adcosoft-gb** [chatwoot/chatwoot#3821] opened 2022-01-20 17:29 UTC
Hello, on chatwoot when I receive a gps position from telegram, I have the following message: No content available

How can I receive them on chatwoot from telegram?

**Comment by iammattmartin** [comment] 2022-01-20 17:40
Support would need to be added in.

**Comment by adcosoft-gb** [comment] 2022-01-20 17:42
I'm new, how can i add the support please?

**Comment by iammattmartin** [comment] 2022-01-20 17:46
Well, you can code it yourself or you''ll need to consider this a feature request - or contact chatwoot and ask for a paid-for integration.

**Comment by adcosoft-gb** [comment] 2022-01-20 17:55
no problem, thank you for your answer

**Comment by sojan-official** [comment] 2022-01-20 23:21
ref: #3398

**Comment by pranavrajs** [comment] 2022-02-08 17:36
Duplicate of #3398. Closing it as we can track the progress there.

**Closed by pranavrajs** 2022-02-08 17:36 UTC
