### ISSUE TITLE
Manually Refresh Messages to receive in live chat or any other inbox

### ISSUE THREAD

**Issue by almomdegal** [chatwoot/chatwoot#10553] opened 2024-12-06 17:57 UTC
I have this issue

my websockets are ok, but i still have to manually refresh the page to get the messages.

     FORCE_SSL: "false" both in app and worker

I´m hosting with docker

_Originally posted by @jjmmbb in https://github.com/chatwoot/chatwoot/issues/9823#issuecomment-2276753932_

**Comment by pranavrajs** [comment] 2024-12-07 05:45
@almomdegal Unfortunately, there’s limited information available to assist you. If you’re not running worker threads, you won’t receive messages in real-time. I hope you can debug from there. Closing this as this is configuration issue, not a bug in Chatwoot.

**Closed by pranavrajs** 2024-12-07 05:45 UTC
