### ISSUE TITLE
Add option to edit webhook url for the API channel

### ISSUE THREAD

**Issue by alfredfrancis** [chatwoot/chatwoot#1361] opened 2020-10-23 13:53 UTC
**Is your feature request related to a problem? Please describe.**
No. It's an enhancement

**Describe the solution you'd like**
We need to have an option to edit the webhook URL for the API channel.

**Comment by muhsin-k** [comment] 2021-04-16 10:49
Closing this as it is a duplicate of #1878

**Closed by muhsin-k** 2021-04-16 10:49 UTC
Labels: enhancement
