### ISSUE TITLE
Chatwoot dashboard Disconnected from Chatwoot after few mints

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#4915] opened 2022-06-23 08:44 UTC
Hello,
We are using GCP with Helm Chart chatwoot server, 
After few mints, the dashboard get disconnected. we have increase the timeout also from 30 seconds to 300 seconds, but still the disconnected popup is there. 

Screenshots:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/38554929/175256769-722b709a-13cf-441f-a935-32391f506683.png">

**Comment by vishnu-narayanan** [comment] 2022-06-23 13:49
@harismateen Could you try setting it to 3600?

**Comment by harismateen** [comment] 2022-06-24 03:25
@vishnu-narayanan is it correct to change it from here under load balancer? or i have to update config file?

![image](https://user-images.githubusercontent.com/38554929/175455933-51b60c52-f68c-4140-8141-b0a7181e7e18.png)

**Comment by vishnu-narayanan** [comment] 2022-06-24 07:01
@harismateen Please change it from the GCP console.

**Comment by harismateen** [comment] 2022-06-24 13:35
@vishnu-narayanan still same :( 
![image](https://user-images.githubusercontent.com/38554929/175546861-1e5a3fef-4e94-4d2f-9dd6-1d7aa7b9b1f1.png)

**Comment by harismateen** [comment] 2022-06-27 07:06
@vishnu-narayanan is there any other suggestion to fix this out?

**Comment by pranavrajs** [comment] 2022-06-28 07:22
@harismateen There is too little information to debug here. Would you be able to share a screencast of the behavior? Explain the conditions under which the issue is being shown.

**Comment by pranavrajs** [comment] 2022-07-05 10:58
Closing this as it is not reproducible from our end.

**Closed by pranavrajs** 2022-07-05 10:58 UTC
