### ISSUE TITLE
WhatsApp Cloud Channel unable to send audio message to the customer

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#5848] opened 2022-11-14 07:21 UTC
**Describe the bug**
Hi,
We are unable to send Audio message from chatwoot to the customer's whatsapp number. 
Channel: WhatsApp Cloud API

**To Reproduce**

1. Go to Open Convo 
2. Click on --> click on mic icon and send audio message
3. Customer unable to received the audio message

**Expected behavior**
1. Go to Open Convo 
2. Click on --> click on mic icon and send audio message
3. Customer to received the audio message on their whatsapp

**Screenshots**

![image](https://user-images.githubusercontent.com/38554929/201598510-4d905d81-c147-4e85-bcb2-41e66a4a566a.png)

**Environment**
 Self-hosted - > GCP --> Helm chart --> v2.7.0

**Comment by giquieu** [comment] 2022-11-16 01:47
@pranavrajs 
I noticed that there were updates to the API Cloud, can I check this task?

**Comment by giquieu** [comment] 2022-11-21 05:33
Hello @sojan-official 
About API updates, on the developer.facebook panel it allows, select 14, so it has no impact on the implementation, since there is no change.

I made several simulations of sending the audio recording and could not reproduce the problem.
Every test the device received the messages.

@harismateen 
Maybe sending the log here will make it easier...
It would also be nice to update your environment.

**Comment by sojan-official** [comment] 2022-11-21 13:04
@giquieu, thanks a lot for taking a look. Let's wait for further info from @harismateen  and close this out if there are no further reports.

**Comment by pranavrajs** [comment] 2023-01-04 23:12
Closing this here as there was no activity for a long time.

**Closed by pranavrajs** 2023-01-04 23:12 UTC
Labels: need-more-info
