### ISSUE TITLE
Error messages are generic and not relevant to the error

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#2104] opened 2021-04-15 11:15 UTC
**Describe the bug**

The error messages the API throws and one displayed in the UI when the user enters the "Forgot password" page and uses an email that's not registered is completely off.

**To Reproduce**

1. Go to https://chatwoot.myorg.com/app/auth/reset/password
2. Enter an email that's not registered
3. The API response is: ```Uh ho! We could not find any user with the specified email```
4. UI error is: "We could not connect to the Woot server. Please try again."

**Expected behavior**

Show the right message

**Screenshots**

NA

**Browser logs**

```
{"message":"Uh ho! We could not find any user with the specified email."}
```
**Server logs**

NA

**Environment**

Docker

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Big Sur
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 1.14.3

**Additional context**

NA

**Comment by muhsin-k** [comment] 2021-04-15 13:26
Closing this as it is a duplicate of #1803

**Closed by muhsin-k** 2021-04-15 13:26 UTC

**Comment by srameshr** [comment] 2021-04-15 14:00
@sojanofficial Will you accept a PR for this?
