### ISSUE TITLE
chat widget doesn't scroll automtically to the end

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5995] opened 2022-11-30 17:29 UTC
**Describe the bug**
The chat widget doesnt scroll automatically to the end of conversation

**To Reproduce**

1. Open the chat widget an write some text messages, so that you have to scroll to see all messages
2. Reload the page and open the widget. You will see, that the widget shows automatically the last message (this is perfect!)
3. Close the conversation (as user or agent)
4. Reload the page and open the widget again. Now you will see the first messag instead of the last (no scroll to the end)

**Screenshots**
Wrong:
<img width="398" alt="Bildschirm­foto 2022-11-30 um 18 19 43" src="https://user-images.githubusercontent.com/17011498/204866754-ec859116-6751-472b-8149-3b56c23ed0e4.png">

Correct:
<img width="397" alt="Bildschirm­foto 2022-11-30 um 18 21 03" src="https://user-images.githubusercontent.com/17011498/204866787-14a931d6-ee38-4f97-b037-18447393f71c.png">

**Environment**

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [X] Self-hosted
- - [ ] Linux VM
- - [X] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: macOS
 - Browser Firefox
 - Version 107.0.1

**Comment by vishnu-narayanan** [comment] 2022-12-01 12:32
I am not able to reproduce this from my end. Resolving the conversation, reloading the page, and opening the chat bubble scrolls to the end.

OS: macOS
Browser: Firefox 106

<img width="452" alt="image" src="https://user-images.githubusercontent.com/3526167/205053489-b87f3526-d592-46b5-bf5e-7c64721bd676.png">

**Comment by Ghost108** [comment] 2022-12-01 12:53
Maybe I explained it wrong.
Try it like this way please:

http://www.giphy.com/gifs/IrTB2asZNi8Y4bKhBQ

**Comment by vishnu-narayanan** [comment] 2022-12-02 06:48
@Ghost108 Yeah, you are right 😅

**Closed** 2022-12-20 07:04 UTC
Labels: bug, Good first issue, frontend, severity: 4, ready-for-pickup
