### ISSUE TITLE
Bug on Signup

### ISSUE THREAD

**Issue by kodermax** [chatwoot/chatwoot#3468] opened 2021-11-26 14:59 UTC
**Describe the bug**

**To Reproduce**

1. Go to '/app/auth/signup'

**Screenshots**

![image](https://user-images.githubusercontent.com/590985/143599393-1c5b4c4f-c7c3-40cb-9d70-fef6b6c3de29.png)

**Comment by sojan-official** [comment] 2021-11-26 16:46
@kodermax  is it on a self-hosted instance or on app.chatwoot.com ?

**Comment by startshineye** [comment] 2022-03-19 13:06
on a self-hosted instance I also encountered such a problem

**Comment by startshineye** [comment] 2022-03-19 13:08
@kodermax Have you solved this problem？

**Comment by startshineye** [comment] 2022-03-19 13:15
https://github.com/chatwoot/chatwoot/issues/1752;

**Comment by kodermax** [comment] 2022-03-19 16:46
Yes, it works

**Comment by pranavrajs** [comment] 2022-03-20 07:38
@kodermax Thanks for confirming. Closing as the issue is solved.

**Closed by pranavrajs** 2022-03-20 07:38 UTC
Labels: need-more-info
