### ISSUE TITLE
Problems with API endpoints

### ISSUE THREAD

**Issue by samuelalvesdev** [chatwoot/chatwoot#9203] opened 2024-04-05 19:34 UTC
### Describe the bug

When I try to make any kind of request to the chatwoot API, I get the following error regardless of the request: "error": "Non permissible resource". 
![image](https://github.com/chatwoot/chatwoot/assets/105619015/9e9e1c8f-7bb8-4826-991d-d4b35256eeb3)

### To Reproduce

1 - Open the postman 
2 - method PATCH
3 - https://app.chatwoot.com/platform/api/v1/accounts/{account_id} 
4 - Body: {
  "status": "suspended"
}
5 - header: Content-Type = application/json; charset=utf-8
api_access_token = 

6 - error =  "error": "Non permissible resource"

### Expected behavior

I want to suspend an account from my chatwoot by API endpoint.

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

ubuntu 22.04.4

### Browser and version

Chrome 

### Docker (if applicable)

Docker version 25.0.4, build 1a576c5

Client: Docker Engine - Community
 Version:    25.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

without docker compose

**Comment by samuelalvesdev** [comment] 2024-04-08 14:39
**When I make a request to this endpoint, I get this information in the log:**
![image](https://github.com/chatwoot/chatwoot/assets/105619015/9b6850c7-4b97-495e-b0a9-3c16578fea47)
**Where can I change the permissions for "validate_plataform_app_permissible"?**

**Comment by vishnu-narayanan** [comment] 2024-04-09 06:00
@samuelalvesdev are you hitting `app.chatwoot.com` endpoint?

Could you share the request you are making in postman as curl?

**Comment by samuelalvesdev** [comment] 2024-04-09 14:35
@vishnu-narayanan 
1. Im hitting my host domain as a self-hosted.
2. curl --location --request PATCH 'https://XXXXX.XXXXXX.com.br/platform/api/v1/accounts/2' \
--header 'Content-Type: application/json' \
--header 'api_access_token: XXXXXXXXXXXXXX' \
--data '{
	"status": "suspended"
}'
3. Yep, im getting the same error for all endpoints. {
    "error": "Non permissible resource"
}

**Comment by vishnu-narayanan** [comment] 2024-04-10 01:50
@samuelalvesdev are you passing a `platformAppApiKey` as the api_access_token?

**Comment by samuelalvesdev** [comment] 2024-04-10 02:14
@vishnu-narayanan 
Yep, `platformAppApiKey` as api_access_token on the header.
![image](https://github.com/chatwoot/chatwoot/assets/105619015/28fb488e-588f-4377-9562-985382be37ec)

**Comment by pranavrajs** [comment] 2024-04-10 05:21
Please check if the account number 2 is suspended. It looks like the API is returning proper results. 

Closing this here as it is not a bug.

**Closed by pranavrajs** 2024-04-10 05:21 UTC
Labels: need-more-info, waiting-for-reply

**Comment by samuelalvesdev** [comment] 2024-04-11 17:07
@pranavrajs 
Are you sure about that?

![Screenshot_2024-04-11-14-04-52-258_com whatsapp](https://github.com/chatwoot/chatwoot/assets/105619015/a52f4c5c-62c7-4d26-922b-a9ed2d5d9660)

**Comment by cifuentesmx** [comment] 2024-04-14 13:16
@samuelalvesdev is the account created with the platform api? Because i had the same issue deleting the account! I could only delete accounts created with the platform API, normal accounts are somehow protected form platform API changes for some reason. At least I think so.

**Comment by pranavrajs** [comment] 2024-04-18 16:49
@cifuentesmx Thanks for the note, I missed that point. It is correct, you can only manage the accounts that were created using the platform app. Any other account (either created directly or by any other platform app) cannot be managed. This is done to improve the security of the system.
