### ISSUE TITLE
Custom URL doesn't have SSL certificate on Self Hosted version

### ISSUE THREAD

**Issue by iamankits** [chatwoot/chatwoot#5799] opened 2022-11-04 13:45 UTC
Hello,

I am using a self hosted version of Chatwoot. I have used the normal linux manual install as shown here: https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm

I have also enable the help center, which works fine to be honest. One thing that is missing is an SSL certificate for custom domain for help center.
I used certbot to generate an SSL for the custom domain via command line. But it still uses the one where my chatwoot installation resides.

Helpcenter URL: help.domain.com
Chatwoot URL: chat.domain.com

SSL Certificate used for both URLS is for chat.domain.com

Can you please help fix this bug?

**Comment by iamankits** [comment] 2022-11-05 03:05
Hello @pranavrajs,

I have already generated the SSL via Certbot by adding the help.domain.com in Nginx.conf fie. I just need to map it to the sub-domain help.domain.com. The issue is help.domain.com is using SSL of chat.domain.com.

Here is the nginx.conf file.
`server {
  listen 80;
  listen [::]:80;
  server_name help.domain.com chat.domain.com www.chat.domain.com;

  access_log /var/log/nginx/chatwoot_access_80.log;
  error_log /var/log/nginx/chatwoot_error_80.log;

  return 301 https://chat.domain.com/;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name chat.domain.com help.domain.com www.chat.domain.com;

  underscores_in_headers on;

  access_log /var/log/nginx/chatwoot_access_443.log;
  error_log /var/log/nginx/chatwoot_error_443.log;

  location / {
   proxy_pass_header Authorization;
   proxy_pass http://127.0.0.1:3000;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "upgrade";
   proxy_set_header Host $host;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_set_header X-Forwarded-Ssl on; # Optional
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_http_version 1.1;
   proxy_set_header Connection "";
   proxy_buffering off;
   client_max_body_size 0;
   proxy_read_timeout 36000s;
   proxy_redirect off;
  }

  ssl_certificate /etc/letsencrypt/live/chat.domain.com/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/chat.domain.com/privkey.pem; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/help.domain.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/help.domain.com/privkey.pem;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA>
  ssl_prefer_server_ciphers off;
  ssl_dhparam /etc/ssl/dhparam;
}
`

**Comment by satoshinotdead** [comment] 2022-11-08 02:07
You can wildcard on Cloudflare using their services or use Let's Encrypt via certbot to enable SSL on every single subdomain.

Are you using a CDN or proxy in front than your Nginx?

**Comment by iamankits** [comment] 2022-11-09 02:25
@satoshinotdead I am not using Cloudflare. I generated the cert using Let's Encrypt certbot. It will either take the domain chat.domain.com or help.domain.com SSL and use it on both the sub-domains creating a SSL error on any of the domains.

**Comment by vishnu-narayanan** [comment] 2022-11-10 12:06
@iamankits Have you tried using a wildcard certificate as @satoshinotdead suggested? 

Generate a cert for `*.yourdomain.tld` using LetsEncrypt.

Ref: https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578

**Comment by satoshinotdead** [comment] 2022-11-12 23:53
Or you can share the logs, but I think that's related to your specific config and not to Chatwoot itself _(BTW maybe I can give a hand because I can't help coding)_.

**Comment by gramakri** [comment] 2022-11-22 18:20
This was [reported](https://forum.cloudron.io/topic/8058/alias-web-domain-for-chatwoot) on the Cloudron package. I can confirm that once we added alias support in the chatwoot package, it just works. i.e chatwoot itself works fine without any changes.

**Comment by akzeronet** [comment] 2022-11-23 01:23
> This was [reported](https://forum.cloudron.io/topic/8058/alias-web-domain-for-chatwoot) on the Cloudron package. I can confirm that once we added alias support in the chatwoot package, it just works. i.e chatwoot itself works fine without any changes.

It's great, just one thing, I was trying with the web domain alias... but the second domain by default redirects to docs.chatdron.com/**app/login** (like the first one), instead of docs.chatdron.net/hc/wiki ( Help Center)

**Comment by vishnu-narayanan** [comment] 2022-11-25 10:34
@gramakri Thank you for the update.

**Comment by vishnu-narayanan** [comment] 2022-11-25 10:35
@akzeronet Closing this since you opened a separate one for the new issue.

**Closed by vishnu-narayanan** 2022-11-25 10:34 UTC
Labels: need-more-info, self-hosted
