### ISSUE TITLE
Ability to add custom status for conversations

### ISSUE THREAD

**Issue by HermesMacedo** [chatwoot/chatwoot#7717] opened 2023-08-12 21:02 UTC
Are there any developments on this issue? Having the possibility to create custom Statuses and be able to use them in the configuration of automations?             

 We have decided to keep the custom statuses on hold in favor of the recently added `snoozed` conversation status.
Let's reopen this PR again when we come back to work on this.

_Originally posted by @sojan-official in https://github.com/chatwoot/chatwoot/issues/1829#issuecomment-890548422_

**Comment by HermesMacedo** [comment] 2023-08-15 18:41
@sojan-official     Can I implement this function? Just to know if there is interest and not waste time and energy.

**Comment by pranavrajs** [comment] 2023-08-15 18:51
@HermesMacedo At the moment, we believe that most of the use cases would be solved by snoozed, labels and custom folders of conversations. However, if you think that there is something which we have missed, please share your thoughts. 

Closing this thread here as it is a duplicate of https://github.com/chatwoot/chatwoot/issues/1795. We can continue the discussion there. 

Thanks.

**Closed by pranavrajs** 2023-08-15 18:51 UTC
