### ISSUE TITLE
an admin have posibility to add same site with same domain at him

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#520] opened 2020-02-19 11:05 UTC
**Describe the bug**
domain: 3clicks.ro
admin who created: Aditza
admin who recreate: John
**To Reproduce**

**Expected behavior**
If an domain have an admin, other admin don't have posibillity to add them
<img width="1594" alt="bug chatwoot" src="https://user-images.githubusercontent.com/4247309/74828810-6ceccc00-5318-11ea-9819-73a177043336.PNG">

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranavrajs** [comment] 2020-02-20 08:16
@aermike Could you please explain a bit more on the issue you are facing right now?

**Comment by aermike** [comment] 2020-02-20 08:56
Hi
I create an admin(without verification) on his name Aditza, who has 2 inboxes (3clicks.ro and chat.3clicks.ro)
After that login with default user john doe@acme..bla and create 2 inboxes (main and 3cliks.ro)
You can  you observe that are 2 admins (one confirmed and one not confirmed) with same imboxes(site domain - I interpret).
Ideea is to check unicity of inboxes (or domain, subdomain), that I think is corect.
On the other hand, if I create on an admin inbox (bla.wix.com (example)), let me create on other admins inboxes like (bla1.wix.com, or xxx.wix.com)
It's corect what I interpret?

**Comment by sojan-official** [comment] 2020-02-25 15:45
@aermike  A single account can have multiple administrators.  if you want to create isolated tenants.  You can create a new user via the signup option or via console.  add add the additional domains to them 

example : 
- login with default user ( john@acme.inc) - add  3clicks.ro and chat.3clicks.ro  
- logout 

- signup with ( aditza ) 
- add the additional domains in that account. 

john won't be able to see the domains in aditza account and  vice versa. let us know if this helps

**Comment by aermike** [comment] 2020-02-25 15:58
Hi
This steps are doing, only with aditza first user add him 3clicks.ro and after thar john@acme.com.
In this ticket I mean he posibility to add same domain 3clicks.ro(which is identical at the two users).
Suplimentary treated cases of subdomain(ex wix.com and have subdomain name1.wix.com, name2.wix.com) at aditza and ...its absolutelly corect to have name3.wix.com at john@acme.com.
But is incorect to have at john@acme.com subdomain...example: name1.wix.com or name2.wix.com, because they have ocuppied by aditza...in first step.
I don't know if i explain very correctly what I mean.
Thank you

**Comment by sojan-official** [comment] 2020-02-25 16:06
@aermike  we don't validate whether a domain name was already added by another user, since the domain names are just for the user to identify a particular inbox.  the real magic happens with the script that the user adds to his website, which makes the chat window appear.  

so even if john@acme.com can add name1.wix.com which was already added by aditza. john wouldn't receive any messages from name1.wix.com because the script added on name1.wix.com is tied to aditza account.   let me know if this answers the question.

**Comment by aermike** [comment] 2020-02-27 15:13
On Tuesday, February 25, 2020, 06:06:45 PM GMT+2, Sojan Jose <notifications@github.com> wrote:  
 
 
@aermike we don't validate whether a domain name was already added by another user, since the domain names are just for the user to identify a particular inbox. the real magic happens with the script that the user adds to his website, which makes the chat window appear.

so even if john@acme.com can add name1.wix.com which was already added by aditza. john wouldn't receive any messages from name1.wix.com because the script added on name1.wix.com is tied to aditza account. let me know if this answers the question.

**Comment by sojan-official** [comment] 2020-03-01 14:28
Closing this for now since it's intended behavior.

**Closed by sojan-official** 2020-03-01 14:28 UTC
