### ISSUE TITLE
Bot conversation displayed in the "Agent" conversation tab

### ISSUE THREAD

**Issue by MatthieuBietry** [chatwoot/chatwoot#1858] opened 2021-03-05 14:05 UTC
**Describe the bug**

We have an agent_bot setuped in an inbox, handleling the conversation from start. This inbox is plugged with an API endpoint.

When we received a new user message, the message is correctly handled by the agent_bot, but it appear in an agent "Mine" tab.

If we refresh the page, the conversation well appear in the "bot" tab (dropdown). 
In database, the conversation have a "bot" status. 

**To Reproduce**

1. Setup an agent_bot and an API inbox
2. Connect as an agent to Chatwoot interface
3. Send a message, the message is well answered by the bot
4. The conversation appear in the "Mine" tab of the agent
5. If you refresh, the conversation appear in the "bot" section, as expected

**Expected behavior**

We expected a conversation handle from the begining by a bot, will be display in the "bot" section

**Environment**

This behaviour has been observed in Heroku environment and in a Docker environment

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 88.0

**Comment by pranavrajs** [comment] 2023-01-12 23:06
Sorry for missing this out. Closing this as the bot status is not longer available and there were a couple of changes from the time the issue is created.

**Closed by pranavrajs** 2023-01-12 23:06 UTC
Labels: bug
