### ISSUE TITLE
Contact load via CSV

### ISSUE THREAD

**Issue by SwimGeek** [chatwoot/chatwoot#10186] opened 2024-09-28 18:23 UTC
### Describe the bug

Self hosted version. I attempted to load contacts via CSV a few times. I get the email saying the contacts were loaded - with zero failures.

Number of records imported: 1579
Number of records failed: 0

But, no extra contacts show up in Chatwoot.

Latest version 3.13.

### To Reproduce

Create CSV file with contacts and import.

### Expected behavior

Expect to see the new contacts after loading them.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Debian

### Browser and version

Safari

**Comment by pranavrajs** [comment] 2024-09-29 19:03
@SwimGeek If there is no identifier for the contact, such as email, identifier field, phone number, then it wouldn't be shown on the UI. Let me know if it is not the case.

**Comment by SwimGeek** [comment] 2024-09-30 11:52
Hi

Managed to get it loaded - but the sample CSV did not work well.

Ended up using headers:

name	email	identifier	phone_number	service

(not id)

**Comment by sojan-official** [comment] 2024-10-01 02:19
> @SwimGeek If there is no identifier for the contact, such as email, identifier field, phone number, then it wouldn't be shown on the UI. Let me know if it is not the case.

Closing since the issue is resolved

**Closed by sojan-official** 2024-10-01 02:19 UTC
Labels: need-more-info, 🧄 feature/agent-ui
