### ISSUE TITLE
Error 500 when using Google OAuth

### ISSUE THREAD

**Issue by matiszz** [chatwoot/chatwoot#9980] opened 2024-08-19 14:11 UTC
### Describe the bug

Hey there! I've installed the Chatwoot app using the [Marketplace](https://www.chatwoot.com/docs/self-hosted/deployment/aws-marketplace) deployment. Then, I edited the `.env` file as mentioned, to prepare for production. One of the things I added is the Google OAuth configuration.

It seems to be correctly configured. When I go to my domain, I can see the "Login with Google", and once clicked, I am able to choose my account.

![image](https://github.com/user-attachments/assets/e2680da2-2a35-46cf-9f53-9835606b6098)

However, after the redirection is made, I get an error 500.

Find below the logs:
```log
-- Logs begin at Mon 2024-06-24 09:55:19 UTC. --
INFO -- : [ID_REMOVED] Completed 200 OK in 13ms (Views: 3.1ms | ActiveRecord: 0.0ms | Allocations: 7280)
INFO -- : source=rack-timeout id=[ID_REMOVED] timeout=15000ms service=16ms state=completed
INFO -- : source=rack-timeout id=[ID_REMOVED] timeout=15000ms state=ready
INFO -- : [ID_REMOVED] Started GET "/app/login" at 2024-08-19 13:53:29 +0000
INFO -- : [ID_REMOVED] Processing by DashboardController#index as HTML
INFO -- : [ID_REMOVED]   Parameters: {"params"=>"login"}
INFO -- : [ID_REMOVED]   Rendered dashboard/index.html.erb within layouts/vueapp (Duration: 0.0ms | Allocations: 4)
INFO -- : [ID_REMOVED]   Rendered layout layouts/vueapp.html.erb (Duration: 15.1ms | Allocations: 2452)
INFO -- : [ID_REMOVED] Completed 200 OK in 28ms (Views: 15.9ms | ActiveRecord: 0.0ms | Allocations: 7251)
INFO -- : source=rack-timeout id=[ID_REMOVED] timeout=15000ms service=35ms state=completed
INFO -- : source=rack-timeout id=[ID_REMOVED] timeout=15000ms state=ready
INFO -- : [ID_REMOVED] Started GET "/omniauth/google_oauth2/callback?code=[FILTERED]&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=[FILTERED]&hd=domain.org&prompt=none" at 2024-08-19 13:53:37 +0000
DEBUG -- omniauth: (google_oauth2) Callback phase initiated.
OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".
INFO -- : [ID_REMOVED] Processing by DeviseOverrides::OmniauthCallbacksController#redirect_callbacks as HTML
INFO -- : [ID_REMOVED]   Parameters: {"code"=>"[FILTERED]", "scope"=>"email profile https://www.googleapis.com/auth/userinfo.email openid https://www.googleapis.com/auth/userinfo.profile", "authuser"=>"[FILTERED]", "hd"=>"domain.org", "prompt"=>"none", "provider"=>"google_oauth2"}
INFO -- : [ID_REMOVED] Redirected to https://chatwoot.domain.org/auth/google_oauth2/callback
INFO -- : [ID_REMOVED] Completed 307 Temporary Redirect in 1ms (ActiveRecord: 0.0ms | Allocations: 333)
INFO -- : source=rack-timeout id=[ID_REMOVED] timeout=15000ms service=245ms state=completed
INFO -- : source=rack-timeout id=[ID_REMOVED] timeout=15000ms state=ready
INFO -- : [ID_REMOVED] Started GET "/auth/google_oauth2/callback" at 2024-08-19 13:53:38 +0000
INFO -- : [ID_REMOVED] Processing by DeviseOverrides::OmniauthCallbacksController#omniauth_success as HTML
INFO -- : [ID_REMOVED]   Parameters: {"provider"=>"google_oauth2"}
INFO -- : [ID_REMOVED] Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms | Allocations: 569)
FATAL -- : [ID_REMOVED]
NoMethodError (undefined method `[]' for nil):

app/controllers/devise_overrides/omniauth_callbacks_controller.rb:52:in `get_resource_from_auth_hash'
app/controllers/devise_overrides/omniauth_callbacks_controller.rb:5:in `omniauth_success'
app/controllers/concerns/switch_locale.rb:39:in `set_locale'
app/controllers/concerns/switch_locale.rb:12:in `switch_locale'
INFO -- : source=rack-timeout id=[ID_REMOVED] timeout=15000ms service=6ms state=completed
```

### To Reproduce

1. Install Chatwoot from the AWS Marketplace (it was working fine)
2. Modify .env and setup Google OAuth following these [instructions](https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#google-oauth)
3. Click on "Login with Google"
4. Select your user
5. Get redirected and see an error:

![image](https://github.com/user-attachments/assets/07492453-c377-4b68-abc0-dcec581062fa)

### Expected behavior

I would expect to access the app.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Mac OS

### Browser and version

Google Chrome 127.0.6533.120

**Comment by pranavrajs** [comment] 2024-08-20 15:17
@scmmishra Please take a look.

**Comment by scmmishra** [comment] 2024-08-21 08:42
It seems that the callback is not getting processed properly, can you confirm if the `GOOGLE_OAUTH_CLIENT_ID` and `GOOGLE_OAUTH_CLIENT_SECRET` pairs are set correctly?

**Comment by matiszz** [comment] 2024-08-21 09:44
Hey @scmmishra! Thanks for your quick answer. Yes, I've just double-checked and the ClientID and Secret are set correctly. I guess it makes sense, because the "Login with Google" screen opens up correctly, the problem is with the redirect.

**Comment by scmmishra** [comment] 2024-08-21 10:12
Noted, which version of Chatwoot are you using? @vishnu-narayanan can you confirm if the marketplace image is the latest release?

**Comment by matiszz** [comment] 2024-08-21 10:30
@scmmishra, I'm using cwctl v2.8.0:

```
ubuntu@ip-10-0-0-23:~$ sudo -i -u chatwoot
chatwoot@ip-10-0-0-23:~$ cd chatwoot/
chatwoot@ip-10-0-0-23:~/chatwoot$ sudo cwctl --version
cwctl v2.8.0

chatwoot@ip-10-0-0-23:~/chatwoot$ cat VERSION_CW
3.9.0
```

Not sure if the version of cwctl and the general Chatwoot software are the same though.

**Comment by matiszz** [comment] 2024-08-21 10:30
I did run `sudo cwctl --upgrade` before.

**Comment by vishnu-narayanan** [comment] 2024-08-21 15:51
@matiszz Could you share the output of `https://<your-chatwoot-installation-url>/api` ?

**Comment by matiszz** [comment] 2024-08-21 16:44
@vishnu-narayanan 

{"version":"3.11.1","timestamp":"2024-08-21 16:44:20","queue_services":"ok","data_services":"ok"}

**Comment by vishnu-narayanan** [comment] 2024-08-22 04:30
@matiszz `cwctl --upgrade` should have upgraded you to the latest version, `3,12`. Did you get any errors when you ran `cwctl --upgrade`?

Could you try rerunning it and share the output?

**Comment by matiszz** [comment] 2024-08-22 09:09
Hi @vishnu-narayanan, I've run `cwctl --upgrade` again (it's weird, I did run it before), find the output below.

Also, the output of the /api URL:
```
{"version":"3.12.0","timestamp":"2024-08-22 09:00:36","queue_services":"ok","data_services":"ok"}
```

However, I still have the same error when trying to login with google.
```
Aug 22 09:04:30 ip-10-0-0-23 chatwoot-web.1[858489]: [53670628-ffa0-4736-977a-8c410a7319eb] NoMethodError (undefined method `[]' for nil):
Aug 22 09:04:30 ip-10-0-0-23 chatwoot-web.1[858489]: [53670628-ffa0-4736-977a-8c410a7319eb]
Aug 22 09:04:30 ip-10-0-0-23 chatwoot-web.1[858489]: [53670628-ffa0-4736-977a-8c410a7319eb] app/controllers/devise_overrides/omniauth_callbacks_controller.rb:52:in `get_resource_from_auth_hash'
Aug 22 09:04:30 ip-10-0-0-23 chatwoot-web.1[858489]: [53670628-ffa0-4736-977a-8c410a7319eb] app/controllers/devise_overrides/omniauth_callbacks_controller.rb:5:in `omniauth_success'
Aug 22 09:04:30 ip-10-0-0-23 chatwoot-web.1[858489]: [53670628-ffa0-4736-977a-8c410a7319eb] app/controllers/concerns/switch_locale.rb:39:in `set_locale'
Aug 22 09:04:30 ip-10-0-0-23 chatwoot-web.1[858489]: [53670628-ffa0-4736-977a-8c410a7319eb] app/controllers/concerns/switch_locale.rb:12:in `switch_locale'
```

**Output of the `cwctl --upgrade` command:**
```
chatwoot@ip-10-0-0-23:~/chatwoot$ sudo cwctl --upgrade
Checking for cwctl updates...
Your cwctl is up to date
Upgrading Chatwoot to v3.12.0
Checking Redis availability...
Checking Redis version...
Redis is already version 7.2.5 (>= 7). Skipping Redis upgrade.
Checking Node.js version...
Node.js is already version 20.15.0 (>= 20.x). Skipping Node.js upgrade.
Already on 'master'
Your branch is up to date with 'origin/master'.
remote: Enumerating objects: 3318, done.
remote: Counting objects: 100% (3211/3211), done.
remote: Compressing objects: 100% (1270/1270), done.
remote: Total 3318 (delta 2287), reused 2745 (delta 1925), pack-reused 107 (from 1)
Receiving objects: 100% (3318/3318), 1.05 MiB | 9.91 MiB/s, done.
Resolving deltas: 100% (2296/2296), completed with 165 local objects.
From https://github.com/chatwoot/chatwoot
   ffc018380..d70ba8ff4  master                                                  -> origin/master
 * [new branch]          chore-global-config-mixin                               -> origin/chore-global-config-mixin
   7db7ae0ed..462064bfc  chore-repalce-configMixin-with-useConfig-composable     -> origin/chore-repalce-configMixin-with-useConfig-composable
 * [new branch]          chore-replace-campaign-mixin                            -> origin/chore-replace-campaign-mixin
   0d3780a59..7ec528bd3  chore-replace-darkModeMixin-with-useDarkMode-composable -> origin/chore-replace-darkModeMixin-with-useDarkMode-composable
 * [new branch]          chore-replace-hook-mixin                                -> origin/chore-replace-hook-mixin
 * [new branch]          chore-replace-message-formatter-mixin                   -> origin/chore-replace-message-formatter-mixin
 * [new branch]          chore-replace-portal-mixin                              -> origin/chore-replace-portal-mixin
   a0153daca..c69796411  chore-replace-router-mixin                              -> origin/chore-replace-router-mixin
 * [new branch]          chore/custom-role-apis                                  -> origin/chore/custom-role-apis
   28d9dd092..2b418aaa8  chore/custom-roles-model                                -> origin/chore/custom-roles-model
   855b9c8f2..c63a6ed8e  develop                                                 -> origin/develop
   c545b041a..e5a8634a8  feat/CW-3437                                            -> origin/feat/CW-3437
   b501fd797..230a7fe9b  feat/CW-3443                                            -> origin/feat/CW-3443
 * [new branch]          feat/automations                                        -> origin/feat/automations
   43adbe574..26dd04012  fix/CW-3385                                             -> origin/fix/CW-3385
 * [new branch]          fix/CW-3536                                             -> origin/fix/CW-3536
 * [new branch]          fix/disallow-disposable-emails                          -> origin/fix/disallow-disposable-emails
   5c451d3c9..02f18ce2a  fix/tabs-spacing                                        -> origin/fix/tabs-spacing
 + 644d7dc51...35e98d1e2 i18n-crowdin-translations                               -> origin/i18n-crowdin-translations  (forced update)
 * [new branch]          refactor-replace-router-composable                      -> origin/refactor-replace-router-composable
 * [new tag]             v3.12.0                                                 -> v3.12.0
Updating ffc018380..d70ba8ff4
Fast-forward
 .env.example                                                                                                       |    1 +
 .eslintrc.js                                                                                                       |  154 ++++++++++
 .storybook/preview.js                                                                                              |    4 +-
 Gemfile                                                                                                            |    4 +-
 Gemfile.lock                                                                                                       |   33 +--
 app/builders/messages/messenger/message_builder.rb                                                                 |    2 +-
 app/controllers/api/v1/accounts/integrations/apps_controller.rb                                                    |    2 +-
 app/controllers/api/v1/accounts/integrations/captain_controller.rb                                                 |   22 ++
 app/javascript/dashboard/App.vue                                                                                   |   58 ++--
 app/javascript/dashboard/api/integrations.js                                                                       |    4 +
 app/javascript/dashboard/assets/scss/_woot.scss                                                                    |    5 +
 app/javascript/dashboard/assets/scss/widgets/_woot-tables.scss                                                     |    6 +-
 app/javascript/dashboard/components/Accordion/AccordionItem.vue                                                    |   64 ++---
 app/javascript/dashboard/components/ChannelSelector.vue                                                            |   28 +-

... # Deleted because otherwise the comment is too long.

Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--3-1!node_modules/vue-loader/lib/loaders/stylePostLoader.js!node_modules/postcss-loader/dist/cjs.js??ref--3-2!node_modules/sass-loader/dist/cjs.js??ref--3-3!node_modules/vue-loader/lib/index.js??vue-loader-options!app/javascript/widget/components/template/IntegrationCard.vue?vue&type=style&index=0&id=6b9cd794&prod&lang=scss&scoped=true&:
    Entrypoint mini-css-extract-plugin = *
       2 modules

/usr/local/rvm/gems/ruby-3.3.3/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: /usr/local/rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/mutex_m.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of activesupport-7.0.8.4 to add mutex_m into its gemspec.
DEPRECATION WARNING: Dotenv::Railtie is deprecated! Use Dotenv::Rails instead. (called from <top (required)> at /home/chatwoot/chatwoot/config/application.rb:14)
I, [2024-08-22T08:47:39.808196 #858423]  INFO -- : [dotenv] Loaded .env
I, [2024-08-22T08:47:39.808375 #858423]  INFO -- : [dotenv] Loaded .env
Loading Installation config
```

**Comment by vishnu-narayanan** [comment] 2024-08-23 04:36
@matiszz From the logs, your upgrade to `3.12` was successful. 

Were you trying with a Google Workspace account or a regular Gmail account? Also, could you try another with another Google account?

cc: @scmmishra

**Comment by matiszz** [comment] 2024-08-27 10:22
Hi @vishnu-narayanan, thanks for your support. After debugging a lot, I've realized the problem was that my `FRONTEND_URL` environment variable contained a `/` in the end, so it was redirecting to mydomain.com//app

Hope this doesn't happen to anyone else!

**Comment by pranavrajs** [comment] 2024-09-16 04:44
Closing this as the issue is resolved.

**Closed by pranavrajs** 2024-09-16 04:44 UTC
Labels: Bug, 👑 feature/google-login
