### ISSUE TITLE
Customize the time a user is muted and also add simplified ability in GUI to delete conversations and contacts

### ISSUE THREAD

**Issue by jlar0che** [chatwoot/chatwoot#1781] opened 2021-02-16 11:16 UTC
**Is your enhancement request related to a problem? Please describe.**
Our team is using Chatwoot for customer support and we often get spam messages / requests due to the nature of our work. IT is training staff on usage of Chatwoot and have instructed them to mute any spam requests. Unfortunately, when we mute a spam entry there is a popup that says the user will be muted for **just six hours**. Additionally, these spam messages populate our contact list with fake email addresses and our conversation list with fake requests (often filled with profane language, racist remarks, etc.).

**Describe the solution you'd like**
We'd really like the ability to set custom time-limits for muting a user (and/or an IP address). We'd also like the ability to delete conversations and contacts.

**Describe alternatives you've considered**
Our only alternative was to mute spam conversations and hope that the person who sent the spam doesn't decide to send it again 6 hours later. We would also have to manually delete both spam conversations and spam contacts via API or directly on the Chatwoot database. This is not something a regular user can do and it is more work for admins. Additionally, if something is done incorrectly we run the risk of damaging our Chatwoot application installation.

**Additional context**
Having the ability to delete IP addresses would also be very helpful. Please consider that if Chatwoot is deployed on a website that has "polarizing" or "charged" content the application is definitely going to be used as a way to flood the organization with spam. 

For example, our organization is fighting for debt cancellation for student loans and also advocates for universal healthcare, and fully-funded public higher education. Unfortunately, in the United States, when one declares healthcare and publicly-funded university should be instituted there are people who get upset and want to lash out via the internet.

**Comment by iammattmartin** [comment] 2021-02-16 13:38
I think this may be part duplicate of #1007 (blocking and muting for X period) and  #1283 (delete conversations).

**Comment by sojan-official** [comment] 2021-02-18 11:57
ref #1707  #947

**Comment by sojan-official** [comment] 2024-02-13 03:52
closing in favor of https://github.com/chatwoot/chatwoot/issues/3996#issuecomment-1216391992

**Closed by sojan-official** 2024-02-13 03:52 UTC
Labels: 🐗 Need Product Spec
