### ISSUE TITLE
Account limit exceeded. Upgrade to a higher plan 

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5922] opened 2022-11-23 13:29 UTC
Hi!

I deleted my web widget inbox and would create a new one.
But I cant: I get the response: Account limit exceeded. Upgrade to a higher plan 

I have no inboxes at the moment - which limit is exceeded?

I am unsing the self hosted docker version.

**Comment by sojan-official** [comment] 2022-11-23 14:24
@Ghost108, did you configure an inbox limit for your account via super admin ?

**Comment by glauberssoutodossantos** [comment] 2022-11-23 15:24
@Ghost108 you need to configure your account here

![image](https://user-images.githubusercontent.com/99494469/203584111-db807292-2689-4746-9885-17f57aa677cb.png)

**Comment by Ghost108** [comment] 2022-11-23 16:39
No. No Limits

**Comment by Ghost108** [comment] 2022-11-24 06:11
![Bildschirm­foto 2022-11-24 um 07 09 56](https://user-images.githubusercontent.com/17011498/203707189-c2dd34dc-8b70-4013-abd1-a921584d3b85.png)
As you can see. I have to delete the database and "reinstall" chatwoot. Now it works.

**Comment by sojan-official** [comment] 2022-11-24 07:06
@Ghost108  could have been a case of some migrations not being run. 
Closing this as the issue is resolved.

**Closed by sojan-official** 2022-11-24 07:06 UTC
