### ISSUE TITLE
Cannot enable push notifications in webcatalog.io

### ISSUE THREAD

**Issue by jacekmichalski** [chatwoot/chatwoot#6640] opened 2023-03-09 10:22 UTC
Hi,
I've been testing chatwoot cloud in recent days and wanted to use webcatalog.io to create a windows app. The problem I've encountered is that even though it's based on chromium and !!(‘Notification’ in window); returns true in console the push notifications doesn't work.

1. Install webcatalog.io
2. install chatwoot using webcatalog (they have the app configured for it)
3. Go to profile -> settings -> enable push notification
4. See the error "The browser does not support desktop notifications"

**Expected behavior**

Push notifications should work because webcatalog.io is based on chromium

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [x] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: [Windows 10]

**Comment by iammattmartin** [comment] 2023-03-10 22:22
Dupe of #945 which was closed.

**Comment by pranavrajs** [comment] 2023-05-31 21:50
We use web-push protocol, which doesn't seem to be supported in Electron. A web catalog is a wrapper on top of electron. I'm afraid we can support this without the help of additional configuration.

A similar thread is here. https://stackoverflow.com/questions/41705243/is-it-possible-to-receive-web-pushes-in-an-electron-app

**Closed by pranavrajs** 2023-05-31 21:50 UTC
