### ISSUE TITLE
Unable to start a conversation with a template using WhatsApp Cloud Inbox

### ISSUE THREAD

**Issue by MaoBueno** [chatwoot/chatwoot#5226] opened 2022-08-08 15:07 UTC
**Describe the bug**

Unable to start a conversation with a template using WhatsApp Cloud Inbox

**To Reproduce**
Select an approved whatsapp template and send it

**Expected behavior**

The message reaches the recipient

**Environment**
CapRover
Chatwoot version 2.7.0

**Comment by pranavrajs** [comment] 2022-08-08 16:01
@MaoBueno Please share logs/screencasts to help us debug the issue.

**Comment by weppa-cloud** [comment] 2022-08-08 16:46
Same problem here:  I'm not able to start a conversation with a template using the WhatsApp Cloud inbox

**Comment by MaoBueno** [comment] 2022-08-08 17:40
> @MaoBueno Please share logs/screencasts to help us debug the issue.

![imagen](https://user-images.githubusercontent.com/50222850/183478756-57dc6754-9741-4ddd-bc94-dfce9f4fb585.png)
This is a whatsapp template but the message does not reach the recipient, the channel is created with Whatsapp Cloud

**Comment by MaoBueno** [comment] 2022-08-09 16:46
> @MaoBueno Please share logs/screencasts to help us debug the issue.

![imagen](https://user-images.githubusercontent.com/50222850/183709670-295b57a2-df3a-4b80-8e95-56fcef346d7b.png)
{"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"***************", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"5731**********", "phone_number_id"=>"106706**********", "_aj_hash_with_indifferent_access"=>true}, "contacts"=>[{"profile"=>{"name"=>"M. Y. T. Q.", "_aj_hash_with_indifferent_access"=>true}, "wa_id"=>"573********", "_aj_hash_with_indifferent_access"=>true}], "messages"=>[{"from"=>"573106******", "id"=>"wamid.HBgMNTczMTA2NTAzNDY3FQIAEhggMUNGMzU0QjYwMEE2MEQ2M0NBRTBFQzgxNURGMjg1QTkA", "timestamp"=>"1660062829", "errors"=>[{"code"=>131051, "details"=>"Message type is not currently supported", "title"=>"Unsupported message type", "_aj_hash_with_indifferent_access"=>true}], "type"=>"unsupported", "_aj_hash_with_indifferent_access"=>true}], "_aj_hash_with_indifferent_access"=>true}, "field"=>"messages", "_aj_hash_with_indifferent_access"=>true}], "_aj_hash_with_indifferent_access"=>true}], "controller"=>"webhooks/whatsapp", "action"=>"process_payload", "phone_number"=>"+573127105957", "whatsapp"=>{"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"110554368418177", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"573127105957", "phone_number_id"=>"106706842141523", "_aj_hash_with_indifferent_access"=>true}, "contacts"=>[{"profile"=>{"name"=>"M. Y. T. Q.", "_aj_hash_with_indifferent_access"=>true}, "wa_id"=>"573106503467", "_aj_hash_with_indifferent_access"=>true}], "messages"=>[{"from"=>"573106503467", "id"=>"wamid.HBgMNTczMTA2NTAzNDY3FQIAEhggMUNGMzU0QjYwMEE2MEQ2M0NBRTBFQzgxNURGMjg1QTkA", "timestamp"=>"1660062829", "errors"=>[{"code"=>131051, "details"=>"Message type is not currently supported", "title"=>"Unsupported message type", "_aj_hash_with_indifferent_access"=>true}], "type"=>"unsupported", "_aj_hash_with_indifferent_access"=>true}], "_aj_hash_with_indifferent_access"=>true}, "field"=>"messages", "_aj_hash_with_indifferent_access"=>true}], "_aj_hash_wi...

**Comment by sojan-official** [comment] 2022-08-09 17:18
@MaoBueno  Thanks for the logs. seems like a duplicate of https://github.com/chatwoot/chatwoot/issues/5128 . lets track it over there

**Closed by sojan-official** 2022-08-09 17:18 UTC
Labels: need-more-info
