### ISSUE TITLE
[Docker] Upgrade from v2.13.1 to 2.14.0 FAILS.

### ISSUE THREAD

**Issue by migarol** [chatwoot/chatwoot#6485] opened 2023-02-17 17:06 UTC
I followed the steps in this guide: https://www.chatwoot.com/docs/self-hosted/deployment/upgrade

docker-compose down
docker-compose pull
docker-compose up -d
docker exec -it $(basename $(pwd))_rails_1 sh -c 'RAILS_ENV=production bundle exec rails db:chatwoot_prepare'

This is the error message i get:

docker exec -it $(basename $(pwd))_rails_1 sh -c 'RAILS_ENV=production bundle exec rails db:chatwoot_prepare'

Your Ruby version is 3.1.3, but your Gemfile specified 3.0.4

**Comment by politsin** [comment] 2023-02-17 19:15
I also have a problem with the update v2.13.1 to 2.14.0 
decided to describe the problem here instead of creating a separate ticket.

After the update, both containers `chatwoot_sidekiq_1` and `chatwoot_rails_1` are in the status of "Exited".

When i try to start conteiner `docker start chatwoot_sidekiq_1 -a` i got an error:
```

bundler: failed to load command: sidekiq (/gems/ruby/3.1.0/bin/sidekiq)
/usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `urandom': failed to get urandom (RuntimeError)
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `singleton class'
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:42:in `<module:SecureRandom>'
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:41:in `<top (required)>'
        from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/client.rb:3:in `require'
        from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/client.rb:3:in `<top (required)>'
        from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq.rb:7:in `require'
        from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq.rb:7:in `<top (required)>'
        from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/cli.rb:11:in `require'
        from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/lib/sidekiq/cli.rb:11:in `<top (required)>'
        from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/bin/sidekiq:7:in `require_relative'
        from /gems/ruby/3.1.0/gems/sidekiq-6.4.2/bin/sidekiq:7:in `<top (required)>'
        from /gems/ruby/3.1.0/bin/sidekiq:25:in `load'
        from /gems/ruby/3.1.0/bin/sidekiq:25:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/cli.rb:28:in `start'
        from /usr/local/bundle/gems/bundler-2.4.7/exe/bundle:45:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.4.7/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.4.7/exe/bundle:33:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'

```

**Comment by migarol** [comment] 2023-02-17 19:18
Update: My issue was that i had the /app volume on host, so code never really updated at all.
For me it's working now.

**Comment by politsin** [comment] 2023-02-17 19:24
I have two installations of chatwoot on different servers. 
### 1
One server updated without any problems
Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2

### 2
The second got the problem that is described by the message above.
Linux 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64
Docker version 18.03.1-ce, build 9ee9f40

**Comment by politsin** [comment] 2023-02-17 19:43
I seem to have had trouble whith volumes. 
Now the update has passed and the database update is running.

**Comment by sojan-official** [comment] 2023-02-20 10:57
Thanks for the updates @politsin & @migarol . Closing this as the issue is resolved now.

**Closed by sojan-official** 2023-02-20 10:57 UTC
