### ISSUE TITLE
Local setup failing when using docker

### ISSUE THREAD

**Issue by BhaveshSGupta** [chatwoot/chatwoot#741] opened 2020-04-19 03:38 UTC
Hello,
**Describe the bug**
I am trying to setup this project locally on my system using docker.  It is failing to setup. I have tried setting it up on develop.
I have been following this [guide](https://www.chatwoot.com/docs/installation-guide-docker).

**To Reproduce**
1. git clone https://github.com/chatwoot/chatwoot.git
2. cp .env.example .env
3. Add password for redis on .env
REDIS_PASSWORD=redis
4. docker-compose build
5. docker-compose run --rm rails bundle exec rails db:reset
![image](https://user-images.githubusercontent.com/4209637/79678398-d0ac4c00-8218-11ea-9d89-891014e09562.png)
6. docker-compose up
![image](https://user-images.githubusercontent.com/4209637/79678855-4dd9c000-821d-11ea-8ce8-77f7256da631.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - build version 18363.778

**Comment by vishnu-narayanan** [comment] 2020-04-19 04:44
Is step 4 `docker-compose build` successful ?

**Comment by vishnu-narayanan** [comment] 2020-04-19 05:22
Looks like this might be due to EOL difference between Linux and Windows. Could you change the EOLs from CRLF to LF and try again ? 

Ref: https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory

**Comment by BhaveshSGupta** [comment] 2020-04-19 16:16
Hi @vishnu-narayanan,
Thank you for the help, this turned out to be bummer, I need to configure in git to use LR line endings.

After changing to LR now when I am trying to run I get this error. 
![image](https://user-images.githubusercontent.com/4209637/79693252-2e777d00-8287-11ea-9f98-edf32451178d.png)


I think I have done something wrong in configuration,

But I have been following https://www.chatwoot.com/docs/environment-variables and https://www.chatwoot.com/docs/installation-guide-docker to configure inside docker

**Comment by pranavrajs** [comment] 2020-04-22 08:00
@sojan-official / @sony-mathew Could you please look into this?

**Comment by sojan-official** [comment] 2020-04-23 10:31
@BhaveshSGupta  we are having a hard time replicating this issue. is it still persisting?

**Comment by pranavrajs** [comment] 2020-05-05 08:16
Closing this as the issue is not reproducible. 

@BhaveshSGupta Please feel free to re-open if you still face any issue.

**Closed by pranavrajs** 2020-05-05 08:16 UTC

**Comment by BhaveshSGupta** [comment] 2020-05-05 08:34
@pranavrajs , okay
As of now I am not getting same error. But I was not able to set-it up and running on my system.
