### ISSUE TITLE
Chatwoot-Telgram integration chatwoot is running on cloud plotform but after integrating telegram bot messages are not coming and going

### ISSUE THREAD

**Issue by jayachandrab** [chatwoot/chatwoot#5419] opened 2022-09-12 04:26 UTC
Chatwoot-Telgram integration chatwoot is running on cloud platform but after integrating telegram bot messages are not coming and going. Please do the needful

**Comment by sojan-official** [comment] 2022-09-14 12:04
@jayachandrab, Could you provide a screencast of the behavior?

**Comment by jayachandrab** [comment] 2022-09-14 12:16
as shown in the above screen shot there is not send message option or not receiving any messages sent to bot by other users.

**Comment by sojan-official** [comment] 2022-09-14 13:01
@jayachandrab, you can verify whether your telegram bot is successfully connected to the chatwoot installation by calling the following URL

```
#replace your bot token with the actual token
https://api.telegram.org/bot{your_bot_token}/getWebhookInfo
```

If successfully connected,  it will return your installation/webhooks/telegram. 
if it is not connected, try deleting the inbox and reconnecting again. 

ref: https://www.chatwoot.com/docs/contributing-guide/telegram-channel-setup

**Comment by jayachandrab** [comment] 2022-09-14 13:07
I got the below response
{"ok":true,"result":{"url":"","has_custom_certificate":false,"pending_update_count":7}}
when hit the below url.
https://api.telegram.org/bot{your_bot_token}/getWebhookInfo

**Comment by sojan-official** [comment] 2022-09-14 13:47
@jayachandrab  please refer : https://stackoverflow.com/questions/49308744/telegram-bot-ssl-error-ssl-error-error1416f086ssl-routinestls-process-serve

**Comment by jayachandrab** [comment] 2022-09-19 07:04
currently I am getting below error now the ssl corticate error is not comin

{"ok":true,"result":{"url":"https://blai.cloudgaming.my/app/accounts/1/inbox/31","has_custom_certificate":false,"pending_update_count":4,"last_error_date":1663571034,"last_error_message":"Wrong response from the webhook: 404 Not Found","max_connections":40,"ip_address":"52.187.37.182"}}

**Comment by sojan-official** [comment] 2022-09-19 19:47
@jayachandrab  you don't need to manually set the url. if the you fixed the SSL error. just delete the inbox and recreate a new one. Chatwoot will automatically register the appropriate webhook with telegram

**Comment by jayachandrab** [comment] 2022-09-20 01:32
if add a new one again same issue, no messages are coming to inbox and goin from inbox.

**Comment by pranavrajs** [comment] 2023-01-12 22:30
Closing this here as the problem is not related to Chatwoot rather the issue with SSL Setup.

**Closed by pranavrajs** 2023-01-12 22:30 UTC
