### ISSUE TITLE
It is not possible to have internal inbox name, without giving the chatwidget the same name.

### ISSUE THREAD

**Issue by brundles** [chatwoot/chatwoot#5356] opened 2022-08-30 08:14 UTC
**Describe the bug**

When I set up an inbox, the inbox name i see internally and the name that is displayed to the customer is the same. 

This is very annoying, as I cannot as an example define "Support Germany" and "Support UK" in my settings, without my UK customers having to see "Support UK" in the chat widget window.

This is a small thing, but extremely annoying as it prevents us from getting a decent internal structure to our channels, without polluting the messaging we want to present to the visitors on the site.

**To Reproduce**

- Go to inbox settings
- Write a text in "Website name"
- Click update.
- Go to widget-builder
- See that the name is the same as the inbox is called, and if you change it here, you will also change the inbox name

**Expected behavior**

The internal name of an inbox and the name displayed to the public should be 2 different fields, giving us the option to differentiate those.

It would be fine if the system at setup copied the name from inbox settings onto the widget the first time for a faster setup, but it should allow for us to overwrite it.

**Screenshots**

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/6731143/187384961-4eafb97f-93b4-45b4-9411-e267ad336d36.png">

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/6731143/187385198-0a5dffe3-c1e6-47b6-935e-b1c705a76737.png">

**Comment by pranavrajs** [comment] 2022-10-26 23:59
Closing this as this is the duplicate of #4228

**Closed by pranavrajs** 2022-10-26 23:59 UTC
