### ISSUE TITLE
Support ARM architecture 

### ISSUE THREAD

**Issue by hexclann** [chatwoot/chatwoot#7565] opened 2023-07-21 04:43 UTC
### Is your feature or enhancement related to a problem? Please describe.

The current public container images for chatwoot do not work on ARM64 servers.

### Describe the solution you'd like

Provide multi-architecture images so that chatwoot can be run on ARM64 servers.

**Comment by Startouf** [comment] 2023-07-28 12:49
Duplicate of https://github.com/chatwoot/chatwoot/issues/7470

**Comment by pranavrajs** [comment] 2023-08-15 19:52
Closing this as the issue is a duplicate.

**Closed by pranavrajs** 2023-08-15 19:52 UTC
Labels: ✨ feature-request
