### ISSUE TITLE
widget shows agent offline

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5763] opened 2022-10-26 11:16 UTC
**Describe the bug**
The web widget show agent as offline:
<img width="391" alt="Bildschirm­foto 2022-10-26 um 13 09 22" src="https://user-images.githubusercontent.com/17011498/198011864-c595f02f-2906-42c9-98f7-ee8df9e3a02b.png">
(=we are away at the moment)

Yes, thats right -> because I closed the window of my agent web interface.
BUT: I also using the ios chatwoot app

**Expected behavior**
If I close the agent web interface on my pc - the widget shows the agent still online, because the ios cahtwoot app is online.

**Environment**
- [x] Self-hosted
- - [x] Docker

**Comment by mariusa** [comment] 2022-10-29 09:00
Recently we only see 'We are away at the moment' message, even though an agent has the inbox opened in a browser tab. We didn't set staff hours availability. This used to work.

There's also an error in console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at a.setLocale (App.vue:139:1)
    at App.vue:239:1
```

**Comment by pranavrajs** [comment] 2022-10-31 02:55
@iamsivin Please check this behavior whenever you have time and see if you can reproduce the error mentioned above.

**Comment by panaras10** [comment] 2022-11-02 03:44
I am able to replicate this error on our end too on some occasions. I think it has to do with Redis not refreshing the status correctly?

**Comment by iamsivin** [comment] 2022-11-02 05:18
@pranavrajs I tested it out with staging and couldn't reproduce it.

1. Tested it with business hours settings turned off.
     https://www.loom.com/share/8c4cc53fc5894260828afd1a342c4645

2. Tested it with business hours settings turned on. It is not updating automatically but shows while refreshing.
     https://www.loom.com/share/c0d858e458a24d33be6bcf05d81e8c5c
     
Correct me if I'm wrong. 

Can you guys share much more context on this issue? Can you share more, like the app version, steps for testing that you tested, etc.?

**Comment by mariusa** [comment] 2022-11-02 09:12
Hi, I'm using https://www.chatwoot.com/ (hosted by you)

1. open Inbox in a browser tab https://app.chatwoot.com/app/accounts/.../inbox/16877
2. in another browser profile, open the page which has embedded chat
3. click on chat icon
4. see attached 
![2022-11-02_11-11](https://user-images.githubusercontent.com/1283842/199450147-0a19788a-989a-4193-baf2-c0fb059d9f6d.png)

**Comment by mariusa** [comment] 2022-11-02 09:13
See also error in console message above, maybe it's related

**Comment by pranavrajs** [comment] 2022-11-10 02:36
@mariusa 

> Uncaught TypeError: Cannot read properties of undefined (reading 'split')
>    at a.setLocale (App.vue:139:1)
>    at App.vue:239:1

Can you please share if this happens every time you load the page? We cannot reproduce this on our end.

- The inbox your shared doesn't have working hours configured. Please configure one.
- If you don't want to use the working hours. Please make sure that you are online (busy, offline wouldn't work). The online status indicator would take 1-2 minutes to update even if you open a window. 

@Ghost108 You have to use the business hours option. If business hours are set, even if you have closed the web interface it would show you as online.

**Comment by Ghost108** [comment] 2022-11-10 05:54
@pranavrajs the opening hours are already set
every day => 08:00 AM - 08:00 PM

**Comment by mariusa** [comment] 2022-11-10 09:11
Thanks,

I've cleared all data in browser, and now it works. The  `a.setLocale (App.vue:139:1)` error is also gone.

**Comment by pranavrajs** [comment] 2022-11-10 23:55
Great! Closing this in that case.

**Closed by pranavrajs** 2022-11-10 23:55 UTC
Labels: need-more-info, live-chat
