### ISSUE TITLE
DB Sender address ignored

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#6204] opened 2023-01-08 22:13 UTC
**Describe the bug**

For some time now, we've had inbox addresses set in the database (inboxes - email_address) and these have been obeyed.

It appears in the last one or two updates this has been broken.

Now mails are once again sent with a From address of the inbox name and the address in `MAILER_SENDER_EMAIL` and the reply-to is set a domain in the `MAILER_INBOUND_EMAIL_DOMAIN`.

Our configuration has not changed in the last 6+ months, so this can only have been broken from an upgrade.

Please advise a way to restore this so that outbound mails come from the address set and not the inbound domain.

**Comment by pranavrajs** [comment] 2023-01-09 01:28
@iammattmartin This happens when the inbound emails are enabled in an account. Can you disable the feature? 

You can log in to `/super_admin` and select the account and disable the feature.

**Comment by iammattmartin** [comment] 2023-01-09 01:56
This helped but I guess the question why would the From address be changed for outgoing email when this only impacts inbound emails which should use the reply-to.

It would really be nice to be able to set a domain for the `MAILER_INBOUND_EMAIL_DOMAIN` variable per mailbox so that can work too as it seems you have to make a choice at the moment to have branded email domains or no incoming mail.

**Comment by fayazara** [comment] 2023-01-19 06:30
Closing as duplicate of - https://github.com/chatwoot/chatwoot/issues/6235

**Closed by fayazara** 2023-01-19 06:30 UTC
