### ISSUE TITLE
cwctl --upgrade Does Not Upgrade Chatwoot Instance

### ISSUE THREAD

**Issue by 503Dev** [chatwoot/chatwoot#5314] opened 2022-08-19 18:48 UTC
**Describe the bug**

Running Chatwoot on Ubuntu installed vi cwctl.  When running `sudo cwctl --upgrade` the process completes and no error is shown however the Chatwoot instance is not actually upgrded.

**To Reproduce**

1. Install Chatwoot 2.7.0 on Ubuntu via cwctl
2. Attempt upgrade via cwctl
3. Check Chatwoot version after cwctl completes

**Expected behavior**

Successful upgrade of Chatwoot or an error in the cwctl explaining why the upgrade failed.

**Server logs**

Output from `sudo cwctl --upgrade -d`
```
[5/5] Building fresh packages...
Done in 6.70s.
Everything's up-to-date. Nothing to do
Loading Installation config
```

The log ends there.

**Environment**

Self Hosted
Ubuntu 20.x
Installed via cwctl

**Comment by DmitryKrylovv** [comment] 2022-08-21 07:46
Confirm. ubuntu 20.04. Not updated

**Comment by vishnu-narayanan** [comment] 2022-08-22 08:34
@503Dev  @DmitryKrylovv  I am not able to reproduce this from my end. Please find the logs for upgrading a `v2.7.0` instance to the latest `v2.8.1` release using `cwctl`.

```
root@ip-172-31-66-145:/home/ubuntu# curl localhost:3000/api
{"version":"2.7.0","timestamp":"2022-08-22 08:03:00"}
```

```
root@ip-172-31-66-145:/home/ubuntu# cwctl --upgrade
.
.
.
-- foreign_key_exists?("dashboard_apps", "accounts")
   -> 0.0034s
-- remove_foreign_key("dashboard_apps", "accounts")
   -> 0.0047s
-- foreign_key_exists?("dashboard_apps", "users")
   -> 0.0037s
-- remove_foreign_key("dashboard_apps", "users")
   -> 0.0049s
-- foreign_key_exists?("macros", "users", {:column=>"created_by_id"})
   -> 0.0030s
-- remove_foreign_key("macros", "users", {:column=>"created_by_id"})
   -> 0.0039s
-- foreign_key_exists?("macros", "users", {:column=>"updated_by_id"})
   -> 0.0032s
-- remove_foreign_key("macros", "users", {:column=>"updated_by_id"})
   -> 0.0041s
-- remove_foreign_key("macros", "users", {:column=>"updated_by_id"})
   -> 0.0041s
I, [2022-08-22T08:21:25.357771 #64186]  INFO -- : [ActiveJob] Enqueued Migration::RemoveStaleNotificationsJob (Job ID: 75cacdf2-81db-454c-9ab6-1de2dc1e819a) to Sidekiq(scheduled_jobs)
== 20220809104508 RevertCascadingIndexes: migrated (0.2785s) ==================

Loading Installation config
```
```
root@ip-172-31-66-145:/home/ubuntu# curl localhost:3000/api
{"version":"2.8.1","timestamp":"2022-08-22 08:29:04"}
```

**Comment by vishnu-narayanan** [comment] 2022-08-22 08:39
@503Dev @DmitryKrylovv  Could you both share the output of the following?

1. `cwctl --version`
2. `curl localhost:3000/api`
3. `lsb_release -a`
4. `sudo -i -u chatwoot` && `cd chatwoot` 
4.1 `git branch`
4.2 `git log`
5. `sudo cwctl --upgrade`

**Comment by cadao7** [comment] 2022-08-22 11:31
Not Update for me.
All Log.

`sudo cwctl --upgrade -d
Upgrading Chatwoot to v2.8.1
M       app/javascript/dashboard/assets/scss/widgets/_login.scss
M       app/views/layouts/vueapp.html.erb
M       app/views/super_admin/devise/sessions/new.html.erb
M       public/brand-assets/logo.svg
M       public/brand-assets/logo_thumbnail.svg
M       public/favicon-16x16.png
M       public/favicon-32x32.png
M       public/favicon-512x512.png
M       public/favicon-96x96.png
M       public/favicon-badge-16x16.png
M       public/favicon-badge-32x32.png
M       public/favicon-badge-96x96.png
Already on 'master'
Your branch is behind 'origin/master' by 82 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
remote: Enumerating objects: 197, done.
remote: Counting objects: 100% (197/197), done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 197 (delta 131), reused 120 (delta 84), pack-reused 0
Receiving objects: 100% (197/197), 45.59 KiB | 11.40 MiB/s, done.
Resolving deltas: 100% (131/131), completed with 55 local objects.
From https://github.com/chatwoot/chatwoot
   d35aea03f..bdce36d6b chore/twillio-whatsapp-csv-file -> origin/chore/twillio-whatsapp-csv-file
   f33ff351c..9c6781472 develop                         -> origin/develop
 * [new branch]        feat/contact-identity-field     -> origin/feat/contact-identity-field
 * [new branch]        feat/delete-archive-article     -> origin/feat/delete-archive-article
   559a901fc..4e55ca51d feat/portal-delete              -> origin/feat/portal-delete
   9dc8cbb0a..dacbccca5 feat/portal-public              -> origin/feat/portal-public
   371b1be48..e4d863c00 feat/realtime-time-update       -> origin/feat/realtime-time-update
   e483f69a9..c7d803641 l10n_develop                    -> origin/l10n_develop
   e831daf2b..7c165fb68 vue3-migration                  -> origin/vue3-migration
Updating 628f40c2a..0cfe654b3
error: Your local changes to the following files would be overwritten by merge:
        app/javascript/dashboard/assets/scss/widgets/_login.scss
Please commit your changes or stash them before you merge.
Aborting
Already installed ruby-3.0.4.
To reinstall use:

    rvm reinstall ruby-3.0.4

Using /usr/local/rvm/gems/ruby-3.0.4
Warning: the running version of Bundler (2.2.33) is older than the version that created the lockfile (2.3.16). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.16`.
Using rake 13.0.6
Using concurrent-ruby 1.1.10
Using i18n 1.11.0
Using minitest 5.16.2
Using tzinfo 2.0.4
Using zeitwerk 2.6.0
Using activesupport 6.1.6.1
Using builder 3.2.4
Using erubi 1.10.0
Using racc 1.6.0
Using nokogiri 1.13.7 (x86_64-linux)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.18.0
Using rails-html-sanitizer 1.4.3
Using actionview 6.1.6.1
Using rack 2.2.4
Using rack-test 2.0.2
Using actionpack 6.1.6.1
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.5
Using actioncable 6.1.6.1
Using globalid 1.0.0
Using activejob 6.1.6.1
Using activemodel 6.1.6.1
Using activerecord 6.1.6.1
Using marcel 1.0.2
Using mini_mime 1.1.2
Using activestorage 6.1.6.1
Using mail 2.7.1
Using actionmailbox 6.1.6.1
Using actionmailer 6.1.6.1
Using actiontext 6.1.6.1
Using active_record_query_trace 1.8
Using activerecord-import 1.4.0
Using acts-as-taggable-on 9.0.1
Using public_suffix 4.0.7
Using addressable 2.8.0
Using method_source 1.0.0
Using thor 1.2.1
Using railties 6.1.6.1
Using momentjs-rails 2.29.1.1
Using datetime_picker_rails 0.0.7
Using jquery-rails 4.5.0
Using kaminari-core 1.2.2
Using kaminari-actionview 1.2.2
Using kaminari-activerecord 1.2.2
Using kaminari 1.2.2
Using ffi 1.15.5
Using sassc 2.4.0
Using sprockets 4.1.1
Using sprockets-rails 3.4.2
Using tilt 2.0.10
Using sassc-rails 2.1.2
Using selectize-rails 0.12.6
Using administrate 0.17.0
Using annotate 3.2.0
Using ast 2.4.2
Using attr_extras 6.2.5
Using aws-eventstream 1.2.0
Using aws-partitions 1.605.0
Using aws-sigv4 1.5.0
Using jmespath 1.6.1
Using aws-sdk-core 3.131.2
Using aws-sdk-kms 1.57.0
Using aws-sdk-s3 1.114.0
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using faraday-excon 1.1.0
Using faraday-httpclient 1.0.1
Using multipart-post 2.2.3
Using faraday-multipart 1.0.4
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-patron 1.0.0
Using faraday-rack 1.0.0
Using faraday-retry 1.0.3
Using ruby2_keywords 0.0.5
Using faraday 1.10.0
Using faraday_middleware 1.2.0
Using connection_pool 2.2.5
Using net-http-persistent 4.0.1
Using azure-storage-common 2.0.4
Using azure-storage-blob 2.0.3
Using multi_json 1.15.0
Using statsd-ruby 1.5.0
Using barnes 0.0.9
Using bcrypt 3.1.18
Using bindex 0.8.1
Using msgpack 1.5.3
Using bootsnap 1.12.0
Using brakeman 5.2.3
Using browser 5.3.1
Using uniform_notifier 1.16.0
Using bullet 7.0.2
Using bundler 2.2.33
Using bundler-audit 0.9.1
Using bundle-audit 0.1.0
Using byebug 11.1.3
Using climate_control 1.1.1
Using coderay 1.1.3
Using commonmarker 0.23.5
Using rexml 3.2.5
Using crack 0.4.5
Using cypress-on-rails 1.13.1
Using database_cleaner-core 2.0.1
Using database_cleaner-active_record 2.0.1
Using database_cleaner 2.0.1
Using debase-ruby_core_source 0.10.16
Using libddprof 0.6.0.1.0 (x86_64-linux)
Using libddwaf 1.3.0.2.0 (x86_64-linux)
Using ddtrace 1.2.0
Using declarative 0.0.20
Using orm_adapter 0.5.0
Using responders 3.0.1
Using warden 1.2.9
Using devise 4.8.1
Using devise-secure_password 2.0.1 from https://github.com/chatwoot/devise-secure_password
Using rails 6.1.6.1
Using devise_token_auth 1.2.0
Using diff-lcs 1.5.0
Using digest-crc 0.6.4
Using docile 1.4.0
Using unf_ext 0.0.8.2
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.7.6
Using dotenv-rails 2.7.6
Using down 5.3.1
Using regexp_parser 2.5.0
Using ecma-re-validator 0.4.0
Using email_reply_trimmer 0.1.13
Using et-orbi 1.2.7
Using execjs 2.8.1
Using mime-types-data 3.2022.0105
Using mime-types 3.4.1
Using multi_xml 0.6.0
Using httparty 0.20.0
Using facebook-messenger 2.0.1
Using factory_bot 6.2.1
Using factory_bot_rails 6.2.0
Using faker 2.21.0
Using jwt 2.4.1
Using memoist 0.16.2
Using os 1.1.4
Using signet 0.17.0
Using googleauth 1.2.0
Using fcm 1.0.8
Using flag_shih_tzu 0.3.23
Using foreman 0.87.2
Using raabro 1.4.0
Using fugit 1.5.3
Using google-protobuf 3.21.2 (x86_64-linux)
Using googleapis-common-protos-types 1.3.2
Using grpc 1.47.0 (x86_64-linux)
Using googleapis-common-protos 1.3.12
Using gapic-common 0.10.0
Using geocoder 1.8.0
Using gli 2.21.0
Using httpclient 2.8.3
Using trailblazer-option 0.1.2
Using uber 0.1.0
Using representable 3.2.0
Using retriable 3.1.2
Using webrick 1.7.0
Using google-apis-core 0.7.0
Using google-apis-iamcredentials_v1 0.13.0
Using google-apis-storage_v1 0.18.0
Using google-cloud-env 1.6.0
Using google-cloud-errors 1.2.0
Using google-cloud-core 1.6.0
Using google-cloud-location 0.2.0
Using google-cloud-dialogflow-v2 0.17.0
Using google-cloud-dialogflow 1.5.0
Using google-cloud-storage 1.37.0
Using groupdate 6.1.0
Using haikunator 1.1.1
Using sexp_processor 4.16.1
Using ruby_parser 3.19.1
Using ruby2ruby 2.4.4
Using hairtrigger 0.2.25
Using hana 1.3.7
Using hashdiff 1.0.1
Using hashie 5.0.0
Using hkdf 0.3.0
Using html2text 0.2.1
Using http-accept 1.7.0
Using http-cookie 1.0.5
Using mini_magick 4.11.0
Using ruby-vips 2.1.4
Using image_processing 1.12.2
Using jbuilder 2.11.5
Using json 2.6.2
Using json_refs 0.1.7
Using uri_template 0.7.0
Using json_schemer 0.2.21
Using koala 3.2.0
Using launchy 2.5.0
Using letter_opener 1.8.1
Using line-bot-api 1.25.0
Using liquid 5.3.0
Using rb-fsevent 0.11.1
Using rb-inotify 0.10.1
Using listen 3.7.1
Using maxminddb 0.1.22
Using mock_redis 0.32.0
Using netrc 0.11.0
Using newrelic_rpm 8.9.0
Using oauth 0.5.10
Using parallel 1.22.1
Using parser 3.1.2.0
Using pg 1.4.1
Using pg_search 2.3.6
Using procore-sift 0.16.0
Using pry 0.14.1
Using pry-rails 0.3.9
Using puma 5.6.4
Using pundit 2.2.0
Using rack-attack 6.6.1
Using rack-cors 1.1.1
Using rack-proxy 0.7.2
Using rack-timeout 0.6.3
Using rainbow 3.1.1
Using redis 4.7.1
Using redis-namespace 1.8.2
Using rest-client 2.1.0
Using rspec-support 3.11.0
Using rspec-core 3.11.0
Using rspec-expectations 3.11.0
Using rspec-mocks 3.11.1
Using rspec-rails 5.0.3
Using rubocop-ast 1.19.1
Using ruby-progressbar 1.11.0
Using unicode-display_width 2.2.0
Using rubocop 1.31.2
Using rubocop-performance 1.14.2
Using rubocop-rails 2.15.2
Using rubocop-rspec 2.12.1
Using scout_apm 5.2.0
Using seed_dump 3.3.1
Using semantic_range 3.0.0
Using sentry-ruby-core 5.3.1
Using sentry-rails 5.3.1
Using sentry-ruby 5.3.1
Using sidekiq 6.4.2
Using sentry-sidekiq 5.3.1
Using shoulda-matchers 5.1.0
Using sidekiq-cron 1.6.0
Using simplecov-html 0.10.2
Using simplecov 0.17.1
Using slack-ruby-client 1.0.0
Using spring 2.1.1
Using spring-watcher-listen 2.0.1
Using squasher 0.6.2
Using telephone_number 1.4.16
Using time_diff 0.3.0
Using twilio-ruby 5.68.0
Using twitty 0.1.4
Using tzinfo-data 1.2022.1
Using uglifier 4.2.0
Using valid_email2 4.0.3
Using web-console 4.2.0
Using webmock 3.14.0
Using webpacker 5.4.3
Using webpush 1.1.0
Using wisper 2.0.0
Using working_hours 1.4.1
Bundle complete! 99 Gemfile dependencies, 268 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
warning " > foundation-sites@6.5.3" has unmet peer dependency "jquery@>=2.2.0".
warning " > foundation-sites@6.5.3" has unmet peer dependency "what-input@>=4.1.0".
warning " > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".
warning " > vue-easytable@2.5.5" has unmet peer dependency "lodash@^4.17.20".
warning " > vue-loader@15.9.6" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.9.6" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
warning " > vuex-router-sync@4.1.3" has incorrect peer dependency "vue-router@^2.0.0".
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components > react-syntax-highlighter@15.5.0" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
warning " > @storybook/vue@6.5.9" has unmet peer dependency "css-loader@*".
warning "@storybook/vue > ts-loader@8.2.0" has unmet peer dependency "typescript@*".
warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".
warning "eslint-plugin-storybook > @typescript-eslint/experimental-utils > @typescript-eslint/utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 44.39s.
Warning: the running version of Bundler (2.2.33) is older than the version that created the lockfile (2.3.16). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.16`.
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
warning " > foundation-sites@6.5.3" has unmet peer dependency "jquery@>=2.2.0".
warning " > foundation-sites@6.5.3" has unmet peer dependency "what-input@>=4.1.0".
warning " > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".
warning " > vue-easytable@2.5.5" has unmet peer dependency "lodash@^4.17.20".
warning " > vue-loader@15.9.6" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.9.6" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
warning " > vuex-router-sync@4.1.3" has incorrect peer dependency "vue-router@^2.0.0".
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components > react-syntax-highlighter@15.5.0" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
warning " > @storybook/vue@6.5.9" has unmet peer dependency "css-loader@*".
warning "@storybook/vue > ts-loader@8.2.0" has unmet peer dependency "typescript@*".
warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".
warning "eslint-plugin-storybook > @typescript-eslint/experimental-utils > @typescript-eslint/utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[5/5] Building fresh packages...
Done in 11.78s.
rake aborted!
Errno::EACCES: Permission denied @ apply2files - /home/chatwoot/chatwoot/tmp/cache/assets/sprockets/v4.0.0/eZ/eZYmgTnmUXph13cujGemdSCfuaKhTacbGF-69_SnQ6g.cache
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/cache/file_store.rb:72:in `get'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/cache.rb:223:in `get'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/cache.rb:90:in `fetch'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/base.rb:71:in `file_digest'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/unloaded_asset.rb:105:in `dependency_history_key'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/loader.rb:43:in `load'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/cached_environment.rb:44:in `block in load'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/cached_environment.rb:44:in `fetch'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/cached_environment.rb:44:in `load'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/base.rb:81:in `find_asset'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/base.rb:88:in `find_all_linked_assets'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/manifest.rb:125:in `each'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/manifest.rb:125:in `to_a'
/usr/local/rvm/gems/ruby-3.0.4/gems/sprockets-4.1.1/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/usr/local/rvm/gems/ruby-3.0.4/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
Loading Installation config`

**Comment by cadao7** [comment] 2022-08-22 11:42
> @503Dev @DmitryKrylovv Could you both share output of the following?
> 
> 1. `cwctl --version`
> 2. `curl localhost:3000/api`
> 3. `lsb_release -a`
> 4. `sudo -i -u chatwoot` && `cd chatwoot`
>    4.1 `git branch`
>    4.2 `git log`
> 5. `sudo cwctl --upgrade`
> 6. `curl localhost:3000/api`
> 7. `sudo -i -u chatwoot` && `cd chatwoot`
>    7.1 `git branch`
>    7.2 `git log`


cwctl --version 
cwctl v2.1.0 alpha build
---------------------------------------------------------------------------------------------
curl localhost:3000/api 
{"version":"2.7.0","timestamp":"2022-08-22 11:34:09"}
---------------------------------------------------------------------------------------------
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
---------------------------------------------------------------------------------------------
sudo -i -u chatwoot && cd chatwoot
---------------------------------------------------------------------------------------------
git branch 
fatal: not a git repository (or any of the parent directories): .git
---------------------------------------------------------------------------------------------
git log
fatal: not a git repository (or any of the parent directories): .git
---------------------------------------------------------------------------------------------
sudo cwctl --upgrade
https://github.com/chatwoot/chatwoot/issues/5314#issuecomment-1222226022
---------------------------------------------------------------------------------------------
curl localhost:3000/api
{"version":"2.7.0","timestamp":"2022-08-22 11:40:17"}
---------------------------------------------------------------------------------------------
sudo -i -u chatwoot && cd chatwoot
Sorry, user chatwoot is not allowed to execute '/bin/bash' as chatwoot on XXXXXXXX.contaboserver.net.
---------------------------------------------------------------------------------------------
git branch
fatal: not a git repository (or any of the parent directories): .git
---------------------------------------------------------------------------------------------
git log
fatal: not a git repository (or any of the parent directories): .git
---------------------------------------------------------------------------------------------

**Comment by pranavrajs** [comment] 2022-08-22 14:52
@cadao7 It seems like you have made some changes in the code. The upgrade commands won't work if there is a difference in the code. Please remove the changes and try again.

<img width="467" alt="Screenshot 2022-08-22 at 8 21 32 PM" src="https://user-images.githubusercontent.com/2246121/185951477-5046e712-75df-4343-b358-36bc24d4e60a.png">

**Comment by vishnu-narayanan** [comment] 2022-08-29 12:07
Please reopen if the issue persists.

**Closed by vishnu-narayanan** 2022-08-29 12:07 UTC
Labels: investigation, self-hosted
