### ISSUE TITLE
Macro: unable to add attachments

### ISSUE THREAD

**Issue by mattiamarras** [chatwoot/chatwoot#8113] opened 2023-10-15 16:22 UTC
### Describe the bug

I cannot ad attachments to macros.

In the console i read this error. How I can handle it?

Failed to load resource: the server responded with a status of 404 ()

![image](https://github.com/chatwoot/chatwoot/assets/62311149/06b806f6-5fb4-465a-8bd0-5586621e847c)

### To Reproduce

New macro
Add attachment

v3.1.1

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment] 2023-10-17 09:53
@mattiamarras I'm not able to reproduce the issue. Please see the screenshot below. It works fine. 
<img width="443" alt="Screenshot 2023-10-17 at 2 52 04 AM" src="https://github.com/chatwoot/chatwoot/assets/2246121/06cd89af-6a29-41f9-9020-9df891389a54">

**Comment by mattiamarras** [comment] 2023-10-17 10:21
Stil not working, it may depends on some server config?

Failed to load resource: the server responded with a status of 404 ()
/api/v1/accounts/1/automation_rules/attach_file:1

**Comment by mattiamarras** [comment] 2023-10-17 10:22
@pranavrajs There is some log to check?

**Comment by pranavrajs** [comment] 2023-10-18 20:37
@mattiamarras Did you change any code? 

Closing this here as we cannot reproduce this on our production instance. Please use the latest version 3.2.0 and if it is still an issue, please feel free to re-open the issue.

**Closed by pranavrajs** 2023-10-18 20:37 UTC
Labels: need-more-info, 🧄 feature/agent-ui

**Comment by mattiamarras** [comment] 2023-10-20 06:37
Updated to 3.2 and still having same problem. 
Could I check some logs to give more details?
The only thing i can see now is that in the Chrome Console there is this error:

Failed to load resource: the server responded with a status of 404 ()
xhr.js:184 
POST https://help.volty.it/api/v1/accounts/1/automation_rules/attach_file 404 (Not Found)
(anonymous) @ xhr.js:184

What I can do?

**Comment by mattiamarras** [comment] 2023-10-30 18:36
Problem solved: the version of ruby and node was not correct and upgrade with cwctl was failing without showing error. In the manual update process i found the errors and fixed them. Thanks for support.
