### ISSUE TITLE
Add other languages

### ISSUE THREAD

**Issue by egorsmkv** [chatwoot/chatwoot#415] opened 2020-01-10 14:49 UTC
I want to use your software on my websites but people on them don't speak English so I want to have the software in people's languages.

How can we add other localizations?

**Comment by pranavrajs** [comment] 2020-01-10 15:00
@egorsmkv We have already thought about this and have created the software with a view that we support multiple languages at a later time. If you see https://github.com/chatwoot/chatwoot/tree/develop/app/javascript/dashboard/i18n i18n folder. You could see the list of text we use in Chatwoot. If you can make a translation doc for the text in this folder in the language you want, that would be great!

**Comment by egorsmkv** [comment] 2020-01-10 17:07
So I need to create a folder as https://github.com/chatwoot/chatwoot/tree/develop/app/javascript/dashboard/i18n/locale/en for my targeted language and then also create a file here https://github.com/chatwoot/chatwoot/tree/develop/app/javascript/dashboard/i18n

Correct?

**Comment by egorsmkv** [comment] 2020-01-10 17:08
By the way, how to change a language or it's automatically will be changed?

**Comment by pranavrajs** [comment] 2020-01-10 17:21
> By the way, how to change a language or it's automatically will be changed?

@egorsmkv We will add settings to change the language in dashboard.

> So I need to create a folder as https://github.com/chatwoot/chatwoot/tree/develop/app/javascript/dashboard/i18n/locale/en for my targeted language and then also create a file here https://github.com/chatwoot/chatwoot/tree/develop/app/javascript/dashboard/i18n
Correct?

Yes, that is correct.

**Comment by egorsmkv** [comment] 2020-01-10 18:09
Okay, then add please this setting and any other language in order I have opportunity to test my translations.

**Comment by fr0der1c** [comment] 2020-03-01 09:56
@pranavrajs Will this be added to v1.3.0 release?

**Comment by sojan-official** [comment] 2020-03-01 14:21
@fr0der1c  we are still prioritizing the issues to be worked on v1.3.0 release. we will bump this to the top of the list.

**Comment by sojan-official** [comment] 2020-03-25 22:22
Closing this since its a duplicate of #307

**Closed by sojan-official** 2020-03-25 22:22 UTC

**Comment by sojan-official** [comment] 2020-04-06 18:54
@egorsmkv  @fr0der1c  We just released v1.3.0 which contains settings to change the chatwoot language.  There is a german translation added as an example.  If you guys could contribute by proofreading or adding another language that be awesome. 

Any feedback you have is welcome as well.
