### ISSUE TITLE
I don't see messages from different sources, but with the same user ID.

### ISSUE THREAD

**Issue by vorchvcube** [chatwoot/chatwoot#7776] opened 2023-08-21 12:16 UTC
### Describe the bug

I'm using a widget with user authentication on a website, passing the user ID. In the mobile application, I'm using ApiChannel, authenticating with the same user ID. However, messages from the chat in the mobile app aren't visible in the widget under the same user. I tried using the token from ApiChannel in WebWidget, but it didn't work. How can I synchronize messages for the same user between widgetApi and ApiChannel?

### To Reproduce

1. On the website, use the widget, authenticate, and pass the user ID.
2. In the application or on another website, use ApiChannel, authenticate, and pass the same user ID from the chat widget's contacts.
3. Messages from the same user are different in the widget and in ApiChannel.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment] 2023-08-24 03:44
@vorchvcube Can you please share the implementation of ID in website live chat and API channel? How do you pass this to Chatwoot? 

There are 3 fields we use to identify a user across platforms - `identifier`, `email_address` or `phone_number`. If any of these matches, we would combine the contacts. If you see distinct contacts, then it would most likely be an issue with the way the SDK is initialized and the fields are passed.

Please share more information to debug this.

**Comment by vorchvcube** [comment] 2023-08-24 06:45
![image](https://github.com/chatwoot/chatwoot/assets/17680292/7cb6fe62-82ad-41aa-b35e-407c8271570c)
Yes, we use all 3 fields for identification, but chats are not being merged.

**Comment by vorchvcube** [comment] 2023-08-24 06:47
Contacts are being merged, but the messages differ in the API channel and in the WidgetChannel.

**Comment by vorchvcube** [comment] 2023-08-24 06:49
Is this not provided for in your system? Or should the messages in the chats still be the same if identified correctly?

**Comment by pranavrajs** [comment] 2023-08-24 11:37
@vorchvcube The conversations would not be merged if that's what you are looking for. You will see the other conversations under the previous conversations tab. 

<img width="342" alt="Screenshot 2023-08-24 at 5 07 07 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/bdc7ae14-ca42-4722-a012-aee79a70947f">

**Comment by vorchvcube** [comment] 2023-08-24 14:18
ok.

**Comment by vorchvcube** [comment] 2023-08-24 14:33
![image](https://github.com/chatwoot/chatwoot/assets/17680292/d921ce83-e442-4ab0-95ef-876f55b3e45c)
"It turns out that way for us, and in the admin panel, if a message is sent from a mobile device on the client side, it doesn't appear in the widget."

**Comment by sojan-official** [comment] 2023-08-24 23:43
@vorchvcube  Chatwoot doesn't support this at the moment. The widget will only pull in conversations created in website channel, not from other channels, even if the conversation is associated with the same contact.

**Comment by pranavrajs** [comment] 2023-08-25 04:40
Closing this here for now as the issue is not a bug, but a feature we don't support.

**Closed by pranavrajs** 2023-08-25 04:40 UTC
Labels: need-more-info, 🍛 channel/api, 🐳 channel/live-chat
