### ISSUE TITLE
Manual refresh required to update messages in chatwoot

### ISSUE THREAD

**Issue by jjmmbb** [chatwoot/chatwoot#9823] opened 2024-07-23 15:39 UTC
### Describe the bug

I am always have to manually refresh the browser to get messages updates or new messages in chatwoot.

I am using version: 3.11.0

### To Reproduce

Just get it running using EvoAPI and then send a message. To reflect any update in chatwoot I have to manually refresh the browser.

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Linux

### Browser and version

Edge 126.0.2592.102

**Comment by vishnu-narayanan** [comment] 2024-07-25 14:50
Do you see any errors in your browser console? If so, could you please share them?

Most probably, this is related to WebSockets. Please check if your webserver have websocket support enabled.

**Comment by jjmmbb** [comment] 2024-07-28 19:52
No errors.

**Comment by vishnu-narayanan** [comment] 2024-07-30 10:53
@jjmmbb could you share a screencast that shows the problem? Make sure the browser console is open before you start recording.

**Comment by jjmmbb** [comment] 2024-08-08 22:11
I have found the issue. It was related to FORCE_SSL when using in conjunction with traefik. You must change FORCE_SSL to false.

**Comment by sojan-official** [comment] 2024-08-08 22:55
closing as the issue is resolved

**Closed by sojan-official** 2024-08-08 22:55 UTC
Labels: need-more-info, self-hosted
