### ISSUE TITLE
bug: No new chat is made after resolving

### ISSUE THREAD

**Issue by ChrisvanChip** [chatwoot/chatwoot#4131] opened 2022-03-08 11:49 UTC
I have disabled "Allow messages after conversation resolved". Recently, it seems to just clean the chat history of the customer:

---

![image](https://user-images.githubusercontent.com/31969757/156879815-8ccf63bd-c3cc-4a38-98ea-0f65e891b4b7.png)
_The conversation history for the agent_

---

![image](https://user-images.githubusercontent.com/31969757/156879745-93139cbc-c59d-494f-865a-8486a756e10c.png)
_The conversation bubbles for the customer, even though those messages are from an earlier chat that was resolved._

---

![image](https://user-images.githubusercontent.com/31969757/156879784-66660cd8-26e5-462b-aa0c-f8fe34ab4cf7.png)
_The chat widget for the customer, only seeing the last chat._

---

I would like to have a new chat after the inquiry has been resolved (like the image below). It's really inconvenient right now.

![image](https://user-images.githubusercontent.com/31969757/156879923-84cf8d35-1991-481a-bf32-dfb19cb3779f.png)

It worked properly when a pre-chat form appeared with only one message field.

_Originally posted in https://github.com/chatwoot/chatwoot/issues/4102#issuecomment-1059741293_

**Comment by pranavrajs** [comment] 2022-03-08 13:39
@ChrisvanChip Which version are you on? This should be fixed by https://github.com/chatwoot/chatwoot/pull/4102

**Comment by pranavrajs** [comment] 2022-03-10 03:57
@ChrisvanChip Closing this as the issue is solved already, will reopen if it still persists after the next release.

**Closed by pranavrajs** 2022-03-10 03:57 UTC
