### ISSUE TITLE
postgres:5432 - no response Self hosted Docker

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#1704] opened 2021-01-29 15:20 UTC
**Describe the bug**

Running ```docker-compose run --rm rails bundle exec rails db:reset``` fails with the following logs.

```
echo 'Waiting for postgres to become ready....'
Waiting for postgres to become ready....
+ docker/entrypoints/helpers/pg_database_url.sh
+ export 'POSTGRES_PORT=5432'
+ PG_READY='pg_isready -h postgres -p 5432 -U postgres'
+ pg_isready -h postgres -p 5432 -U postgres
postgres:5432 - no response
+ sleep 2
+ pg_isready -h postgres -p 5432 -U postgres
postgres:5432 - no response
+ sleep 2
+ pg_isready -h postgres -p 5432 -U postgres
postgres:5432 - no response
+ sleep 2
+ pg_isready -h postgres -p 5432 -U postgres
postgres:5432 - no response
+ sleep 2

```
**To Reproduce**

1. Follow the steps here in a a fresh folder: https://www.chatwoot.com/docs/installation-guide-docker

**Expected behavior**

The app should be accessible at localhost:3000

**Screenshots**

NA
**Browser logs**
NA

**Server logs**

```
Creating chatwoot_mailhog_1  ... done
Creating chatwoot_redis_1    ... done
Creating chatwoot_postgres_1 ... done
Creating chatwoot_webpack_1  ... done
Creating chatwoot_sidekiq_1  ... done
Creating chatwoot_rails_run  ... done
+ rm -rf /app/tmp/pids/server.pid
+ rm -rf '/app/tmp/cache/*'
+ echo 'Waiting for postgres to become ready....'
Waiting for postgres to become ready....
+ docker/entrypoints/helpers/pg_database_url.sh
+ export 'POSTGRES_PORT=5432'
+ PG_READY='pg_isready -h postgres -p 5432 -U postgres'
+ pg_isready -h postgres -p 5432 -U postgres
postgres:5432 - no response
+ sleep 2
+ pg_isready -h postgres -p 5432 -U postgres
postgres:5432 - no response
+ sleep 2
+ pg_isready -h postgres -p 5432 -U postgres
postgres:5432 - no response
+ sleep 2
+ pg_isready -h postgres -p 5432 -U postgres
postgres:5432 - no response
+ sleep 2
```
**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku): Self hosted with Docker

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22]: develop branch

**Smartphone (please complete the following information):**

**Additional context**

.env file
```
# Used to verify the integrity of signed cookies. so ensure a secure value is set
SECRET_KEY_BASE=replace_with_lengthy_secure_hex

# Replace with the URL you are planning to use for your app
FRONTEND_URL=http://0.0.0.0:3000

# If the variable is set, all non-authenticated pages would fallback to the default locale.
# Whenever a new account is created, the default language will be DEFAULT_LOCALE instead of en
# DEFAULT_LOCALE=en

# If you plan to use CDN for your assets, set Asset CDN Host
ASSET_CDN_HOST=

# Force all access to the app over SSL, default is set to false
FORCE_SSL=false

# This lets you control new sign ups on your chatwoot installation
# true : default option, allows sign ups
# false : disables all the end points related to sign ups
# api_only: disables the UI for signup, but you can create sign ups via the account apis
ENABLE_ACCOUNT_SIGNUP=false

# Redis config
REDIS_URL=redis://redis:6379
# If you are using docker-compose, set this variable's value to be any string,
# which will be the password for the redis service running inside the docker-compose
# to make it secure
REDIS_PASSWORD=123456789
# Redis Sentinel can be used by passing list of sentinel host and ports e,g. sentinel_host1:port1,sentinel_host2:port2
REDIS_SENTINELS=
# Redis sentinel master name is required when using sentinel, default value is "mymaster".
# You can find list of master using "SENTINEL masters" command
REDIS_SENTINEL_MASTER_NAME=

# Postgres Database config variables
POSTGRES_HOST=postgres
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=postgres
RAILS_ENV=development
RAILS_MAX_THREADS=5

# Mail outgoing
MAILER_SENDER_EMAIL=accounts@chatwoot.com
SMTP_PORT=1025
SMTP_DOMAIN=chatwoot.com
# if you are running docker-compose, set SMTP_ADDRESS value as "mailhog",
# else set the value as "localhost"
SMTP_ADDRESS=mailhog
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_AUTHENTICATION=
SMTP_ENABLE_STARTTLS_AUTO=

# Mail Incoming
# This is the domain set for the reply emails when conversation continuity is enabled
MAILER_INBOUND_EMAIL_DOMAIN=
# Set this to appropriate ingress channel with regards to incoming emails
# Possible values are :
# relay for Exim, Postfix, Qmail
# mailgun for Mailgun
# mandrill for Mandrill
# postmark for Postmark
# sendgrid for Sendgrid
RAILS_INBOUND_EMAIL_SERVICE=
# Use one of the following based on the email ingress service
# Ref: https://edgeguides.rubyonrails.org/action_mailbox_basics.html
RAILS_INBOUND_EMAIL_PASSWORD=
MAILGUN_INGRESS_SIGNING_KEY=
MANDRILL_INGRESS_API_KEY=

# Storage
ACTIVE_STORAGE_SERVICE=local

# Amazon S3
# documentation: https://www.chatwoot.com/docs/configuring-s3-bucket-as-cloud-storage
S3_BUCKET_NAME=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=

# Sentry
SENTRY_DSN=

# Log settings
# Disable if you want to write logs to a file
RAILS_LOG_TO_STDOUT=true
LOG_LEVEL=info
LOG_SIZE=500

### This environment variables are only required if you are setting up social media channels

# Facebook
# documentation: https://www.chatwoot.com/docs/facebook-setup
FB_VERIFY_TOKEN=
FB_APP_SECRET=
FB_APP_ID=

# Twitter
# documentation: https://www.chatwoot.com/docs/twitter-app-setup
TWITTER_APP_ID=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_ENVIRONMENT=

#slack integration
SLACK_CLIENT_ID=
SLACK_CLIENT_SECRET=

### Change this env variable only if you are using a custom build mobile app
## Mobile app env variables
IOS_APP_ID=6C953F3RX2.com.chatwoot.app


### Smart App Banner
# https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html
# You can find your app-id in https://itunesconnect.apple.com
#IOS_APP_IDENTIFIER=1495796682

## Push Notification
## generate a new key value here : https://d3v.one/vapid-key-generator/
# VAPID_PUBLIC_KEY=
# VAPID_PRIVATE_KEY=
#
# for mobile apps
# FCM_SERVER_KEY=

## Bot Customizations
USE_INBOX_AVATAR_FOR_BOT=true



## IP look up configuration
## ref https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md
## works only on accounts with ip look up feature enabled
# IP_LOOKUP_SERVICE=geoip2
# maxmindb api key to use geoip2 service
# IP_LOOKUP_API_KEY=

## Development Only Config
# if you want to use letter_opener for local emails
# LETTER_OPENER=true

```

**Comment by sojan-official** [comment] 2021-02-09 12:52
@srameshr  could you check whether the docker container for Postgres is running ?

**Comment by agustinrudas** [comment] 2021-02-13 15:10
This happend to me when i setup a wrong password
The password need to be set in (.env) file and (docker-compose.yaml) file too.
sometimes the postgress instance is already running. and other postgress instance is trying to be created at the same time.
i suggest:
docker-compose down (and also check if all docker instance of this project are stopped and deleted.)
docker-compose build
docker-compose run --rm rails bundle exec rails db:reset
docker-compose up

Note:
I use a latest repo of postgress. in docker-compose.yaml
  postgres:
    image: postgres:**latest**
    restart: always
This is not suggested in docs but maybe it can help you.

**Comment by kumarmj** [comment] 2021-05-03 12:53
Hey what are we doing to address this issue in documentation?
If anybody have idea, how situation can be improved. I can help code it, could be good first issue for me.

**Comment by pranavrajs** [comment] 2021-05-04 08:16
@kumarmj I didn't understand the context. Could you please explain what you meant by "what are we doing to address this issue in documentation?".

**Comment by jusce17** [comment] 2021-11-25 08:33
This issue is almost a year old, and update on it ?

TIA

**Comment by vishnu-narayanan** [comment] 2021-11-25 08:43
@jusce17 Did you encounter this issue recently?

**Comment by jusce17** [comment] 2021-11-25 08:51
Yes, 2 days ago and I've been struggling with it until now

**Comment by jusce17** [comment] 2021-11-25 11:27
Hey @vishnu-narayanan 

I dont think it is an actual bug.

As I am running on MAC I edited my .env file and changed the `POSTGRES_HOST` from:

```
# Postgres Database config variables
POSTGRES_HOST=localhost
POSTGRES_USERNAME=DUMMYUSER
POSTGRES_PASSWORD=DUMMYPASSWORD
RAILS_ENV=development
RAILS_MAX_THREADS=5
```

to

```
# Postgres Database config variables
POSTGRES_HOST=host.docker.internal
POSTGRES_USERNAME=DUMMYUSER
POSTGRES_PASSWORD=DUMMYPASSWORD
RAILS_ENV=development
RAILS_MAX_THREADS=5
```
I have just started using chatwoot and I am not sure how mature it is for production kicks

**Comment by vishnu-narayanan** [comment] 2021-11-25 14:02
Is it working for you with `POSTGRES_HOST=host.docker.internal`?

It should be working with `localhost` btw. Could you see if you can access the `postgres` container locally?

**Comment by jusce17** [comment] 2021-11-25 14:30
@vishnu-narayanan  would you please guid me on how to do it ?
If by accessing locally you mean ` docker exec -it chatwoot-postgres-1 bash` , I can access it with no  problem

**Comment by vishnu-narayanan** [comment] 2021-11-25 15:11
No. Since you are having an issue with accessing postgres against the `localhost`, try installing the `psql` cli locally and see if you can access the postgres db container.

`psql -h localhost -p 5432 -U postgres`

**Comment by jusce17** [comment] 2021-11-25 15:31
@vishnu-narayanan 
I changed my `POSTGRES_HOST` to localhost

just running `psql -h localhost -p 5432 -U postgres` gives me :
```
port 5432 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?
```
if I spin up the container first `docker-compose up -d `

it asks me to login and works fine 
```

Password for user postgres: 
```

Changing my  env to `POSTGRES_HOST=host.docker.internal` again and ran `psql -h localhost -p 5432 -U postgres` 
it also asks me to login and works fine

**Comment by jusce17** [comment] 2021-11-25 15:31
I can access the container, but it looks like, the other containers cannot access it

**Comment by sojan-official** [comment] 2021-12-15 13:50
@vishnu-narayanan  anything we can do to help here?

**Comment by vishnu-narayanan** [comment] 2021-12-15 15:15
@sojan-official I cannot reproduce the issue from my end.

**Comment by sojan-official** [comment] 2021-12-16 19:34
@jusce17  are you still facing the issue ?

**Comment by lpadula** [comment] 2022-01-26 22:32
same problem here! cant connect to postgres

**Comment by sojan-official** [comment] 2022-03-01 15:19
closing in favor of: https://github.com/chatwoot/chatwoot/issues/3233

**Closed by sojan-official** 2022-03-01 15:19 UTC
Labels: bug

**Comment by Vthechamp22** [comment] 2022-04-26 05:48
> `docker-compose up -d `

I'm facing the same issue here.

**Comment by p1slave** [comment] 2022-07-08 05:42
Same problem here. I can access postgre service from inside the postgre container and also from the host but the rails container seems to have trouble accessing the host port (I set it to 5433) that is bonded to the postgre service in the container.

**Comment by sojan-official** [comment] 2022-07-08 08:43
> > `docker-compose up -d `
> 
> I'm facing the same issue here. I've followed the exact steps as mentioned in the docker chatwoot production guide, and whenever i try to prepare the database docker gets stuck at pg_isready. Apparently other containers are unable to access this postgres server.
> 
> @sojan-official if you have any example env file (with values) for local development and the docker installation steps, please do share them with me.

you can follow https://www.chatwoot.com/docs/contributing-guide/environment-setup/docker

**Comment by RodolfoMonge** [comment] 2022-07-27 10:21
Same issue.

docker-compose run --rm rails bundle exec rails db:chatwoot_prepare
....
+ pg_isready -h localhost -p 5432 -U postgres
localhost:5432 - no response
+ sleep 2

Unable to prepare/migrate Postgres DB.

From my local host, I have access to postgres DB:
root@localhost:/software/chatwoot# psql -h localhost -p 5432 -U postgres
Password for user postgres:
psql (14.4 (Ubuntu 14.4-0ubuntu0.22.04.1), server 12.11 (Debian 12.11-1.pgdg110+1))
Type "help" for help.

postgres=#
postgres=#

But rails container doesn't have access to db.

**Comment by sojan-official** [comment] 2022-07-28 09:50
@RodolfoMonge Could you link the documentation page you are following for the setup?

**Comment by RodolfoMonge** [comment] 2022-07-28 13:23
Hi.
Thanks for your answer.
I was finally able to configure.
The problem was that I put localhost in the POSTGRES_HOSTNAME variable, when the correct setting is POSTGRES_HOSTNAME=postgres (since that is the name of the container that has the database).

Documentation followed for configuration:
Docker Chatwoot Production deployment guide | Chatwoot


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Docker Chatwoot Production deployment guide | Chatwoot

Pre-requisites
 |

 |

 |



Now I have another issue:
I have to manually refresh the browser for the messages to appear.
My scenario:OS:Ubuntu 22.04Docker version 20.10.17, build 100c701Image: chatwoot/chatwoot:latestWeb Server: Apache/2.4.52 (Ubuntu) for Reverse Proxy
Today I will try Nginx, as a reverse proxy, as indicated in the configuration guide.

Best regards.

Rodolfo Monge 

    El jueves, 28 de julio de 2022 03:50:49 a. m. CST, Sojan Jose ***@***.***> escribió:  
 
 


@RodolfoMonge Could you link the documentation page you are following for the setup?
