### ISSUE TITLE
Access Token shows 502 Bad Gateway error after configuring Platform Apps

### ISSUE THREAD

**Issue by clarcksp** [chatwoot/chatwoot#7558] opened 2023-07-19 22:58 UTC
### Describe the bug

After creating a "Platform Apps" for testing and accessing the Access Tokens menu, it started showing the error on the page "502 Bad Gateway"
In the front log I simply get a 200 OK from the page.
But if I try to enter some token numbering through the address bar: (Ex. https://chatwoot/super_admin/access_tokens/1) It displays an error page and I get a 500 internal error in the log. But only if the token I want to access is a super admin user, any other user information page is presented.

### To Reproduce

1. Create a Platform Apps
2. Access the Access Tokens menu

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20.04

### Additional context

Log Error:

```
Jul 19 22:50:28 [222855]: I, [2023-07-19T22:50:28.710228 #222855]  INFO -- : source=rack-timeout id=8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca timeout=15000ms state=ready
Jul 19 22:50:28 [222855]: I, [2023-07-19T22:50:28.710596 #222855]  INFO -- : [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca] Started GET "/super_admin/access_tokens/1" for 45.168.65.23 at 2023-07-19 22:50:28 +0000
Jul 19 22:50:28 [222855]: I, [2023-07-19T22:50:28.712985 #222855]  INFO -- : [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca] Processing by SuperAdmin::AccessTokensController#show as HTML
Jul 19 22:50:28 [222855]: I, [2023-07-19T22:50:28.713047 #222855]  INFO -- : [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]   Parameters: {"id"=>"1"}
Jul 19 22:50:28 [222855]: I, [2023-07-19T22:50:28.720735 #222855]  INFO -- : [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]   Rendered /usr/local/rvm/gems/ruby-3.2.2/gems/administrate-0.18.0/app/views/administrate/application/show.html.erb within layouts/super_admin/application (Duration: 3.5ms | Allocations: 2996)
Jul 19 22:50:28 [222855]: I, [2023-07-19T22:50:28.720827 #222855]  INFO -- : [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]   Rendered layout layouts/super_admin/application.html.erb (Duration: 3.7ms | Allocations: 3021)
Jul 19 22:50:28 [222855]: I, [2023-07-19T22:50:28.720998 #222855]  INFO -- : [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca] Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.9ms | Allocations: 4767)
Jul 19 22:50:28 [222855]: F, [2023-07-19T22:50:28.722081 #222855] FATAL -- : [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]
Jul 19 22:50:28 [222855]: [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca] ActionView::Template::Error (uninitialized constant SuperAdminDashboard):
Jul 19 22:50:28 [222855]: [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]     23:       [namespace, field.data],
Jul 19 22:50:28 [222855]: [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]     24:     ) %>
Jul 19 22:50:28 [222855]: [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]     25:   <% else %>
Jul 19 22:50:28 [222855]: [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]     26:     <%= field.display_associated_resource %>
Jul 19 22:50:28 [222855]: [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]     27:   <% end %>
Jul 19 22:50:28 [222855]: [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]     28: <% end %>
Jul 19 22:50:28 [222855]: [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca]
Jul 19 22:50:28 [222855]: [8c68056d-5f5c-42e4-abf4-eb6e4a9bbdca] app/views/fields/polymorphic/_show.html.erb:26`
```

**Comment by Double-Click-ERP** [comment] 2023-07-24 08:43
Hello ,
Try this #7333

**Comment by clarcksp** [comment] 2023-07-24 19:49
> Hello , Try this #7333

Hello, thanks for the feedback.
In my chatwoot nginx file there is no proxy_buffering option.
I changed the proxy_pass option to the address http://127.0.0.1:3000;
But the problem persists.

**Comment by clarcksp** [comment] 2023-07-24 20:01
Everything indicates that the problem is in the display of the AgentBot page when I have a user with super_admin permissions
Because if I try to access the user profile page inside the agentbot:
https://<chatroot>/super_admin/access_tokens/<number> and this user is not a super_admin the page is displayed

**Comment by nikparmar** [comment] 2023-07-30 05:56
For me, adding this helped to the nginx config

```
proxy_buffer_size          128k;
proxy_buffers              4 256k;
proxy_busy_buffers_size    256k;
```

**Comment by pranavrajs** [comment] 2023-08-15 20:01
@clarcksp I cannot reproduce it on my end. Can you please share a screencast of the action you are doing?

**Comment by pedrofnts** [comment] 2023-09-28 20:35
> @clarcksp I cannot reproduce it on my end. Can you please share a screencast of the action you are doing?

he's trying to access "Access Tokens" in Super Admin. The same is happening to me in a two VPS with more than 10 agents.

proxy_buffer solutions didn't work for me.

**Comment by pedrofnts** [comment] 2023-09-28 20:42
<img width="1474" alt="Captura de Tela 2023-09-28 às 17 41 40" src="https://github.com/chatwoot/chatwoot/assets/63073772/6c96c260-f35a-4390-8aa5-604aff6b0c3b">

I've justed deleted some agents and now I'm able to see Access Tokens page.

**Comment by pranavrajs** [comment] 2023-10-24 19:54
Closing this here for now, as the issue seems to be fixed by deleting orphan records.

**Closed by pranavrajs** 2023-10-24 19:54 UTC
Labels: need-more-info, 👩‍💻 development-chores
