### ISSUE TITLE
Line Break in Welcome Message

### ISSUE THREAD

**Issue by converso-chat** [chatwoot/chatwoot#1350] opened 2020-10-19 13:34 UTC
Hello. The welcome message cannot be placed with a line break? I need to insert a small menu to call our chatbot

Thanks

**Comment by pranavrajs** [comment] 2020-10-23 07:27
@converso-chat Can you share a screenshot or a mockup with the intended behaviour?

**Comment by converso-chat** [comment] 2020-10-30 07:29
Hello, 
I have no image, I already exclude it. But is like that:

"Hello, this is the first line </br>
And this is the second line </br>
Three lines "

Understood?

Thanks

**Comment by sojan-official** [comment] 2022-01-21 03:39
closing in favor of https://github.com/chatwoot/chatwoot/issues/1241

**Closed by sojan-official** 2022-01-21 03:39 UTC
Labels: need-more-info
