### ISSUE TITLE
Bug when editing words

### ISSUE THREAD

**Issue by GyR4uk** [chatwoot/chatwoot#5716] opened 2022-10-23 12:14 UTC
Bug when editing words

[Запись экрана от 23.10.2022 15:13:07.webm](https://user-images.githubusercontent.com/35705596/197391480-bbdf71ce-3567-4f6e-9b06-61c4190dfcec.webm)

**Comment by pranavrajs** [comment] 2022-10-24 17:45
Thanks for reporting the issue. Closing this as this is a duplicate of https://github.com/chatwoot/chatwoot/issues/5622

**Closed** 2022-10-24 17:45 UTC
