### ISSUE TITLE
Chatwoot self-hosted getting very slow with 10~15 users

### ISSUE THREAD

**Issue by fabriciorissetto** [chatwoot/chatwoot#3425] opened 2021-11-19 16:59 UTC
**Describe the bug**

Not sure it's a bug, I didn't find Chatwoot benchamark reports to compare with. But we are currently facing performance issues on chatwoot-web instance with just about 10~15 active users and 3k tickets in the database. Simple requests like `conversations/{id}/update_last_seen` starts taking too log (about 3+ seconds) to complete. When we look to the resources in our machine it seems to be OK (a lot of memory and cpu available all the time).

**Screenshots**
Datadog APM Metrics for the chatwoot-web instance:
![image](https://user-images.githubusercontent.com/1520059/142653191-34677ba6-af29-4ecf-b800-8f4cbde92251.png)

In this pod the memory at the time of the above metrics were:

![image](https://user-images.githubusercontent.com/1520059/142653780-df0b53a5-c62a-4abb-bd03-b7ebbaac627b.png)

**Environment**

We are using the Chatwoot self-hosted on EKS containers at AWS. The pod which seems to be bottlenecking is the web instance, the slowest and more called request we could find was the `conversations/{id}/update_last_seen`. All pods (web, worker) have 8GB RAM / 2CPU.

Our database is a `postgres` instance (version 12.7) on RDS with the following settings:

Model | Core Count | vCPU* | Memory (GiB) | Storage | Dedicated EBS Bandwidth (Mbps) | Network Performance (Gbps)
-- | -- | -- | -- | -- | -- | --
db.m5.large | 1 | 2 | 8 | EBS-only | Up to 4,750 | Up to 10

Single requests to database seems to be working fine. The most slow database request at the time took around 900ms~

**Additional context**

After commenting this lines we completely solved the problem:
![image](https://user-images.githubusercontent.com/1520059/142653428-2efbdde8-1378-45b9-89ab-d7eb7edfcfc5.png)

But the downside is we don't have this information anymore, and all conversations in the frontend are now "unread" (bold style) forever while we don't put the code back.

**Comment by pranavrajs** [comment] 2021-11-19 17:36
@fabriciorissetto Thanks for the details. What version of Chatwoot are you running? It is quite interesting to see 3k `update_last_seen` calls for 10-15 users in ~50 minutes. 

Would you be able to provide some more details for the questions below?

1. How many conversations do you handle per day (per agent)? 
2. Would it be possible for you to update the method `update_last_seen` with the following option?

```rb
def update_last_seen
  @conversation.update_column(:agent_last_seen_at, DateTime.now.utc)
  @conversation.update_column(:assignee_last_seen_at,  DateTime.now.utc) if assignee?
end
```

**Comment by fabriciorissetto** [comment] 2021-11-19 22:08
Thanks for your quick response @pranavrajs. Our fork was made from [this](https://github.com/cloudhumans/cloudchat/commit/40d0b2faf32dd7f66a65469f6de24144af4a2717) version.

The number of calls for the `update_last_seen` endpoint was a surprise for us as well. Our number of conversations/day is quite low, around 450. We have 20 agents registered, usually 10~ of them active simultaneously. Trying to have a fast response-SLA, is very common they all open the same ticket when it arrives (by API) and trying to assign to them and reply ASAP.

## Adding some more context 
When ordering the requests by quantity (on that time span I shared above), the `update_last_seen` has a huge difference above the second most called endpoint:
 
![image](https://user-images.githubusercontent.com/1520059/142675666-98d90db8-55f2-49be-98b5-1dc6a99c5c70.png)

Tracing this specific endpoint we can see a lot of calls during its internal execution (green spans are database calls):
![image](https://user-images.githubusercontent.com/1520059/142679842-d5d17b84-717e-49f8-8a53-24f88f6d9fc9.png)

# After changing the code as you suggested (using the `update_column`):

![image](https://user-images.githubusercontent.com/1520059/142696424-7a9240de-e0fe-48db-a46b-643802992234.png)

It seems it decreased the amount of initial database calls to 3:
* `UPDATE conversations SET agent_last_seen_at = ? WHERE conversations . id = ?`
* `SELECT users . * FROM users WHERE users . id = ? LIMIT ?` (not sure where this came from, it may be something related to the way the APM is configured, idk)
* `UPDATE conversations SET assignee_last_seen_at = ? WHERE conversations . id = ?`

There were no more performance issues so far since this deploy, so it may have solved the issue! But the deploy was made close tho EOD, so I will let this version run during entire Monday to ensure it was fixed. I'll inform you here and if it really fixed the issue we can open a PR to your branch :pray: Thank you so far @pranavrajs and congratulations for this project!

**Comment by tejaswinichile** [comment] 2021-11-20 02:08
@pranavrajs I was thinking that we can have this update in the background too. 
cc @sojan-official

**Comment by pranavrajs** [comment] 2021-11-20 04:15
@fabriciorissetto Thanks for the detailed information. Let us know how it goes.

@tejaswinichile This was my first thought, but I don't think the problem is with the update query. My understanding is that it might be the problem with the callbacks we execute after a conversation attribute is updated. This particular query doesn't have any associated side effect. `update_columns` is enough in this case so that these callbacks are not executed. If that fix is working then we can think about moving all the after_commit hooks on a conversation to a worker.

**Comment by rahulmr** [comment] 2021-11-21 10:20
@pranavrajs can we implement this is our self hosted server as well seems like good change, does it has any side effects?

**Comment by fabriciorissetto** [comment] 2021-11-23 12:42
Hello guys, updating you here: besides the suggested change has significantly improved that endpoint performance, it's still being called a lot and we disabled it again. We will investigate it further along these week. It seems to be an issue in the frontend, maybe some stage management issue on vue.js. I need to consider it might be related to a set of (really) small changes we did in the frontend as well, so again, I'll inform you here as long as I find some new information.

Thank you so far guys.

**Comment by sojan-official** [comment] 2021-11-23 13:05
@fabriciorissetto  thanks for reporting. Will wait back for your findings. 

@rahulmr  We will bring the change to develop as a fix once we hear back from fabricio along with any other changes if required.

**Comment by fabriciorissetto** [comment] 2021-11-26 21:15
Hello guys, we were able to find the problem. Here is a [recording](https://www.loom.com/share/2210c3be79284a519a72be5f8f4a9fe5) showing how to simulate the problem. 

This chatwoot instance is a sandbox environment we use sometimes for testing (is not our production version). It was deployed about a month ago using the button "Deploy to Heroku".

Our engineer who found the problem, @pedrohenriquepires, will shere here more details about the problem and how he was able to fix it. It's probably not the end-state solution, but it completely solved the performance problem.

**Comment by pedrohenriquepires** [comment] 2021-11-26 21:36
Hello folks, 

As you can see in the @fabriciorissetto recording, the problem is at the `scrollToMessage` event listener, that is created on the `MessagesView` component. 

![image](https://user-images.githubusercontent.com/6934800/143655949-a713f461-58c3-4dfb-b176-04769d0055f5.png)

This component never calls the `unmounted` lifecycle for some reason. I'm not a Vue developer, so I don't know exaclty how Vue deals with the components lifecycle, but my guess is that Vue doesn't unmount some components with conditional render to reuse them in the future. And the `MessageView` component has a conditional render.

![image](https://user-images.githubusercontent.com/6934800/143656139-580e4f10-d501-437a-a9e6-ba995c37ef47.png)

The solution that we made for this issue is remove all `scrollToMessage` events before create a new one in the `created` lifecycle

![image](https://user-images.githubusercontent.com/6934800/143656202-f0d5e2fc-33a2-4059-83f6-285c5453b121.png)

I'm not sure if this is the best solution, but worked like a charm, and if you guys think this solution is applicable to you, we can make a PR with it.

**Comment by fabriciorissetto** [comment] 2021-11-29 18:25
Thank you for your quick responses as well @pranavrajs :rocket:

**Comment by sojan-official** [comment] 2021-11-30 15:28
fixed in https://github.com/chatwoot/chatwoot/pull/3478

**Closed by sojan-official** 2021-11-30 15:28 UTC
Labels: investigation
