### ISSUE TITLE
What is the source_id and what is the proper way to create a new conversation?

### ISSUE THREAD

**Issue by AlessandraFrancez** [chatwoot/chatwoot#988] opened 2020-06-29 20:59 UTC
I apologize if this isn't the proper forum for questions. I'm trying to integrate Chatwoot with my own project, which already handles conversations with users from many channels. As such, I'm looking for a purely API-based implementation. 

I've been studying the APIs and from what I can tell, to start a conversation I should use:

POST /accounts/:account_id/contacts to create a new user
POST /accounts/:account_id/conversations to create a new conversation
POST /accounts/:account_id/conversations/:id/messages to send new messages

And then use the webhook to update messages on my side. Is this the correct approach? 

If so, what should be the source_id on Create New Conversation? I noticed that field is empty on all the messages I received from the webhook so I'm not sure what it represents.

Anyway, no matter what I try to fill it with, I get:

{
    "error": "Resource could not be found"
}

What am I missing?

**Comment by pranavrajs** [comment] 2020-06-30 03:49
@AlessandraFrancez 

`source_id` represents the session identifier of the user. Our APIs are not suited to create conversations via API now. We are making some changes to it for enabling an API based channel. 

> As such, I'm looking for a purely API-based implementation.

This is not supported fully yet. This will be available in future releases. Please join our discord channel https://discord.gg/cJXdrwS, our team will be able to help you better.

Closing this as this is not a bug/enhancement.

**Closed by pranavrajs** 2020-06-30 03:49 UTC

**Comment by sojan-official** [comment] 2020-07-24 05:21
Note:

- Chatwoot now supports API channels: https://github.com/chatwoot/chatwoot/commit/8079bf50a0f656c5e3120919e34df3eb5ee25140

the flow for creating a conversation via API goes like this 
- create a contact, with inbox_id and source_id in params 
  ( if source id isn't provided. chatwoot will automatically generate a source id ) 
- use the source id to create a conversation on behalf of the contact.
