### ISSUE TITLE
"Delete Conversation" Missing?

### ISSUE THREAD

**Issue by Evoltstore** [chatwoot/chatwoot#9711] opened 2024-07-02 08:56 UTC
### Is your feature or enhancement related to a problem? Please describe.

Is there any "delete" conversation feature in Chatwoot?
We are trying to use Chatwoot for email management, however I can't find any way to delete conversations. 

### Describe the solution you'd like

From time to time we get some SPAM emails that we wish to both block and delete, or even just a unrelated email from a supplier that might send important emails at some points but one is unrelated to us so we just wish to delete it in order to keep the inbox clean and organized.
The point is that ideally the email would be deleted from the chatwoot conversations and also from the original set up email.

I found this in the docs but the page seems to be broken https://www.chatwoot.com/docs/user-guide/conversation-workflow/#delete-message 
But I couldn't find this option

### Describe alternatives you've considered

We have tried to delete/trash button in the "contact" and it does delete the conversation as well, the problem is that if this is a set up SMTP email channel, it does not delete the email from the original inbox which means soon it will just load up the message again like a new conversation.

**Comment by iammattmartin** [comment] 2024-07-03 00:14
Search is a powerful thing..

#947

**Comment by Evoltstore** [comment] 2024-07-03 08:06
@iammattmartin 
Thanks for pointing me there, Initially I searched for the terms "Delete messages" but couldn't find anything. While writing this issue I mentally corrected for the correct term of "Delete conversation" but it did not occur me to search again.
Curiously searching right now trying for "Delete conversation" 
returns #9219 in the first page but the thread you shared doesn't really seem to show up
either github search sucks or I suck at github search :P

**Comment by pranavrajs** [comment] 2024-07-08 04:09
Closing this as this is duplicate of #947

**Closed by pranavrajs** 2024-07-08 04:09 UTC
Labels: feature-request, 📮 channel/email
