### ISSUE TITLE
Chat Widget does not work correctly on Android phones

### ISSUE THREAD

**Issue by Diplomat-LV** [chatwoot/chatwoot#8066] opened 2023-10-06 15:36 UTC
### Describe the bug

1. This problem only happens for Android users and most likely is chrome browser issue (iphone users don‘t get this issue).
2. First time customer can successfully have a chat with agent – widget refreshes, answers are visible.
3. When the same customer starts second session (or third and later), not at the same time, just new conversation – chat widget buttons stop working correctly.
4. „Start conversation“ and „exit conversation“ doesn‘t refresh window and customer doesn‘t see responses.
5. We checked it many times by deleting customer contact and his conversation history from chatwoot. First chat is always good, next one – no.
6. We are using "Chatwoot v3.1.1 - Bugfix" LinuxVM installation with Node.js v20.5.1

Video recording of a failing chat session on Android
https://github.com/chatwoot/chatwoot/assets/118850916/e9f811e5-5ea6-4749-8c46-a3b850397fd3

### To Reproduce

1. Open Chat Widget on Android phone, type a message, press „Start conversation“ then „exit conversation“ and close the Chat Widget. If customer does this for the first time, the chat session will succeed.
2. Open Chat Widget on Android phone, using the same customer as in step1, and type a message.  Pressing „Start conversation“ will not refresh the Chat Widget and it will look as if nothing has happened.

Please see attached video recording in "describe the bug" section.

### Expected behavior

When returning customer on Android phone presses „Start conversation“, Chat Widget refreshes, thus notifying the customer that the message has been sent.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Mobile

### Operating system

Android

**Comment by pranavrajs** [comment] 2023-10-08 06:22
@Diplomat-LV Can you please share the browser console error and the network logs? 

It seems like you are being rate-limited and it doesn't seem to be an issue with the device type.

**Comment by Diplomat-LV** [comment] 2023-10-09 13:05
@pranavrajs The client's developers opened a similar case and asked to close this one while referencing to the new one.

Widget issues with consequent chats #35
https://github.com/chatwoot/chatwoot-react-native-widget/issues/35

Sorry for the caused inconvenience.

**Comment by imvlat** [comment] 2023-10-18 07:59
Hello @pranavrajs @nithindavid !
It was confirmed on Chatwoot Mobile App developer Discord chat that the issue is reproducible by other users
https://discord.com/channels/647412545203994635/1162333290162819112/1163434444091310112 

Could you please check React Native chatwoot libraries?

And please respond to sales@chatwoot.com - our customer plans to buy Premium support, but no reaction so far.

Kind regards,
Mihails Ivanovs | Belam

**Comment by pranavrajs** [comment] 2023-10-18 18:53
Closing this here. We will continue the discussion over https://github.com/chatwoot/chatwoot-react-native-widget/issues/35

**Closed by pranavrajs** 2023-10-18 18:53 UTC
Labels: need-more-info, 🐳 channel/live-chat
