### ISSUE TITLE
Twitter creating conversation for originated tweets

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1043] opened 2020-07-14 23:53 UTC
**Describe the bug**
If the twitter account added tweets a newly created message, CW creates this as a conversation. Generally this is not required because we know the tweet having created it but it also means that replies will go do that tweet instead of the actual user.

**To Reproduce**
1) Tweet from account
2) View new tweet as conversation in CW.

**Expected behavior**
Originated tweets from twitter account user should be ignored.

**Comment by pranavrajs** [comment] 2020-07-15 05:54
@iammattmartin Got the same feedback from other people as well, we will take it up along with other Twitter issues this sprint.

**Comment by pranavrajs** [comment] 2021-01-17 20:44
@iammattmartin I have researched about this about a couple of times. The easiest solution is to keep the conversation, but create it in the resolved state by default. Otherwise, we would not be able to maintain the thread. 

The second part of the problem is actually solved already.

**Comment by iammattmartin** [comment] 2023-01-05 16:46
Was there any ever progress on this given this issue is nearly 3 years old and is still a problem.

**Comment by pranavrajs** [comment] 2023-05-25 18:59
Closing this for now as we have put the Twitter integration on hold due to the API and pricing changes.

**Closed by pranavrajs** 2023-05-25 18:59 UTC
Labels: backend, need-discussion, v3-board-cleanup
