### ISSUE TITLE
Website Domain cannot have a restrictive effect

### ISSUE THREAD

**Issue by yhmjSky** [chatwoot/chatwoot#8412] opened 2023-11-24 03:36 UTC
### Describe the bug

I created a webwidget and set the domain to XXX1.com. But I can still use it on XXX2.com, Is this intentional? 

Related questions: #1985  #7309 

### To Reproduce

Create a new inbox, and enter website domain.
Create a new "xxx.html" file locally, copy the script code, and open it.
Widgets can be used!

### Expected behavior

There can be a simple limit

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by vishnu-narayanan** [comment] 2023-11-27 06:54
@yhmjSky This is the intended behavior at this point. The widget is not restricted to the domain.

**Comment by yhmjSky** [comment] 2023-11-28 07:46
> @yhmjSky This is the intended behavior at this point. The widget is not restricted to the domain.

Thank you for your reply.
In addition, if I use webhook, is the IP received by the hook server the IP of my cw project, or the IP of the chat user?

**Comment by pranavrajs** [comment] 2023-12-01 03:16
@yhmjSky The IP address in the webhook payload is the IP of the user. I'm closing this for as the feature is working as intended.

**Closed by pranavrajs** 2023-12-01 03:16 UTC
