### ISSUE TITLE
Facebook / Twitter

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#4415] opened 2022-04-07 17:34 UTC
We are repeatedly seeing both Facebook and Twitter just stop working. There is no feedback when this happens and our configuration (keys etc) has not changed.

Again we've had to re-connect Facebook and we then lose all historic messages received since the link was broken (i.e they show in Facebook only). There must be a better way to check and notify of this instead of a link at the bottom of Faacebook Inbox settings that is always there now regardless of linking status. This means we have no idea if it is linked or not! 

Furthermore, the Twitter implementation gives no feedback whatsoever. Our tweets were coming through, stopped some time ago and now, no matter which guide step we use (1 or 2), we see no attempts from Twitter in to the server and none out from the server and zero ways to debug it!

This really needs to be given more focus when it is a core feature of the product which, based on other reports i've seen, just is not reliable enough.

**Comment by iammattmartin** [comment] 2022-04-07 17:50
+ and it seems on Twitter, the webhook is registered on Inbox add (as it appears deleted on removal) which fixes it but you cannot re-add an existing twitter account as would be the only way to refresh it. Deleting the inbox to re-add is not viable!

**Comment by tejaswinichile** [comment] 2022-04-07 18:05
@iammattmartin I suppose this is the self-hosted version? 
If you have your Twitter and Facebook apps, can you check recent errors in your Facebook app? You can find it on the Messenger settings page. And make sure the business settings are correct for the page as the app can manage the page.

For Twitter, I will try to reproduce the above issue if you could elaborate more when that appears. If you happened to know the flow.

**Comment by iammattmartin** [comment] 2022-04-07 18:10
It is.

There were no errors in the Facebook app. Re-linking has fixed it, as it always does but we lose the message timelines.

For twitter, that error happens when you try and re-add the same twitter account to fix the re-linking. The only way to fix a Twitter account is to delete it and re-add it which then immediately works. It's not viable for this to be done when there are messages attached to the twitter account which will be deleted by doing so.

**Comment by iammattmartin** [comment] 2022-04-07 22:20
As an aside, it would be good to know how to re-initiate the webhooks call to Twitter without having to delete/re-add an account.

**Comment by tejaswinichile** [comment] 2022-04-08 05:28
> As an aside, it would be good to know how to re-initiate the webhooks call to Twitter without having to delete/re-add an account.

Sure, we would take it as an investigation ticket for the upcoming sprints, @iammattmartin  Thanks for the detailed research on the issue. 👍🏼

**Comment by iammattmartin** [comment] 2022-04-19 16:17
Was there any update on this? We urgently need a way to re-link twitter accounts. For a customer support tool which doesn't do one of the basic things, it's pretty concerning that it has taken nearly 2 weeks to get anything on this - all the while - we're missing messages in one of the core channel types.

**Comment by pranavrajs** [comment] 2022-04-22 10:58
@iammattmartin 

A couple of questions on this. 

> Again we've had to re-connect Facebook and we then lose all historic messages received since the link was broken (i.e they show on Facebook only)

What does this mean? Do you lose data when you re-authorize Facebook?

> There must be a better way to check and notify of this instead of a link at the bottom of Facebook Inbox settings that is always there now regardless of linking status. This means we have no idea if it is linked or not!

Facebook has changed the ways apps worked from what they had in the past, they added thread-locks which would have resulted in a set of complexities, such as webhooks not being received by other apps. Please make sure you have only added Chatwoot to your page. Please see this for more information. https://github.com/chatwoot/chatwoot/discussions/3397#discussioncomment-2593391

>  Twitter implementation gives no feedback whatsoever. Our tweets were coming through, stopped some time ago

I'm not sure why this is happening. 

Do you hit the limits on your Twitter Business API subscription? A free plan on Twitter APIs would only allow 15 accounts to subscribe to it.

Do you have Firewall Changes which has resulted in temporary (15 minutes or more) downtime recently?

If you have not deleted the Twitter Profile, you can try running the following command and share the results.

```rb
inbox = <your-twitter-inbox-id>
Twitter::WebhookSubscribeService.perform(inbox_id) 
```

**Comment by iammattmartin** [comment] 2022-04-22 11:09
This is largely for Twitter as there is no way to re-link a twitteraccount.

I have tried that but got  an error.

```
3.0.2 :004 > inbox = 22
 => 22
3.0.2 :005 > Twitter::WebhookSubscribeService.perform(inbox_id)
(irb):5:in `<main>': undefined local variable or method `inbox_id' for main:Object (NameError)
Did you mean?  inbox
```

No limits have been hit on the Twitter account/app though.

**Comment by pranavrajs** [comment] 2022-04-22 11:12
@iammattmartin Please use `inbox_id = 22`, not inbox

**Comment by iammattmartin** [comment] 2022-04-22 11:15
Have changed:

```
(irb):2:in `<main>': undefined method `perform' for Twitter::WebhookSubscribeService:Class (NoMethodError)
```

**Comment by pranavrajs** [comment] 2022-04-22 11:44
Oops! Sorry, it should have been this 

```
inbox_id = 22
::Twitter::WebhookSubscribeService.new(inbox_id: inbox.id).perform
```

**Comment by pranavrajs** [comment] 2022-04-22 12:23
@iammattmartin 

Please try the below one. It should work.

```rb
inbox = Inbox.find(22)
::Twitter::WebhookSubscribeService.new(inbox_id: inbox.id).perform
```

**Comment by iammattmartin** [comment] 2022-04-22 12:25
One step further but another error:

```
/usr/local/rvm/gems/ruby-3.0.2/gems/activesupport-6.1.4.7/lib/active_support/core_ext/object/try.rb:15:in `[]': no implicit conversion of String into Integer (TypeError)
```

**Comment by pranavrajs** [comment] 2022-04-22 12:32
@iammattmartin Can you please share the full log?

**Comment by iammattmartin** [comment] 2022-04-22 12:37
After entering the second command, that is the only line returned. There is no other information output.

Do you mean the system logs?

**Comment by iammattmartin** [comment] 2022-04-25 18:05
@pranavrajs Any work around the error to re-auth twitter so messages are incoming again?

**Comment by pranavrajs** [comment] 2022-04-26 08:28
@pranavrajs As far as we know, there is no API for re-authorising. We can check if the webhook subscription is available, if not ask to resubscribe. This is what the script should do, I'm not sure why it is throwing a cryptic error. 

Can you please share what you get as a result of these following commands? Please execute these steps one by one and share the result. 

```rb
inbox_id  = 22
inbox = Inbox.find(inbox_id)

channel = inbox.channel

channel.fetch_webhooks

channel.fetch_webhooks.body
```

**Comment by pranavrajs** [comment] 2022-04-26 08:33
@iammattmartin Please make sure that you execute the above commands in production rails console. 

```
RAILS_ENV=production bundle exec rails c
```

**Comment by iammattmartin** [comment] 2022-04-26 10:40
```
3.0.2 :011 > channel.twitter_client.fetch_webhooks
 =>
#<Twitty::Response:0x000055dc92c6a768
 @raw_response=#<Net::HTTPUnauthorized 401 Unauthorized readbody=true>>
3.0.2 :012 > channel.twitter_client.fetch_webhooks.body
 => {"errors"=>[{"code"=>89, "message"=>"Invalid or expired token."}]}
```

**Comment by iammattmartin** [comment] 2022-04-29 15:02
Is there any known way on refreshing the token @pranavrajs?

**Comment by pranavrajs** [comment] 2022-05-02 08:24
@iammattmartin Have you reset the Twitter app credentials for some reason? 401 unauthorized means that your existing tokens are expired, as far as I know, the Twitter auth token is active until the token is available. I'll research ways to go around this issue.

**Comment by iammattmartin** [comment] 2022-05-02 12:23
This may have happened after the tweets had already stopped to try and fix the issue but given there is no output from CW, it is impossible to know what happens.

Either way, there needs to be monitoring or a check in place to monitor this. We were relying on CW to deliver mentions/messages but as we weren't getting that, we didn't think we had any - which was no the case and led to customer annoyance on being "ignored".

There must be greater focus on such monitoring of core channels because if CW is meant to be relied upon as a reliable source, when that breaks silently, we are not to know any different and would be counter productive to run a twitter client in addition just to monitor this software.

In any case, where the link is broken, either CW needs to re-auth the link manually or provide a way to do this, which at the moment, when we try and re-add the twitter account, we get that [error ](https://github.com/chatwoot/chatwoot/issues/4415#issuecomment-1092028044) above.

**Comment by tejaswinichile** [comment] 2022-05-02 13:10
@iammattmartin 
> This may have happened after the tweets had already stopped to try and fix the issue but given there is no output from CW, it is impossible to know what happens.

Displaying the error or notifying that something is broken is doable, it might be available in Sentry if you have that connection with your app. 

> In any case, where the link is broken, either CW needs to re-auth the link manually or provide a way to do this

 If any error appears to be from the Twitter side I am not sure right now but you would have to re-connect to your existing account with the new inbox.

Are you getting the below error after deleting the previous Twitter inbox?

https://github.com/chatwoot/chatwoot/issues/4415#issuecomment-1092028044

> Deleting the inbox to re-add is not viable!

To tackle `add a Twitter account to an existing inbox` would take some time because we would have to build that functionality at CW, as Twitter doesn't provide re-authorization.

cc @pranavrajs @sojan-official 

We can have this as a new enhancement to investigate upon re-authorization on the twitter account for the existing inbox.

**Comment by iammattmartin** [comment] 2022-05-02 13:13
> Are you getting the below error after deleting the previous Twitter inbox?

Hard to say, if we delete the Twitter inbox, we lose all the history. This is not a workable solution as mentioned before. We shouldn't need to delete something to fix a problem that could only then happen again in the future.

However, adding a new twitter account again that had no history worked as expected. So it is a solution but just not viable without the loss of data.

Either we need to be able to re-auth the connection, or rename the existing twitter inbox, re-add the original one and then merge some how.

**Comment by pranavrajs** [comment] 2022-05-05 04:51
<img width="928" alt="Screenshot 2022-05-05 at 10 18 59 AM" src="https://user-images.githubusercontent.com/2246121/166865051-4698e8bc-8f52-46c5-8937-a6aaaaaaed44.png">
https://developer.twitter.com/en/docs/authentication/faq

@tejaswinichile @sojan-official These are the cases where the OAuth token can be expired. I guess we can add a flow in the inbox settings page to reauthorize the app which would use the same flow as a new Twitter channel but would update the existing OAuth token at the end instead of creating a new one. Let us prioritize this one in the next sprint.

**Comment by iammattmartin** [comment] 2022-05-11 11:49
This is so very frustrating. Again today, we get messages on Facebook but not on CW. 

Needing yet another reconnect with loss of messages.

We are at the point now that we cannot rely upon the software as it is just not reliable enough.

**Comment by iammattmartin** [comment] 2022-05-11 22:26
I don't think that is really required.

Facebook re-linking works but the "reconnect" box at the bottom is always showing, even when the integration is working. 

There just needs to be a massive improvement on re-connecting twitter accounts without having to delete and re-add and also monitoring of said linking of both Facebook and Twitter.

Having a unreliable client to manage these accounts is creating a false sense of security when we are missing messages and no way to re-sync once we have "lost" (this is also really needed).

**Comment by sojan-official** [comment] 2022-05-13 10:39
@iammattmartin  The reauthenticate button at the bottom is always shown for Facebook pages irrespective of the integration status. This is shown for users who would like to reconfigure the permissions allocated to the chatwoot app.

**Comment by iammattmartin** [comment] 2022-05-13 10:40
Noted, but then this means there is no visible way to know the state between facebook and the app. No alerts, nothing visual and until we start getting messages via FB which we only find by logging in there, we are not to know.

**Comment by tejaswinichile** [comment] 2022-06-02 13:27
@iammattmartin We do send messages to the chatwoot account admin if the FB session is expired during sending or receiving messages between Facebook chatwoot account.

https://github.com/chatwoot/chatwoot/blob/develop/app/builders/messages/facebook/message_builder.rb#L125

And I think this new change would resolve your concern https://github.com/chatwoot/chatwoot/pull/4695

**Comment by pranavrajs** [comment] 2023-05-25 19:02
Closing this here as the Twitter integration is disabled and for Facebook inboxes we now have a notification mailer that sends the update when the inbox is disconnected.

**Closed by pranavrajs** 2023-05-25 19:02 UTC
Labels: chore
