### ISSUE TITLE
bug: conversation assignee dropdown shows agents who are not part of the inbox.

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#3719] opened 2022-01-10 05:18 UTC
The conversation assignee dropdown shows agents who are not part of the inbox.

<img width="449" alt="Screenshot 2022-01-10 at 10 47 33 AM" src="https://user-images.githubusercontent.com/1277421/148721210-b74f4440-ab22-4e74-94fc-7133e3d63536.png">

![image](https://user-images.githubusercontent.com/1277421/148720942-fedba71e-eb3a-4efc-b29f-53dd4ff68d74.png)

**Comment by pranavrajs** [comment] 2022-01-11 19:39
@nithindavid This is working as expected. You can assign it to the inbox members or administrators. The list is fetched using `assignable_agents` which is returning the right set of agents.

**Comment by pranavrajs** [comment] 2022-01-11 19:43
Closing this issue as it is not a bug.

**Closed by pranavrajs** 2022-01-11 19:43 UTC
Labels: bug
