### ISSUE TITLE
Image broken inside Email ticket

### ISSUE THREAD

**Issue by aslamabbas** [chatwoot/chatwoot#4847] opened 2022-06-13 07:43 UTC
Images do not load properly inside Email inbox tickets. They appear broken.

Example: https://imgur.com/a/cUj3BPt

We can download the images. But we not see them inside the mails, in the way they were sent.

**Comment by pranavrajs** [comment] 2022-06-16 08:10
This is similar to https://github.com/chatwoot/chatwoot/issues/4875. This issue could've happened due to style removal during rendering. Let us investigate this further.

**Comment by pranavrajs** [comment] 2023-12-05 21:25
Closing this here as the rendering has been updated a lot since the 2.8.0 version and this issue is not reproducible anymore.

**Closed by pranavrajs** 2023-12-05 21:25 UTC
Labels: 🐞 bug, investigation, product
