### ISSUE TITLE
Can't receive email when adding customer service

### ISSUE THREAD

**Issue by phpmac** [chatwoot/chatwoot#9253] opened 2024-04-17 10:29 UTC
### Describe the bug

Where is the email address configured?

### To Reproduce

Where is the email address configured?

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by vishnu-narayanan** [comment] 2024-04-19 02:25
@phpmac There needs to be more information to debug. Could you please share the answers to the following questions in detail?

## Describe the bug.

## Steps To Reproduce?

## Expected behavior?

**Comment by vishnu-narayanan** [comment] 2024-04-30 06:50
Closing due to lack of information and response. Please reopen if you are still facing this.

**Closed by vishnu-narayanan** 2024-04-30 06:50 UTC
Labels: need-more-info, waiting-for-reply
