### ISSUE TITLE
API List All Messages not returning all messages

### ISSUE THREAD

**Issue by guiqis** [chatwoot/chatwoot#5829] opened 2022-11-09 19:06 UTC
**Describe the bug**

API Endpoint "List All Messages" not listing all messages from conversation. Only the last ones are returned.

**To Reproduce**

1. Run an API call to https://www.chatwoot.com/developers/api/#tag/Messages/operation/list-all-messages and check that only a few (or one) message is being returned.

**Expected behavior**

See all messages in the Payload

**Screenshots**

**Browser logs**

**Server logs**

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [x] Self-hosted
- - [x] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Cloud Provider** (If applicable)
- [ ] AWS
- [ ] GCP
- [ ] Azure
- [ ] DigitalOcean
- [ ] Others

**Additional context**

The endpoint is working because I'm receiving messages. But not all the messages from the conversation.

**Comment by nithindavid** [comment] 2022-11-28 06:33
@guiqis I could not reproduce as the the API was returning correctly. Can you post the actual API response and the original thread?

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1277421/204209245-2cb0cd7b-e9d5-4666-8415-cf6b610f4193.png">

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1277421/204209363-77ca498f-5e34-41e1-9007-e6071e85d953.png">

**Comment by nithindavid** [comment] 2023-01-09 05:30
Hi @guiqis, Closing this issue as we could not reproduce it at our end. Please reopen if this is happening at your side.

**Closed by nithindavid** 2023-01-09 05:30 UTC
Labels: need-more-info
