### ISSUE TITLE
Register Button doesn't show even ENABLE_ACCOUNT_SIGNUP is set to true

### ISSUE THREAD

**Issue by aldhielman** [chatwoot/chatwoot#3699] opened 2022-01-06 04:20 UTC
I have CW installation on Linux VM Server, and i have set ENABLE_ACCOUNT_SIGUNP=TRUE on .env config file
But the register button doesn't show on login page

this screenshot from app.chatwoot.com
![image](https://user-images.githubusercontent.com/16577318/148327480-47a430f8-7ca2-4e81-879f-ad5ab9c46d91.png)

this my screnshot from CW on my linux server
![image](https://user-images.githubusercontent.com/16577318/148327690-8e88af18-8f39-436c-8c6d-1b6ebe804799.png)

**Comment by pranavrajs** [comment] 2022-01-06 06:29
@vishnu-narayanan This is the duplicate of https://github.com/chatwoot/chatwoot/issues/3674. This is a breaking change in my opinion as there is no context on how to recover from this. 

The problem here is that we don't have a straightforward of creating SuperAdmins. Until the #3061 is tested and merged, I would suggest giving preference to ENV if it is available. 

https://github.com/chatwoot/chatwoot/blob/a61dae0bb29edc7417c52d9528581a974631b422/lib/global_config_service.rb#L3

Instead of the above line, please use
```
config = ENV[config_key] || GlobalConfig.get(config_key)
```

@sojan-official Thoughts?

**Comment by pranavrajs** [comment] 2022-01-06 07:25
@aldhielman That might be something different, not related to this issue. Have you set the FRONTEND_URL variable?

**Comment by aldhielman** [comment] 2022-01-06 07:37
> FRONTEND_URL

I've set with my own domain and it worked to open image or file when customer sent me chat via website widget

**Comment by sojan-official** [comment] 2022-01-06 09:47
@pranavrajs  I don't think #3288, #3674 led to/were unintended breakages. But the failure to update our documentation/release notes led to confusion. 

The intention of #3288 is to deprecate environment variables and promote configurations from the UI so that the changes would get reflected on the installation without server restarts. The code also has backwards compatibility for installations with preconfigured environment variables and gracefully switches them to GlobalConfig based configuration. 

when someone updates an existing chatwoot installation with the new changes 
- In the future for these values, they should rely on globalConfig instead of environment variables
- The code will pick up existing environment variables and update them to the globalConfig so the existing workflows wouldn't break

newer installations
- The configurations should be done from super admin pannel

Ideally, we should ensure that there aren't references in our documentation mentioning these environment variables and update the instructions on configuration via GlobalConfig is up to date. 

----

Agreed that until #3061 and onboarding flow is merged, the set-up for super admin console in chatwoot would remain tricky as it requires console. But fallback on environment variables could have some caveats as well. 

- Our installation set-up makes a copy of `.env.example` for the env variables, which would have default values for most variables. Configuration via GlobalConfig could be affected by these env variables and could be confusing [ We will end up having to maintain additional documentation around that ] 
- For newer installations, it would be worthier to start educating them about super admin pannel & global config as that is the way forward. 

-----

Meanwhile, some references that I found where we should update documentation

- https://github.com/chatwoot/chatwoot/blob/a61dae0bb29edc7417c52d9528581a974631b422/.env.example#L100 
- https://github.com/chatwoot/chatwoot/blob/a61dae0bb29edc7417c52d9528581a974631b422/.env.example#L21
- https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#disable-new-user-signup ( convert the documentation to enable signup instead with global config )
- https://www.chatwoot.com/docs/self-hosted/deployment/helm-charts/#chatwoot-environment-variables
- https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup#configuring-the-environment-variables-in-chatwoot ( switch to global config )
- https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/instagram-channel-setup#configuring-the-environment-variables-in-chatwoot ( move IG verify the token to app config, update the documentation )

cc: @vishnu-narayanan

**Comment by vishnu-narayanan** [comment] 2022-01-06 16:49
@pranavrajs Noted. Will revert.

cc: @sojan-official

**Closed** 2022-01-12 03:20 UTC
Labels: need-discussion
