### ISSUE TITLE
Blank page after log out - 3.14 Chatwoot

### ISSUE THREAD

**Issue by ZiekBaboon** [chatwoot/chatwoot#10313] opened 2024-10-17 12:15 UTC
### Describe the bug

After upgrading from version 3.13 to version 3.14 the login screen goes blank and it is impossible to log in again.

The update has been done manually.

To reproduce it I do the following:

1. Log-out
2. Blank page in the login screen.

v3app.js:29 SyntaxError: Invalid linked format (at message-compiler.esm-browser.js:116:19)
    at Fe (message-compiler.esm-browser.js:116:19)
    at m (message-compiler.esm-browser.js:241:25)
    at Oe (compiler-messages.esm-navigator.js:837:21)
    at qe (compiler-message.esm-browser.js:851:20)
    at Object.gt [as nextToken] (compiler-messages.esm-browser.js:896:16)
    at P (compiler-messages.esm-navigator.js:1045:31)
    at k (compiler-messages.esm-browser.js:1153:36)
    at y (compiler-message.esm-browser.js:1193:25)
    at Object.w [as parse] (compiler-message.esm-browser.js:1208:21)
    at ua (compiler-message.esm-browser.js:1608:24)
Promise.then		
(anonymous) @ v3app.js:29
Show 30 more frames

![image](https://github.com/user-attachments/assets/99aadbcd-40d6-4a20-85b9-b0c6b2bab542)

### To Reproduce

1. Log-out
2. Blank page en la pantalla de login

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows, Mac

### Browser and version

Chrome, Firefox, Safari, Opera

**Comment by ZiekBaboon** [comment] 2024-10-17 12:47
Same problem with macOS Mojave

**Comment by sojan-official** [comment] 2024-10-17 21:21
@ZiekBaboon please share more information about the chatwoot version, whether you have done any recent changes upgrade etc.

**Comment by willihangga** [comment] 2024-10-18 03:35
We’re still encountering the same error, and we believe it’s related to this specific file. Our current solution is to downgrade to version 3.13.0 for now. Let me know if there are any other suggestions or solutions.

![Screen Shot 2024-10-18 at 10 34 00](https://github.com/user-attachments/assets/c516b520-2006-4374-9302-159ea41d6a93)

**Comment by willihangga** [comment] 2024-10-18 03:37
We’re still encountering the same error, and we believe it’s related to this specific file. Our current solution is to downgrade to version 3.13.0 for now. Let me know if there are any other suggestions or solutions.

![Screen Shot 2024-10-18 at 10 34 00 2](https://github.com/user-attachments/assets/0450e622-318b-43c4-9344-01f57042ed0b)

**Comment by vishnu-narayanan** [comment] 2024-10-18 04:40
@willihangga Have you made any custom changes to the fronted code? Was the upgrade to 3.14 successful?

**Comment by willihangga** [comment] 2024-10-18 05:38
It seems that the upgrade was successful, but when trying to log in, I’m getting a blank page with the error showing in the console log. I’m using the Docker image from DockerHub without any customizations on the frontend.

**Comment by ZiekBaboon** [comment] 2024-10-18 06:14
> @ZiekBaboon please share more information about the chatwoot version, whether you have done any recent changes upgrade etc.

Last Chatwoot version 2.14. This appeared after the upgrade (manual upgrade because I had an old CWCTL)

Hosted on Linux ubuntu VM

**Comment by vishnu-narayanan** [comment] 2024-10-18 10:52
@willihangga I cannot reproduce this on the `3.14` docker installation. Please find the screenshot from a fresh `3.14` docker installation. 

Could you share more about your installation? Which version were you upgrading from?

<img width="1676" alt="image" src="https://github.com/user-attachments/assets/8553ec29-cf4a-460a-9ca7-fcea3c87230d">

**Comment by vishnu-narayanan** [comment] 2024-10-18 10:53
@ZiekBaboon Did you upgrade from Chatwoot `2.14.0` to `3.14.0`?

**Comment by michaelmeneses** [comment] 2024-10-18 17:37
Same here

**Comment by agebeyaw** [comment] 2024-10-18 22:37
Happens same here as well. Upgrade was successful from 3.13 to 3.14. But after logout unable to login again and it shows completely empty screen with error on console

![Screenshot 2024-10-19 at 00 37 03](https://github.com/user-attachments/assets/06d76857-d2c1-4afe-b577-1e559bcab5c7)

**Comment by vaestvita** [comment] 2024-10-19 04:00
I have the same problem when installing chat in docker on Linux, on Windows 10 the login form is displayed correctly

**Comment by rgfpy** [comment] 2024-10-19 12:50
Hello, i have the same error, updated from 3.13 ro 3.14 and not working more the front page and not show the login page
Installation is in VPS.

The error show in console JS is: Uncaught SyntaxError: Invalid or unexpected token (at dashboard-DFlvZe8j.js:6:13851) the line JS is: _=s(1.toString);r.exports=function(p){return"Symbol("+(p===void 0?"":p)+")

**Comment by vaestvita** [comment] 2024-10-20 04:37
I found the cause of the problem - if the DEFAULT_LOCALE variable is active in your .env file and it is set to a value other than "en" (in my case, it was set to "ru"), the login form does not appear. If you set the variable to "en," the login form displays correctly (I haven't tested it with other languages).

**Comment by rgfpy** [comment] 2024-10-21 12:26
> I found the cause of the problem - if the DEFAULT_LOCALE variable is active in your .env file and it is set to a value other than "en" (in my case, it was set to "ru"), the login form does not appear. If you set the variable to "en," the login form displays correctly (I haven't tested it with other languages).

thanks for these data

**Comment by scmmishra** [comment] 2024-10-22 09:38
@ZiekBaboon I've create a PR with a potential fix for this https://github.com/chatwoot/chatwoot/pull/10334
You can checkout this branch and test it out for yourself. The PR description includes the exact reason why this bug was surfacing.

**Closed** 2024-10-22 10:13 UTC
Labels: need-more-info, self-hosted, Bug
