### ISSUE TITLE
SMTP settings not working "ActionView::Template::Error: Missing host to link to!"

### ISSUE THREAD

**Issue by madebyjono** [chatwoot/chatwoot#5263] opened 2022-08-13 09:30 UTC
**Describe the bug**

In trying to add agents or send password reset emails to the agents, no emails are sent/received.
I'm using zoho's smtp.

In the Sidekiq logs I'm getting Dead jobs with Error messages:

"ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true"

SMTP-related env vals are set as below:

SMTP_USERNAME=email@mydomain.com
SMTP_PASSWORD=mypassword
SMTP_AUTHENTICATION=login
SMTP_PORT=587
SMTP_ADDRESS=smtppro.zoho.com

FRONTEND_URL has been set as well

Am I missing something?

**Expected behavior**

Password reset / Agent notification emails sent

**Environment**

Self-hosted and installed via Caprover one-click install

**Comment by madebyjono** [comment] 2022-08-13 12:55
Apparently the same environment variables needed to be added to the worker as well. I did that and didn't get the error messages anymore. But now its showing 
"EOFError (end of file reached)"

**Comment by madebyjono** [comment] 2022-08-14 02:13
Okay don't mind me. 
I had set the sender env as MAIL_SENDER_EMAIL instead of MAILER_SENDER_EMAIL. 
Check your spelling guys.

**Comment by pranavrajs** [comment] 2022-08-18 08:09
@madebyjono Closing it as it seems the issue is resolved, let me know if it is not the case.

**Closed by pranavrajs** 2022-08-18 08:09 UTC
