### ISSUE TITLE
NoMethodError raised when setting for inbox business availability time

### ISSUE THREAD

**Issue by lwdStudio** [chatwoot/chatwoot#6441] opened 2023-02-13 03:33 UTC
**Describe the bug**

NoMethodError raised when checking business availability time setting

**To Reproduce**

1. Go to 'Setting' -> 'inbox' -> 'inbox setting' -> 'business hours'
2. Click on 'Enable business availability for this inbox'
3. Make changes to any of the business end time
4. Error Prompt "Starting time should be before closing time." when selecting for any options. NoMethodError will be raised in sentry/console log. 

**Expected behavior**

Correct time checking for closing time after starting time.

**Screenshots**

![image](https://user-images.githubusercontent.com/21992845/218357564-77caa045-eb48-48c2-9822-295182c44b71.png)

**Browser logs**

Link to Sentry:

[**Server logs**](https://beijing-7d-vision-technologies.sentry.io/share/issue/4661564cafcc444285584a93bea33781/)

**Environment**

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [x] Self-hosted
- - [ ] Linux VM
- - [x] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: Windows
 - Browser Microsoft Edge
 - Version 110

**Docker** (If applicable)

Please share the output of the following.
- `docker version`
```
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:47:51 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:47:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- `docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 9
  Running: 8
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.505GiB
 Name: cn-wulanchabu-aliyun-web
 ID: 11cdcf0b-2fe4-4ea4-a517-b01753604f38
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- `docker-compose version`
```
Docker Compose version v2.15.1
```

**Cloud Provider** (If applicable)
- [ ] AWS
- [ ] GCP
- [ ] Azure
- [ ] DigitalOcean
- [x] Others

**Additional context**

This is a recent Chatwoot Docker install on a fresh Ubuntu for my company's website deployment. The issue never happened on an older version of Chatwoot installed on our testing machine, which has been running for months with no major issues.

**Comment by pranavrajs** [comment] 2023-02-14 00:54
@lwdStudio Can you please share the server logs also? It seems like the database is not up to date or there is some issue with the migration. Any additional information would be helpful.

**Comment by lwdStudio** [comment] 2023-02-14 06:14
I have been going through server logs, I don't see any error prompted, or even GET method called for changing business availability setting. It might not be that useful.

I believe the time checking is done in front-end, which aligns to the sentry error I posted previously. 

I also try to access the same page on a Firefox browser and on Safari on iPhone, the issue no longer exists, and time checking method works as expected.

![image](https://user-images.githubusercontent.com/21992845/218653822-865fe2d9-e542-42ac-b2f8-4a23b09d6908.png)

It seems like the way Chromium based browser interpret the method differently. I am able to repeat the issue on a Chromium browser 110 installed on fedora. 

![image](https://user-images.githubusercontent.com/21992845/218653734-2d87e2be-c3e1-496d-8620-9db16726f5ac.png)


This seems to be a minor bug; I might want to use Firefox for setting up Chatwoot for now.

**Comment by lwdStudio** [comment] 2023-02-14 06:22
app.chatwoot.com has the same behavior. You can try on your own using a later version of chromium.

![image](https://user-images.githubusercontent.com/21992845/218655749-ecd336e6-ffcf-44e5-aafa-07279356134d.png)

**Comment by pranavrajs** [comment] 2023-05-25 19:27
Not sure, if this is an issue with the specific build of Chromium. I can't reproduce this on Chrome similar version. Closing this here for now. Please feel free to reopen if this is the same case with the latest version of Chromium

**Closed by pranavrajs** 2023-05-25 19:27 UTC
Labels: need-more-info, investigation
