### ISSUE TITLE
Popup Chat Messages based on the web page of the user

### ISSUE THREAD

**Issue by dtharindu** [chatwoot/chatwoot#1213] opened 2020-09-10 08:14 UTC
When the user is on a particular page popup a personalized message to initiate the conversation with the user.

Eg: If the customer is on the pricing page -> popup a message from the chat widget and ask "Do you have any questions regarding pricing?

**Comment by pranavrajs** [comment] 2020-09-10 10:56
Seems like this is a duplicate of #1209. Please feel free to reopen the issue if it is not the case.

**Closed by pranavrajs** 2020-09-10 10:56 UTC
