### ISSUE TITLE
Hi @sojan-official and @pranavrajs

### ISSUE THREAD

**Issue by machalex** [chatwoot/chatwoot#1452] opened 2020-11-24 18:10 UTC
Hi @sojan-official and @pranavrajs 
Sorry but emails account confirmation still not sent.
Sidekiq is working but jobs not working

![image](https://user-images.githubusercontent.com/11045936/100134515-a09ce980-2e88-11eb-83d1-101d65986efa.png)

Any Ideas ?

_Originally posted by @machalex in https://github.com/chatwoot/chatwoot/issues/1437#issuecomment-733148242_

**Comment by pranavrajs** [comment] 2020-11-24 18:54
Closing this as it is a duplicate of #1437

**Closed by pranavrajs** 2020-11-24 18:54 UTC
