### ISSUE TITLE
On Build: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by drauber** [chatwoot/chatwoot#8995] opened 2024-02-22 14:03 UTC
### Describe the bug

While i'm run `RAILS_ENV=production rake assets:clean assets:clobber assets:precompile` the process is interrupted by **FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory**

### To Reproduce

In local environment with few updates, using WSL, and 16GB Ram, on a I5-12500H
When i run:  `RAILS_ENV=production rake assets:clean assets:clobber assets:precompile` after this command 3~4 minutes i receive this output:
`.....

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
55 │ $input-padding: $form-spacing / 2 !default;
   │                 ^^^^^^^^^^^^^^^^^
   ╵
    node_modules/foundation-sites/scss/forms/_text.scss 55:17                       @import
    node_modules/foundation-sites/scss/forms/_forms.scss 13:9                       @import
    node_modules/foundation-sites/scss/foundation.scss 28:9                         @import
    app/javascript/dashboard/assets/scss/_woot.scss 23:9                            @import
    app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue 2:9  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($form-spacing, 2) or calc($form-spacing / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
39 │   padding: ($form-spacing / 2 + rem-calc($input-border-width)) 0;
   │             ^^^^^^^^^^^^^^^^^
   ╵
    node_modules/foundation-sites/scss/forms/_label.scss 39:13                      form-label-middle()
    node_modules/foundation-sites/scss/forms/_label.scss 47:7                       foundation-form-label()
    node_modules/foundation-sites/scss/forms/_forms.scss 28:3                       foundation-forms()
    node_modules/foundation-sites/scss/foundation.scss 90:3                         foundation-everything()
    app/javascript/dashboard/assets/scss/_woot.scss 25:1                            @import
    app/javascript/dashboard/routes/dashboard/settings/inbox/WidgetBuilder.vue 2:9  root stylesheet

WARNING: 18 repetitive deprecation warnings omitted.

<--- Last few GCs --->

[4333:0x5c5a570]   116433 ms: Scavenge 2027.0 (2078.7) -> 2022.6 (2078.9) MB, 5.18 / 0.00 ms  (average mu = 0.228, current mu = 0.127) allocation failure;
[4333:0x5c5a570]   116447 ms: Scavenge 2028.0 (2078.9) -> 2024.5 (2081.7) MB, 6.56 / 0.00 ms  (average mu = 0.228, current mu = 0.127) allocation failure;
[4333:0x5c5a570]   116462 ms: Scavenge 2030.2 (2081.7) -> 2026.2 (2098.9) MB, 7.51 / 0.00 ms  (average mu = 0.228, current mu = 0.127) allocation failure;

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xc9b0c0 node::Abort() [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
 2: 0xb700c9  [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
 3: 0xec0260 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
 4: 0xec0547 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
 5: 0x10d1bd5  [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
 6: 0x10e9a58 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
 7: 0x10bfb71 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
 8: 0x10c0d05 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
 9: 0x109d346 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
10: 0x108ee44 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
11: 0x10921f7 v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
12: 0x13e1b85 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
13: 0x13d9cac v8::internal::StringTable::LookupString(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
14: 0x1504a88 v8::internal::Runtime_HasProperty(int, unsigned long*, v8::internal::Isolate*) [/home/douglas/.asdf/installs/nodejs/20.7.0/bin/node]
15: 0x7f6535e99ef6
`

### Expected behavior

Build all source code withouth any problem 
or 
How i can trace where is the error or change the build process to test different kinds?

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu over VPS, tried too in Hetznet Ubuntu.

**Comment by drauber** [comment] 2024-02-23 10:30
I am endeavoring to identify the issue by utilizing all the tools at my disposal. However, it seems that the only effective solution I've found so far is to increase the physical RAM on the machine. On a pristine system with a fresh installation of Ubuntu and 16GB of RAM, the build process is successful. On the same machine with only 8GB, the build fails.

Upon analyzing the build log, I've discover that the issue occurs immediately before the following point: 
`
....
Hash: 1ab0db292662fb7eb04b
Version: webpack 4.46.0
Time: 195971ms
Built at: 02/23/2024 7:12:28 AM
                                                                                                      Asset       Size              Chunks                                Chunk Names
                                                                                   css/2-e7ad3990.chunk.css   20.2 KiB                   2  [emitted] [immutable]         
....
`
 Is ther a way to trace whats happen?

Thanks.

**Comment by shivamkb17** [comment] 2024-02-28 19:33
In 8 GB RAM, the build process is also successful, The chatwoot installation time need atleast 4 core server/ VPS. 
If less then build process failed.

**Comment by sojan-official** [comment] 2024-03-12 14:03
Please refer to https://stackoverflow.com/a/19371813 

Closing this as the issue is on a modified version of Chatwoot.

**Closed by sojan-official** 2024-03-12 14:03 UTC
Labels: 🐞 bug
