### ISSUE TITLE
feat: Dark Mode

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1042] opened 2020-07-14 22:40 UTC
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A dark mode theme for the staff interface.

**Describe alternatives you've considered**
Can use alternative hacks but these often break notifications on some platforms.

**Additional context**
This would help with late night working whereas most OSs support dark mode for applications where CW remains fairly "bright".

**Comment by Nancy-Chauhan** [comment] 2020-08-04 12:13
I would like to pick this issue. Is this open? @pranavrajs @iammattmartin

**Comment by pranavrajs** [comment] 2020-08-04 12:46
@Nancy-Chauhan please feel free to take it.

**Comment by iammattmartin** [comment] 2020-09-24 01:41
@Nancy-Chauhan Did you have any luck with this?

**Comment by pranavrajs** [comment] 2020-10-01 04:50
@Nancy-Chauhan Unassigning this as this was not picked up yet.

**Comment by gabrielhicks** [comment] 2020-10-05 18:50
I am interested and would appreciate working on this for hacktoberfest. If there is any specificity toward color schemes etc please let me know!

**Comment by ishitaojha** [comment] 2021-03-21 04:47
hey if the issue is still open can you assign it to me ?

**Comment by muhsin-k** [comment] 2021-03-21 05:50
@ishitaojha Please feel free to go ahead.

**Comment by FatGrizzly** [comment] 2021-06-29 10:53
@ishitaojha Any updates on this one?
The community is eagerly waiting for Dark Mode

**Comment by iammattmartin** [comment] 2021-06-29 10:58
Doesn't appear to be.

For now we use Webcatalog to apply a dark mode. Works fairly well.

![Screenshot 2021-06-29 at 11 54 52 AM](https://user-images.githubusercontent.com/15971590/123786119-3db57a00-d8d1-11eb-84be-acca000ed152.png)

**Comment by iammattmartin** [comment] 2021-06-29 11:03
Wonder if something like https://darkmodejs.learn.uno/ would be a quick fix.

**Comment by pranavrajs** [comment] 2021-07-10 15:51
@iammattmartin Tried it. It doesn't work. Please see the screenshot below :(
<img width="1920" alt="Screenshot 2021-07-10 at 9 20 56 PM" src="https://user-images.githubusercontent.com/2246121/125168793-ccc16c80-e1c4-11eb-87ef-eb8488d0f038.png">

**Comment by ishitaojha** [comment] 2021-07-10 16:01
> @ishitaojha Any updates on this one?
> The community is eagerly waiting for Dark Mode

No Not yet I was working on it but Wasn't able to resolve

**Comment by bphan002** [comment] 2022-08-25 03:00
Can I give this a try?

**Comment by iammattmartin** [comment] 2023-01-21 23:56
Just to update this. webcatalog which we use to container the CW UI uses "Dark Reader".

https://darkreader.org/

This works well, maybe this could be reviewed to passthrough the CSS to make dark mode easily.

**Comment by Leandroledledled** [comment] 2023-02-26 04:51
> Só para atualizar isso. webcatalog que usamos para conter a IU CW usa "Dark Reader".
> 
> https://darkreader.org/
> 
> Isso funciona bem, talvez isso possa ser revisado para passar pelo CSS para facilitar o modo escuro.

Perfect!

**Comment by pranavrajs** [comment] 2023-08-04 02:26
https://github.com/chatwoot/chatwoot/pull/7662

**Closed by pranavrajs** 2023-08-04 02:26 UTC
Labels: Good first issue, frontend, feature-request
