### ISSUE TITLE
[CW-1422] SMTP Error

### ISSUE THREAD

**Issue by muqaffa21** [chatwoot/chatwoot#6709] opened 2023-03-20 09:43 UTC
i've got error 

Failed to send Email
Exception: Net::SMTPSyntaxError
Performed ActionMailer::MailDeliveryJob (Job ID: f62ec37c-a1e1-4ee0-9237-8e59942b1d86) from Sidekiq(mailers) in 833.74ms

after upgrade to v2.15.0 

<sub>[CW-1422](https://linear.app/chatwoot/issue/CW-1422/smtp-error)</sub>

**Comment by donpauls** [comment] 2023-03-22 17:09
I have exactly the same problem. Unable to send emails via SMTP after upgrade to v2.15.0.
Tell me how to roll back to the previous version?

Here is the text of the error: 
```
Net::SMTPFatalError: 555 5.5.2 Syntax error
/usr/local/rvm/gems/ruby-3.1.3/gems/net-smtp-0.3.3/lib/net/smtp.rb:1076:in `check_response'
```

**Comment by Ziek-fw** [comment] 2023-03-22 17:18
Same error here:

chatwoot-worker.1[990]: W, [2023-03-22T16:32:23.989252 #990] WARN -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [a1ba1357-c5f6-413e-8d33-3366e509de2f] Error when sending Email.
Tue 22 16:32:23 fibwichat chatwoot-worker.1[990]: E, [2023-03-22T16:32:23:23.989423 #990] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [a1ba1357-c5f6-413e-8d33-3366e509de2f] Exception: Net::SMTPSyntaxError
Tue 22 16:32:23 fibwichat chatwoot-worker.1[990]: I, [2023-03-22T16:32:23:23.989758 #990] INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [a1ba1357-c5f6-413e-8d33-3366e509de2f] Done ActionMailer::MailDeliveryJob (Job ID: a1ba1357-c5f6-413e-8d33-3366e509de2f).

**Comment by Ziek-fw** [comment] 2023-03-22 18:54
After downgrading to version 2.14 the mail sending works again.

**Comment by pranavrajs** [comment] 2023-03-23 03:10
@donpauls @Ziek-fw @muqaffa21 Which SMTP provider are you using?

**Comment by Ziek-fw** [comment] 2023-03-23 09:55
@pranavrajs ISPConfig + Postfix

**Comment by donpauls** [comment] 2023-03-23 10:33
> @donpauls @Ziek-fw @muqaffa21 Which SMTP provider are you using?

Tried two providers: smtp.gmail.com, smtp.yandex.ru
And there and there the error is the same

**Comment by pranavrajs** [comment] 2023-03-24 02:16
@donpauls We don't have major changes in the last version in IMAP as far I remember. If reverting works, please go ahead.

cc:  @tejaswinichile @sojan-official

**Comment by donpauls** [comment] 2023-03-24 08:48
How to rollback to a previous version?
The update was done like this:
`# cwctl --upgrade`

**Comment by Ziek-fw** [comment] 2023-03-24 09:04
> How to rollback to a previous version? The update was done like this: `# cwctl --upgrade`

sudo -i -u chatwoot
cd chatwoot/
git fetch --tags
git checkout v2.14.0
bundle
yarn
rake assets:precompile RAILS_ENV=production
RAILS_ENV=production bundle exec rake db:migrate

# Switch back to root user
exit

# Copy the updated targets
cp /home/chatwoot/chatwoot/deployment/chatwoot-web.1.service /etc/systemd/system/chatwoot-web.1.service
cp /home/chatwoot/chatwoot/deployment/chatwoot-worker.1.service /etc/systemd/system/chatwoot-worker.1.service
cp /home/chatwoot/chatwoot/deployment/chatwoot.target /etc/systemd/system/chatwoot.target

# Reload systemd files
systemctl daemon-reload

# Restart the chatwoot server
systemctl restart chatwoot.target

**Comment by donpauls** [comment] 2023-03-24 09:48
Thank you!

**Comment by muqaffa21** [comment] 2023-03-28 04:07
i think this issue same with issue number #6706 , after we assign conversation to agent.

after this commit #6579 ,  then we facing this issue ...

**Comment by aerostovtsev** [comment] 2023-04-03 06:24
@sojan-official Hello!
I have the same error appeared(email is not sent, I use smtp.yandex.ru ) on v2.15.0 screenshot of the log https://i.imgur.com/Q4KmVum.png

There is a solution without rolling back to v2.14.0?

**Comment by Kinzi** [comment] 2023-04-03 07:34
Same error here. Hosting on cloudron.

**Comment by kallados** [comment] 2023-04-03 11:12
Same by me :/

**Comment by jdabeau** [comment] 2023-04-05 16:53
> > How to rollback to a previous version? The update was done like this: `# cwctl --upgrade`
> 
> # Login as Chatwoot user
> sudo -i -u chatwoot
> 
> # Navigate to the Chatwoot directory
> cd chatwoot/
> 
> # Downgrade
> git fetch --tags git checkout v2.14.0
> 
> # Update
> bundle yarn rake assets:precompile RAILS_ENV=production RAILS_ENV=production bundle exec rake db:migrate
> 
> # Switch back to root user
> exit
> 
> # Copy the updated targets
> cp /home/chatwoot/chatwoot/deployment/chatwoot-web.1.service /etc/systemd/system/chatwoot-web.1.service cp /home/chatwoot/chatwoot/deployment/chatwoot-worker.1.service /etc/systemd/system/chatwoot-worker.1.service cp /home/chatwoot/chatwoot/deployment/chatwoot.target /etc/systemd/system/chatwoot.target
> 
> # Reload systemd files
> systemctl daemon-reload
> 
> # Restart the chatwoot server
> systemctl restart chatwoot.target
> 
> Similar steps to update manually: https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm

I solved the problem following your steps. I was on 2.15.0, fresh installation from yesterday. Any mail could work. Now with 2.14.0 i can work with:

GOOGLE WORKSPACE
MAILS HOSTED IN MY DEDICATED WITH PLESK

Fantastic ♥

**Comment by gramakri** [comment] 2023-04-06 07:12
@sojan-official is it confirmed that this is a bug in Chatwoot? Do you need any more information ? Happy to help debug.

**Comment by sojan-official** [comment] 2023-04-10 15:02
@gramakri  seeing quite a few reports on this.  We are looking into this.

**Comment by tejaswinichile** [comment] 2023-04-10 15:45
@gramakri @aerostovtsev  Are you able to create the inbox? and not able to send emails.

**Comment by aerostovtsev** [comment] 2023-04-11 01:12
@tejaswinichile The mailbox is created, emails are successfully sent on v2.14.0 and early builds. Error only on v2.15.0

**Comment by tejaswinichile** [comment] 2023-04-12 05:05
Investigation: 

Exception:: Net::SMTPSyntaxError/Net::SMTPSyntaxError\[555 5.5.2 Syntax error\]: Appears when the assignee name is in a different script other than English. Or SMTP is not able to parse the email address.

I was able to reproduce the above issue. 

```
Error performing ActionMailer::MailDeliveryJob (Job ID: some-job-id) 
  from Sidekiq(mailers) in 2536.36ms: Net::SMTPFatalError (555 5.5.2 Syntax error. s5-20020a63f045000000b005038291e5cbsm9534660pgj.35 - gsmtp
):
```

This can be resolved by appending from email the mail name header. Adding a fix for the same.

There was one more issue:

Net::SMTPAuthenticationError: is not related to the chatwoot app but to the mail provider, which blocks the unknown sender. Adding the sender email might resolve the issue but mostly you should turn on the settings for your app by turning on [https://myaccount.google.com/lesssecureapps](https://myaccount.google.com/lesssecureapps)

[https://support.google.com/a/answer/6260879?hl=en](https://support.google.com/a/answer/6260879?hl=en).

**Comment by Kinzi** [comment] 2023-04-13 05:00
The error is not only google related. I am using chatwoot on a cloudtron server and have the exact same issue. Not working since 2.15.

**Comment by Kinzi** [comment] 2023-04-13 05:01
It's discussed here: https://forum.cloudron.io/topic/8893/weird-email-issue/8?_=1680507150491

**Comment by kallados** [comment] 2023-04-13 12:29
Yes, I have the same Issue with Cloudron and tested two other providers (one VPS a second one dedic, both with Ubuntu) and got the same Output as well. There is no Name with some inconvenient letters etc. There must be some change between 2.15 and all older Versions.

**Closed** 2023-04-13 17:42 UTC
Labels: need-more-info, linear, 2 points, Customer Reported

**Comment by kallados** [comment] 2023-04-13 17:52
Is there some solution?

**Comment by pranavrajs** [comment] 2023-04-13 17:56
https://github.com/chatwoot/chatwoot/pull/6900

**Comment by pranavrajs** [comment] 2023-04-13 17:56
@kallados The fix is in the #6900 PR. This would available in the 2.16 release on Monday.

**Comment by Sixth2538** [comment] 2023-04-18 07:16
hi @pranavrajs upgraded to 2.16 and still running into the same issue.

Self hosted with docker

Env variable:

```
SMTP_ADDRESS=smtp.sendgrid.net
SMTP_AUTHENTICATION=plain
SMTP_DOMAIN=xxx.xxx
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_PORT=587
SMTP_USERNAME=apikey
SMTP_PASSWORD=xx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Log from sidekiq:

![image](https://user-images.githubusercontent.com/111109779/232700581-9ccd206b-d42f-4083-b8f5-9098e5db2ee0.png)

**Comment by tejaswinichile** [comment] 2023-04-18 08:46
@Sixth2538 Is this issue appearing only for reset password instruction emails?

**Comment by Sixth2538** [comment] 2023-04-18 09:50
@tejaswinichile happens with confirmation email as well

![image](https://user-images.githubusercontent.com/111109779/232740373-e899e804-4f49-4541-b12b-0c2ca469ee52.png)
