### ISSUE TITLE
Can't we just attach file_resource here?

### ISSUE THREAD

**Issue by SmartManoj** [chatwoot/chatwoot#1469] opened 2020-12-01 08:26 UTC
https://github.com/chatwoot/chatwoot/blob/a5ceddc454efe56a0837053bd8ad1e6b970e4270/app/services/twilio/incoming_message_service.rb#L103-L107

Like in https://github.com/chatwoot/chatwoot/blob/a5ceddc454efe56a0837053bd8ad1e6b970e4270//app/builders/messages/message_builder.rb#L24

if we rename file_type to content_type in local_resource.rb file

**Comment by pranavrajs** [comment] 2020-12-22 12:56
I don't understand the issue here. Closing it as it is not a bug or an enhancement request.

**Closed by pranavrajs** 2020-12-22 12:56 UTC
