### ISSUE TITLE
Unassigned conversations display only messages intended for the user's group

### ISSUE THREAD

**Issue by clarcksp** [chatwoot/chatwoot#7645] opened 2023-07-30 14:19 UTC
### Is your feature or enhancement related to a problem? Please describe.

Hello.
I'm using the application in a scenario where we will have several teams distributed among all users, but the unassigned conversations show all messages for all teams that don't have any agent linked.
Is it possible to keep conversations unassigned by showing only the messages corresponding to the users of the team to which it is linked?

### Describe the solution you'd like

In this scenario, we have an average of 1,000 messages per day and it must go through several sectors until it is resolved.
As the sectors also have different users, they should assign the message to themselves. In this way, the message should only appear to the team members who, in turn, would make this assignment automatically.

**Comment by pranavrajs** [comment] 2023-08-15 19:23
Duplicate of #6422 and it should be solved by https://github.com/chatwoot/chatwoot/pull/7649

**Closed by pranavrajs** 2023-08-15 19:23 UTC
Labels: ✨ feature-request
