### ISSUE TITLE
arm64 images for docker

### ISSUE THREAD

**Issue by physx2494** [chatwoot/chatwoot#7939] opened 2023-09-19 05:07 UTC
### Is your feature or enhancement related to a problem? Please describe.

arm instances across hyperscalers as compared to x64 are very cheap and value for money. Currently, it is not possible to host chatwoot on an arm64 VM.

### Describe the solution you'd like

It would be excellent if Chatwoot could provide arm64 docker images to host the server on arm64 machines.

**Comment by iammattmartin** [comment] 2023-09-20 11:58
Dupe 
#2575 #7470

**Comment by pranavrajs** [comment] 2023-09-22 07:13
Closing as duplicate of #7470

**Closed by pranavrajs** 2023-09-22 07:13 UTC

**Comment by microtec1989** [comment] 2023-10-20 02:01
It would be good if Chatwood ran on arm64 machines as there are many possibilities for implementation and development on these machines currently. I already have several apps running on these machines, now it's chatwoot's turn

**Comment by iamkhalidbashir** [comment] 2023-11-03 13:38
+1

**Comment by iamkhalidbashir** [comment] 2023-11-06 09:47
I have created an arm64 repo for chatwoot, which can be used untill officially supported by chatwoot-team
https://hub.docker.com/r/amoxt/chatwoot-arm

Note: I will try to build for latest versions, if I miss any, please reply me with this comment.

Best,
Khalid

**Comment by hostsistemas** [comment] 2023-11-19 14:48
> Eu criei um repositório arm64 para chatwoot, que pode ser usado até ser oficialmente suportado por chatwoot-team https://hub.docker.com/r/amoxt/chatwoot-arm
> 
> Nota: tentarei construir para as versões mais recentes, se perder alguma, responda-me com este comentário.
> 
> Atenciosamente, Khalid

please update🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼

**Comment by hostsistemas** [comment] 2023-11-19 14:50
> 🙏🏼🙏🏼🙏🏼🙏🏼



> Eu criei um repositório arm64 para chatwoot, que pode ser usado até ser oficialmente suportado por chatwoot-team https://hub.docker.com/r/amoxt/chatwoot-arm
> 
> Nota: tentarei construir para as versões mais recentes, se perder alguma, responda-me com este comentário.
> 
> Atenciosamente, Khalid



> I have created an arm64 repo for chatwoot, which can be used untill officially supported by chatwoot-team https://hub.docker.com/r/amoxt/chatwoot-arm
> 
> Note: I will try to build for latest versions, if I miss any, please reply me with this comment.
> 
> Best, Khalid

update please 🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼

**Comment by iamkhalidbashir** [comment] 2023-11-22 08:13
> > 🙏🏼🙏🏼🙏🏼🙏🏼
> 
> > Eu criei um repositório arm64 para chatwoot, que pode ser usado até ser oficialmente suportado por chatwoot-team https://hub.docker.com/r/amoxt/chatwoot-arm
> > Nota: tentarei construir para as versões mais recentes, se perder alguma, responda-me com este comentário.
> > Atenciosamente, Khalid
> 
> > I have created an arm64 repo for chatwoot, which can be used untill officially supported by chatwoot-team https://hub.docker.com/r/amoxt/chatwoot-arm
> > Note: I will try to build for latest versions, if I miss any, please reply me with this comment.
> > Best, Khalid
> 
> update please 🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼

Done! v3.3.1
