### ISSUE TITLE
Date/time localization

### ISSUE THREAD

**Issue by hartois** [chatwoot/chatwoot#1778] opened 2021-02-16 05:36 UTC
How can we localize date/time in conversations?
![image](https://user-images.githubusercontent.com/11641656/108022603-ea354480-7031-11eb-8429-06e994d96f9e.png)

**Comment by pranavrajs** [comment] 2023-05-25 19:15
Duplicate of https://github.com/chatwoot/chatwoot/issues/953

**Closed by pranavrajs** 2023-05-25 19:15 UTC
