### ISSUE TITLE
chatwoot and google chrome

### ISSUE THREAD

**Issue by rabeb00** [chatwoot/chatwoot#2663] opened 2021-07-19 11:48 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated 
We use Chatwood in Google Chrome and it does not work fully...f.ex. i can't see if somebody is typing of wants to chat with me.
should i change my google chrome settings ..location, notifications ect.
help! With kind regards Ben

**Describe alternatives you've considered**

**Additional context**

**Comment by iammattmartin** [comment] 2021-07-19 20:14
Are you using self-hosted or cloud versions?

and just to confirm, do you mean in the staff interface or widget?

**Comment by rabeb00** [comment] 2021-07-19 20:51
hi Matt, they use the self hosted version
i am analysing an incident for a department of our organization




Op ma 19 jul. 2021 22:14 schreef Matt ***@***.***>:

**Comment by iammattmartin** [comment] 2021-07-19 20:53
Have you tested other browsers to see if the issue is consistently replicated?

Do you get any errors in the dev console for the widget or staff area also, if only happening in Chrome?

**Comment by rabeb00** [comment] 2021-07-19 20:59
in Firefox it works fine...

Op ma 19 jul. 2021 22:53 schreef Matt ***@***.***>:

**Comment by iammattmartin** [comment] 2021-07-19 21:00
Ok, console logs with errors will be next step from Chrome.

**Comment by rabeb00** [comment] 2021-07-19 21:01
they only use the chatwoot app for chatting..texting ..

Op ma 19 jul. 2021 22:53 schreef Matt ***@***.***>:

**Comment by rabeb00** [comment] 2021-07-19 21:02
console logs?
How do i get the logs?

Op ma 19 jul. 2021 23:00 schreef Matt ***@***.***>:

**Comment by iammattmartin** [comment] 2021-07-19 21:09
Maybe check https://support.happyfox.com/kb/article/882-accessing-the-browser-console-and-network-logs/.

I have tested with Chrome and cannot see an issue and get notified of someone typing.

**Comment by rabeb00** [comment] 2021-07-19 21:22
hi Matt, i will go to bed it;s late in The Netherlands. In our organization
we use a Proxy server with caching function. Maybe that's the issue.
Thank you for your support. With kind regards Ben Raben

Op ma 19 jul. 2021 om 23:09 schreef Matt ***@***.***>:

**Comment by rabeb00** [comment] 2021-07-20 19:41
hi matt,
i think i found the couse...the protocol websocket is blocked...not allowed
on our proxy/firewall.
Could that be the issue, you also think?
with kind regards, Ben

Op ma 19 jul. 2021 22:14 schreef Matt ***@***.***>:

**Comment by sojan-official** [comment] 2021-07-20 19:54
@rabeb00 Hey Ben, Chatwoot uses WebSockets to deliver real-time updates, like new messages, typing indicators, etc. 
So without the WebSockets open, the chatwoot experience wouldn't be ideal.

**Comment by rabeb00** [comment] 2021-07-20 20:03
hi , is this somewhere documented?
I took my three days to detect this...
tomorrow the network department will enable websocket for a specific
website...
i am optimistic....
with kind regards, Ben



Op di 20 jul. 2021 21:55 schreef Sojan Jose ***@***.***>:

**Comment by iammattmartin** [comment] 2021-07-20 21:11
I'm not sure it needs to be. The "modern web" uses websockets a lot. As this uses existing ports and does not need any special ports, it would be unrealistic to expect every site you visit to say they need it.

The browser console should always be one of the first go-tos in situations like this and you'd have likely seen the websockets (wss://) timeout fairly quickly.

**Comment by rabeb00** [comment] 2021-07-21 20:18
Hi.
This case is still not solved...
So i attached an netwerk trace from Google Chrome latest version.
As said in our organiation ( 36000 desktops)  browser traffic to the
Internet must pass a proxy/firewall server.
Any idea?
Is there a setting in Google Chome that controls the websocket protocol ?
With kind regards, Ben



Op di 20 jul. 2021 om 22:03 schreef Ben Raben ***@***.***>:

**Comment by iammattmartin** [comment] 2021-07-21 21:39
I would recommend updating your issue on github. 

You need to look at the Google console as already advised. If you are getting websockets connection issues, it's an environment issue you'll need to resolve.

Chatwoot does not have any issues specific to Chrome otherwise it would be replicable and other users would be reporting it.

**Comment by rabeb00** [comment] 2021-07-22 07:01
hi Matt,
the attachment shows the developers tool/ Console..in google chrome.
With kind regards, Ben

Op wo 21 jul. 2021 23:39 schreef Matt ***@***.***>:

**Comment by iammattmartin** [comment] 2021-07-22 09:37
You'll need to update via Github as already advised.

**Comment by pranavrajs** [comment] 2022-03-14 15:43
Closing this as the issue is not related to Chatwoot but the config in the reverse proxy.

**Closed by pranavrajs** 2022-03-14 15:43 UTC
