### ISSUE TITLE
Stream Messages

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1128] opened 2020-08-09 00:04 UTC
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The inbox view is static and appears to not update unless the page is refreshed. It would be nice to have this refresh/poll at regular intervals so if you have the page open in a tab, or in an app like "Fluid" when you go to it, it won't look like it has no messages (unless you manually refresh.

**Comment by pranavrajs** [comment] 2020-08-09 06:14
@iammattmartin I couldn't completely understand the issue. Is this the duplicate of #995

**Comment by iammattmartin** [comment] 2020-08-09 17:25
Looks like it is quite similar.

I was just talking about the inbox messages, so brand new conversations appear without having to refresh but I suspect this could all be related under to the same bit of work. :)

**Comment by pranavrajs** [comment] 2020-08-09 18:03
Yes, this is the same. Closing the issue as it is a duplicate

**Closed by pranavrajs** 2020-08-09 18:03 UTC
