### ISSUE TITLE
Message with image does not trigger webhook

### ISSUE THREAD

**Issue by torquan** [chatwoot/chatwoot#3430] opened 2021-11-21 14:59 UTC
**Describe the bug**

For inboxes of type "api" a webhook is triggered if a message is sent in Chatwoot. There's also an event on the webhook that can be added in Settings -> Integrations.

If a message includes an image, there is no webhook triggered.

**To Reproduce**

1. Create API Inbox
2. Listen to the webhook, for quick reproduction for ex. via webhook.site
3. Send a message in that inbox.

**Expected behavior**

A webhook event containing the image or a link to the image.

**Screenshots**
Nothing happens after sending.

**Browser logs**
Message is received successfully by chatwoot:
```
{
  "id": 265,
  "content": null,
  "inbox_id": 30,
  "echo_id": "e14c168e4b5f",
  "conversation_id": 1,
  "message_type": 1,
  "content_type": "text",
  "content_attributes": {},
  "created_at": 1637506886,
  "private": false,
  "source_id": null,
  "sender": {
    "id": 1,
    "name": "Admin",
    "available_name": "Admin",
    "avatar_url": "https://www.gravatar.com/avatar/0c7e5c1d3729176a49fe8de41764ea81?d=404",
    "type": "user",
    "availability_status": "online",
    "thumbnail": "https://www.gravatar.com/avatar/0c7e5c1d3729176a49fe8de41764ea81?d=404"
  },
  "attachments": [
    {
      "id": 42,
      "message_id": 265,
      "file_type": "image",
      "account_id": 24,
      "extension": null,
      "data_url": "https://[redacted]/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBMdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c22bb6de604671bdac85e906849e73725487e36e/lights.jpg",
      "thumb_url": "https://[redacted]/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBMdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c22bb6de604671bdac85e906849e73725487e36e/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2QzNKbGMybDZaVWtpRERJMU1IZ3lOVEFHT3daVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--9e5c654eeeb50a4aa82d784732a8369c5f2103c7/lights.jpg"
    }
  ]
}

```

**Server logs**

Didn't find any logs. I tried running these commands:
https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm/#viewing-logs.
Results were empty.

**Environment**

self-hosted via caprover on a Ubuntu VPS

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version Chatwoot v1.21.0

**Smartphone (please complete the following information):**
not used

**Additional context**

**Comment by pranavrajs** [comment] 2021-11-22 18:07
@torquan I will test it out and see if I can reproduce this.

**Comment by torquan** [comment] 2021-11-22 18:35
I just tried to make a video of this, but this happened:
- image messages did appear but were quite delayed (with a 2KB image)
- they were out of order
- one image message triggered a webhook event of type text without content.


Here's the video https://streamable.com/9sh0z7. It got a bit long, sorry for that. If there's a better way I can help, please let me know.

**Comment by pranavrajs** [comment] 2023-01-04 22:44
Closing this as the issue is not reproducible in the latest release. @torquan Please feel free to reopen if it is not the case.

**Closed by pranavrajs** 2023-01-04 22:44 UTC
Labels: investigation
