### ISSUE TITLE
[CW-1857] After upgrading to 2.17.0, after creating a new message in API Channel, sometimes the corresponding event is not sent through the channel Webhook

### ISSUE THREAD

**Issue by luissakihama** [chatwoot/chatwoot#7168] opened 2023-05-22 19:41 UTC
### Describe the bug

After upgrading to 2.17.0, when creating a new message in API Channel, sometimes the corresponding event is not sent through the channel Webhook. This behavior is not observed in versions 2.16 or before.

Also tried with Webhook Integration with subscription for events when message is created. The same behavior was seen.

### To Reproduce

1. Create a API Channel Inbox with a Webhook URL
2. Open a Conversations
3. Send several outgoing messages and look for the events sent through the Webhook URL

### Expected behavior

All messages are created but only some of them has associated events in the Webhook URL

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu 22.04.2 LTS

### Browser and version

Brave 1.51.114

<sub>[CW-1857](https://linear.app/chatwoot/issue/CW-1857/after-upgrading-to-2170-after-creating-a-new-message-in-api-channel)</sub>

**Comment by luis-notifai** [comment] 2023-05-30 18:26
Hi, 

here is an update. I saw the same behavior in 2.16. At first seems that everything was ok in 2.16, because we weren't using constantly. But now when we start to do it we detect the same issue in 2.16.

Please let me know if you find something. 

Thanks in advance.

**Comment by luissakihama** [comment] 2023-05-30 18:27
Hi,

here is an update. I saw the same behavior in 2.16. At first seems that everything was ok in 2.16, because we weren't using constantly. But now when we start to do it we detect the same issue in 2.16.

Please let me know if you find something.

Thanks in advance.

**Comment by luissakihama** [comment] 2023-05-30 21:43
Also found errors in the Sidekiq dashboard, but not sure how to interpret them

<img width="1439" alt="image" src="https://github.com/chatwoot/chatwoot/assets/26125876/850ca818-43f8-4030-8725-dd9cc4e4378d">
<img width="1438" alt="image" src="https://github.com/chatwoot/chatwoot/assets/26125876/6d110877-0437-4cc5-a74d-7d3d6ae0f8b8">

**Comment by luissakihama** [comment] 2023-05-30 22:46
I was using AWS ElasticCache for Redis, so I decided to try replacing for internal Redis and it solved the problem. So at the end, I assumed incorrectly that the issue was related to upgraded but it seems that it always present. Not sure what in the AWS ElasticCache was causing the problem because the Redis Cluster has no errors.

**Comment by sojan-official** [comment] 2023-05-31 12:34
@luissakihama Thanks for reporting back.  There shouldn't be any issues with elastic cache specifically, though, as we have other users using it.   

I'm closing this for now because the issue is resolved. let's reopen if it persists.

**Closed by sojan-official** 2023-05-31 12:34 UTC
Labels: bug, investigation, linear
