### ISSUE TITLE
After sign in not show view

### ISSUE THREAD

**Issue by lambk2211** [chatwoot/chatwoot#2635] opened 2021-07-15 08:37 UTC
**Describe the bug**

**To Reproduce**

1. Login 

**Expected behavior**

![photo_2021-07-15_15-34-42](https://user-images.githubusercontent.com/57747823/125756703-21a04cb1-e85f-44e5-a35d-181b4da75581.jpg)

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**
i install linux after create db, create user with sso_token and login success but have meet issue. I don't know more about vuejs.
How can i fixed it. Thank you very much

**Comment by lambk2211** [comment] 2021-07-15 10:06
ah, this is my fault, i forget create account for user

**Comment by pranavrajs** [comment] 2021-07-15 10:18
Closing as the issue is solved.

**Closed by pranavrajs** 2021-07-15 10:18 UTC
