### ISSUE TITLE
Inbox is not creating for fb channel

### ISSUE THREAD

**Issue by muzammal-murtaza** [chatwoot/chatwoot#1840] opened 2021-02-27 20:35 UTC
**Describe the bug**

Whenever i try to create inbox of facebook i get following error on console
_**Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true excluded from capture: DSN not set

```
ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
    2: json.channel_id @facebook_inbox.channel_id
    3: json.name @facebook_inbox.name
    4: json.channel_type @facebook_inbox.channel_type
    5: json.avatar_url @facebook_inbox.try(:avatar_url)
    6: json.page_id @facebook_inbox.channel.try(:page_id)
    7: json.enable_auto_assignment @facebook_inbox.enable_auto_assignment**_
```

**Screenshots**
![Screenshot from 2021-02-28 01-34-55](https://user-images.githubusercontent.com/68580311/109399532-2d15e700-7965-11eb-9d80-4479b227f5ca.png)

**Environment**

a self hosted installation of Chatwoot.

**Comment by pranavrajs** [comment] 2021-02-28 07:41
Please set `FRONTEND_URL` as described here. https://www.chatwoot.com/docs/environment-variables#configure-frontend-url

**Comment by pranavrajs** [comment] 2021-02-28 07:43
Closing the issue as it is not a bug. @muzammal-murtaza Please feel free to reopen this if it does not resolve your problem.

**Closed by pranavrajs** 2021-02-28 07:43 UTC

**Comment by muzammal-murtaza** [comment] 2021-02-28 09:54
Now inbox is created but i am not getting messages, do i need more comfiguration for that?

**Comment by sojan-official** [comment] 2021-02-28 13:46
@muzammal-murtaza  please finish the set up as described here https://www.chatwoot.com/docs/facebook-setup
