### ISSUE TITLE
docker production issue

### ISSUE THREAD

**Issue by lybtt** [chatwoot/chatwoot#1696] opened 2021-01-26 13:32 UTC
I run chatwoot with docker, it likes this:

![image](https://user-images.githubusercontent.com/38394058/105851250-c75cd500-601d-11eb-87ec-5a3a78f8a54d.png)

 Now I want to change some words in html, how to make the modified html effective? 

![image](https://user-images.githubusercontent.com/38394058/105851357-ee1b0b80-601d-11eb-84dd-8d3cd130ea41.png)

**Comment by iammattmartin** [comment] 2021-01-26 14:34
Why hello?

This is not a message greeting.

**Comment by lybtt** [comment] 2021-01-26 14:42
> Why hello?
> 
> This is not a message greeting.

This is just one example :)

**Comment by iammattmartin** [comment] 2021-01-26 14:44
You'll likely be on your own here but it's not a bug in any case.

**Comment by lybtt** [comment] 2021-01-26 14:48
> You'll likely be on your own here but it's not a bug in any case.

I'm so sorry,  I used the template and forgot to change the label.

**Comment by iammattmartin** [comment] 2021-01-26 15:01
Worth closing if you've sorted it then.

**Closed** 2021-01-31 16:14 UTC
Labels: Question
