### ISSUE TITLE
API Contact search + fails

### ISSUE THREAD

**Issue by Stephen-Lobo** [chatwoot/chatwoot#3495] opened 2021-12-01 12:22 UTC
**Describe the bug**
Search contact via API fails if contact number contains **+** Prefix 

**To Reproduce**

1. Search any contact with + and without + prefix through GET Command Via API / Postman
2. For eg use contact number +123456789. The search does not works. 
3. Now search same contact number without +, it works. 

**Expected behavior**
API Get command for search should also consider when contact number contains + prefix.

**Environment**

Self hosted
Latest chatwoot version

**Comment by pranavrajs** [comment] 2021-12-01 17:47
Hey Stephen, Can you please share a screencast? It seems like the API is working for me with or without + sign, and I see that we have covered this issue already here https://github.com/chatwoot/chatwoot/pull/3241/files

**Comment by Stephen-Lobo** [comment] 2021-12-02 13:19
There is definitely search bug in current version. Pls see screenshot video:

https://user-images.githubusercontent.com/87435610/144429646-1fdf6c60-b996-49fd-91f5-01600be73ab6.mov

**Comment by Stephen-Lobo** [comment] 2021-12-11 13:29
@pranavrajs 

Friendly bump.

**Comment by sojan-official** [comment] 2021-12-19 04:19
@pranavrajs  Seems like the previous PR opted for filtering the value on the frontend.  We could probably remove that and just implement a filter in the backend.

**Comment by pranavrajs** [comment] 2022-09-27 01:19
Closing this as the issue is resolved in recent releases.

**Closed by pranavrajs** 2022-09-27 01:19 UTC
Labels: need-more-info
